### ISSUE TITLE
New golang release: Go 1.18

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#1043]
**What would you like to be enhanced**
: go v1.18 사용 (gomod, docker image 등)

**Why is this needed**
 - 최신 릴리스 적용 (Go 1.18 is released! 15 March 2022)
 - Generics 이 추가되어 코드 개선 가능성이 높아짐.

**Proposed solution**
: go v1.18로 시스템 동작 여부 확인 및 설정 변경

**note**
: 급하게 결정할 필요는 없습니다.

https://go.dev/blog/go1.18

> Go 1.18 is released!
> 
> The Go Team
> 15 March 2022
> 
> Today the Go team is thrilled to release Go 1.18, which you can get by visiting the [download page](https://go.dev/dl/).
> 
> Go 1.18 is a massive release that includes new features, performance improvements, and our biggest change ever to the language. It isn’t a stretch to say that the design for parts of Go 1.18 started over a decade ago when we first released Go.
> 
> Generics
> In Go 1.18, we’re introducing new support for [generic code using parameterized types](https://go.dev/blog/why-generics). Supporting generics has been Go’s most often requested feature, and we’re proud to deliver the generic support that the majority of users need today. Subsequent releases will provide additional support for some of the more complicated generic use cases. We encourage you to get to know this new feature using our [generics tutorial](https://go.dev/doc/tutorial/generics), and to explore the best ways to use generics to optimize and simplify your code today. The [release notes](https://go.dev/doc/go1.18) have more details about using generics in Go 1.18.
> 
> Fuzzing
> With Go 1.18, Go is the first major language with fuzzing fully integrated into its standard toolchain. Like generics, fuzzing has been in design for a long time, and we’re delighted to share it with the Go ecosystem with this release. Please check out our [fuzzing tutorial](https://go.dev/doc/tutorial/fuzz) to help you get started with this new feature.
> 
> Workspaces
> Go modules have been almost universally adopted, and Go users have reported very high satisfaction scores in our annual surveys. In our 2021 user survey, the most common challenge users identified with modules was working across multiple modules. In Go 1.18, we’ve addressed this with a new [Go workspace mode](https://go.dev/doc/tutorial/workspaces), which makes it simple to work with multiple modules.
> 
> 20% Performance Improvements
> Apple M1, ARM64, and PowerPC64 users rejoice! Go 1.18 includes CPU performance improvements of up to 20% due to the expansion of Go 1.17’s register ABI calling convention to these architectures. Just to underscore how big this release is, a 20% performance improvement is the fourth most important headline!
> 
> For a more detailed description of everything that’s in 1.18, please consult the [release notes](https://go.dev/doc/go1.18).
> 
> Go 1.18 is a huge milestone for the entire Go community. We want to thank every Go user who filed a bug, sent in a change, wrote a tutorial, or helped in any way to make Go 1.18 a reality. We couldn’t do it without you. Thank you.
> 
> Enjoy Go 1.18!

**Comment by seokho-son** [comment]
Hello @jihoon-seo @yunkon-kim

**Comment by jihoon-seo** [comment]
몇 달 째 Go 1.18 을 사용했는데, CB-Tumblebug 및 CB-Spider 등에서 특별한 이슈가 발생하지 않았습니다. 😊

지금 보니 Go 1.19 도 나왔네요 ㅎㅎ
https://go.dev/blog/go1.19
https://go.dev/dl/

**Comment by seokho-son** [comment]
@jihoon-seo 1.18의 개선판도 나왔군요! :) 
TB는 업데이트하면 좋을 것 같은데, 다른 FW가 어떻게 하실지는 잘 모르겠어요.

1.19로 넘어가볼까요?

**Comment by powerkimhub** [comment]
@jihoon-seo 

- go.mod 내부 go version도 `go 1.18`로 변경해서 사용해본 건지요?

**Comment by jihoon-seo** [comment]
@powerkimhub 네 테스트해 보니 특별한 이슈가 발생하지 않았습니다. 😊

**Comment by powerkimhub** [comment]
@jihoon-seo 

- 확인 감사합니다. 
- Spider도 조만간 업데이트 해보겠습니다.

**Comment by yunkon-kim** [comment]
@seokho-son @jihoon-seo @powerkimhub 

1.19 패치노트를 확인해보니 기존 Library가 개선되었습니다. (Minor changes 이지만, 기능에 영향을 줄 수 있을 것 같습니다.)
- 참고: [Minor changes to the library](https://tip.golang.org/doc/go1.19#minor_library_changes)

CB-Larva도 관련된 사항이 있어 `1.19`를 적용해볼 계획입니다. 이슈가 있으면 공유 드리겠습니다 ^^

**Comment by seokho-son** [comment]
커뮤니티 회의를 통해 1.19로 업그레이드 및 시험 진행하는 것으로 논의 되었습니다. :)

**Comment by jihoon-seo** [comment]
테스트를 하나 해 보았습니다.

"`go.mod` 에 `go 1.19` 라고 명시되어 있는 CB-Spider" 를 import 하는
"`go.mod` 에 `go 1.16` 라고 명시되어 있는 CB-Tumblebug" 를 빌드해 보았는데
빌드가 되었습니다. 😊
