### ISSUE TITLE
Register all existing CSP resources for each cloudConnection to CB-TB objs

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#1055]
이슈 #918 를 통해 개별 자원에 대한 CSP-native 자원 등록 기능이 추가되었습니다.

- #983
  - #1018
- #990
- #1016
  - #1019
- #1046 (POST [​/ns​/{nsId}​/registerCspVm](https://cloud-barista.github.io/cb-tumblebug-api-web/?url=https://raw.githubusercontent.com/cloud-barista/cb-tumblebug/main/src/api/rest/docs/swagger.yaml#/[Infra%20service]%20MCIS%20Provisioning%20management/post_ns__nsId__registerCspVm))

일일이 CSP-native 자원의 ID 정보를 읽어서, 등록을 실행하는 것은 사용자에게 너무 어려울 것 같습니다.
따라서, connectionConfig 단위로 관련 리소스 정보를 조회해서, 조회된 리소스들 중 CB-TB가 이미 관리하고 있지 않은 자원을
등록하는 기능 및 API를 만들면 좋을 것 같습니다.

POST [​/inspectResources](https://cloud-barista.github.io/cb-tumblebug-api-web/?url=https://raw.githubusercontent.com/cloud-barista/cb-tumblebug/main/src/api/rest/docs/swagger.yaml#/[Admin]%20System%20management/post_inspectResources)

로 각 리소스 타입에 대해 조회하고, CB-TB 오브젝트로 관리되지 않는 자원들만 리스팅하여
CB-TB 오브젝트로 등록하기를 수행하도록 구성하면 될 것 같습니다.

**Comment by jihoon-seo** [comment]
[지금까지 만든 함수를 호출할 때 사용자가 명시해야 하는 값들]

`registerExistingVNet` 등은
- NS ID (API path 내에 명시)
- `name` (← 이 이름으로 Spider 에 자원 유무를 lookup)
- `connectionName`

를 명시해야 하고,

`registerCspVm` 은
- NS ID (API path 내에 명시)
- MCIS name (API 호출의 JSON body에 명시; 해당 MCIS가 있으면 그 MCIS에 VM을 추가하고, 해당 MCIS가 없으면 신규 MCIS를 생성)
- `connectionName`
- ...

를 명시하도록 되어 있습니다.

---

새로 만들 함수가 MCIR + VM 등록을 수행하는 함수라고 가정하면
[새로 만들 함수를 호출할 때 사용자가 명시해야 하는 값들 (안)]
- NS ID (API path 내에 명시)
- `connectionName`
- MCIS name (API 호출의 JSON body에 명시; 해당 MCIS가 있으면 그 MCIS에 VM을 추가하고, 해당 MCIS가 없으면 신규 MCIS를 생성)
- (MCIR 이름은 NS prefix + Spider NameID 조합하여 자동 생성)
- (VM 이름은 NS prefix + MCIS name + Spider NameID 조합하여 자동 생성)

**Comment by seokho-son** [comment]
@jihoon-seo 혹시 해당 이슈 처리 가능하실까요?
어려우시면 제가 처리하겠습니다. :)

**Comment by seokho-son** [comment]
착수하였습니다. :)

**Comment by seokho-son** [comment]
Todo

- [x] API return body 구조 개선
- [] 자원간 연관관계 및 자원 정보 재구축 필요 (일부 가능한 항목만)
- [] SG 등록 관련 임의의 값 임시 지정한 항목 개선 필요
- [] 모든 connectionConfig 를 기준으로 등록하는 스크립트 추가 (아마도 기능으로 개발할 필요는 없을 듯..)

**Comment by seokho-son** [comment]
처리 속도 이슈가 있으나,
Spider의 lock 메커니즘에 의한 것으로 보임.

Spider에서 자원별 lock 에 대한 검토 예정.

https://github.com/cloud-barista/cb-tumblebug/discussions/1081#discussioncomment-2678021

**Comment by seokho-son** [comment]
https://github.com/cloud-barista/cb-spider/releases/tag/v0.5.5

https://github.com/cloud-barista/cb-spider/wiki/GetSGOwnerVPC()-and-GetVMUsingRS() 
연동 및 테스트 필요.
