### ISSUE TITLE
TB 오브젝트 ID 생성 방식 변경 (UUID->사용자지정ID)

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#109]
[개요]
TB 오브젝트 ID 생성 방식 변경 (UUID->사용자지정ID)

[현황]
TB는 오브젝트의 ID (예: MCIS ID)를 시스템이 생성한 UUID로 사용하고 있음.
오브젝트의 Name은 사용자가 지정하는 부가 정보로 사용함.
이 방식에는 장단점이 있으며, 선택의 문제임. 다만 아래의 단점을 고려하기로 함.
- 주요 연동 프레임워크인 CB-Spider와 처리 방식에 일관성이 다소 떨어짐.
- UUID는 사람이 인지하기 어려운 ID의 형태이며, 이에 의해 Test 등이 다소 까다로운 측면이 있음.

[수정방향] TB 오브젝트 ID 생성 방식을 변경 (UUID->사용자지정ID)
- 기존 API 및 처리 방식은 유지하되, API Call시 사용자가 지정한 오브젝트의 Name을 기반으로 ID를 생성.
- 오브젝트의 ID와 Name은 동일한 값을 가지게 됨. (예: Spec의 Name="goodSpec", ID="goodSpec")
- 사용자는 오브젝트의 Name을 Namespace 내에서 유일한 값으로 사용해야 함. (예: SpecNameList:["spec1", "spec2", "spec3"]인 경우, Spec의 Name으로 "spec2"를 사용하면, 중복 오류를 리턴) 

[수정방식]
GenUuid() 함수 코드 수정.
- ID 중복 확인 로직 추가 (가능한 별도의 함수로 구성)
- UUID 스트링 생성 주석 처리
- Name을 ID로 리턴

**Comment by seokho-son** [comment]
Related issues: #85 , #84

**Comment by jihoon-seo** [comment]
이 issue 는 close 해도 될 것으로 보입니다.

#110 에서의 API 변경사항
- `nsReq` struct 에 `Id string` 이 있었는데 주석처리 했습니다.
- 다음 struct 에 `Name string` 이 없었는데 추가했습니다.
  - `imageReq`, `imageInfo`
  - `networkReq`, `networkInfo`
  - `publicIpReq`, `publicIpInfo` (FYI: Spider & TB 에서 PublicIP 관리기능 제거 예정)
  - `securityGroupReq`, `securityGroupInfo`
  - `sshKeyReq`, `sshKeyInfo`
  - `subnetReq`, `subnetInfo`
  - `vNicReq`, `vNicInfo` (FYI: Spider & TB 에서 vNic 관리기능 제거 예정)
