### ISSUE TITLE
Problematic logic in ListResource

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#1099]
https://github.com/cloud-barista/cb-tumblebug/blob/main/src/core/mcir/common.go

ListResource 에서 
// ListResource returns the list of TB MCIR objects of given resourceType
func ListResource(nsId string, resourceType string) (interface{}, error) {
https://github.com/cloud-barista/cb-tumblebug/blob/main/src/core/mcir/common.go#L759

https://github.com/cloud-barista/cb-tumblebug/blob/main/src/core/mcir/common.go#L787
코드를 보면
```
keyValue, err := common.CBStore.GetList(key, true)
keyValue = cbstore_utils.GetChildList(keyValue, key)
```
이 과정에서 keyValue == nil, err == nil 인 상황이 발생(해당 타입에 대한 아무런 자원이 등록되어 있지 않는 경우)하여 
결과적으로
```
return nil, nil // When err == nil && keyValue == nil
```
https://github.com/cloud-barista/cb-tumblebug/blob/main/src/core/mcir/common.go#L860
에 이를 수 있어 보입니다.

인터페이스를 리턴하는 ListResource 를 활용하는 코드들에서
해당 인터페이스를 리소스 타입에 따라, 타입을 주입하는 경우가 있는데,
ex: `content.VNet = resourceList.([]TbVNetInfo)` // type assertion (interface{} -> array)

인터페이스가 nil인 경우에, 런타임 에러가 발생할 수 있습니다. (이때는 error도 nil이기 때문에, error 확인 코드를 지나치게 됩니다.)

따라서, 지금은 error에 대한 예외 처리 이외에, 추가적으로 인터페이스가 nil 인 경우에 대한 예외 처리도 필요하게 되는 것 같습니다.

개선이 필요할까요? PTAL: @jihoon-seo

**Comment by jihoon-seo** [comment]
`ListResource()` 의 references 중
- `securitygroup.go` 는 PR #1101 에서 보완되었고
- 나머지 references 는 아마도 비슷한 문제는 없을 것 같아 보입니다

@seokho-son 맞을까요? 😊

**Comment by seokho-son** [comment]
@jihoon-seo 나중에도 (다른 기능 추가시) 유사한 일이 발생할 수도 있지 않을까~ 해서요 ^^

return nil, nil
return 이 nil 이 되는 상황에는, 
차라리 error를 nil 대신 err로 제공하는게 나을까 싶기도 합니다. 
그럼 해당 함수를 사용하는 함수에서는 error 처리로 걸리겠죠?

**Comment by jihoon-seo** [comment]
현재 `ListResource()` 의 references 는

https://github.com/cloud-barista/cb-tumblebug/blob/349d440b7e211f312a34c717450f2f43fcfbd7fe/src/api/rest/server/mcir/common.go#L127-L145

https://github.com/cloud-barista/cb-tumblebug/blob/349d440b7e211f312a34c717450f2f43fcfbd7fe/src/core/mcis/utility.go#L387-L395

위와 같이 `ListResource()` 호출 직후에 `err != nil` 여부를 판단하여
`err != nil` 이면 즉시 return을 하고 있습니다.

만약 return이 nil 일 때 error를 nil이 아니라 err로 제공하면
- `ListResource()` 호출에는 문제가 없었으나 결과가 nil인 경우와
- `ListResource()` 호출에 문제가 있는 경우를

구분하지 못할 것 같습니다.

혹시 다른 좋은 방법이 있을까요? 🤔

**Comment by seokho-son** [comment]
@jihoon-seo 

https://github.com/cloud-barista/cb-tumblebug/pull/1104/files

이런 스타일을 생각했었습니다. :)
