### ISSUE TITLE
Add NLB capability to MCIS

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#1157]
**What would you like to be added**
CSP의 NLB (서비스)를 MCIS로 지원 (MCIS에 포함된 동일 CSP VM 그룹 한정)

**Why is this needed**
클라우드 인프라에는 하드웨어 수준으로 지원되는 LB가 필요한 경우가 많으며,
이는 클라우드 서비스 제공자를 통해서 서비스 형태로 제공 될 수 있음. (Cloud NLB)
CB-Spider 차원에서 CSP의 NLB가 추상화하고 있으며, 사용해볼 수 있는 API가 개발되었음.

이에 따라 CB-TB에서도 MCIS에 NLB를 반영하기 위한 현실적인 방안을 고안할 필요가 있음.

 - 1단계: CB-SP NLB관련 동작 현황 파악 및 API 테스트
 - 2단계: MCIS 형상 (필요시) 업데이트
 - 3단계: MCIS에 NLB 연계를 위한 기능 추가 (현재 모든 CSP에 대해 NLB를 제공하는 것이 아니므로, 불가능한 상황에도 대응할 수 있도록 주의하여 개발할 필요가 있음. NLB 관련 기능에 오류가 있을 수 있음을 감안하고, 오류를 미리 대응할 수 있도록 구성할 필요 있음.)
 - 4단계: NLB 관련 API 추가, MCIS 생성 등 API 개선
 - 5단계: 기본 동작 테스트

참고
- https://github.com/cloud-barista/cb-spider/wiki/Network-Load-Balancer-and-Driver-API
- https://github.com/cloud-barista/cb-spider/wiki/NLB-Test-Tool-Guide

**Comment by jihoon-seo** [comment]
[NLB 자원의 scope]
TB의 NLB 자원은 다음의 두 가지 중 하나 (또는 이외의 옵션) 로 정의할 수 있을 것 같은데,
어떤 것이 더 적합하다고 보이시나요? 😊

1. 다른 MCIR (vNet, SG, ...) 등과 동일하게
   namespace 범위의 자원이며
   특정 MCIS에 속하지는 않음
2. 특정 MCIS에 속함

**Comment by seokho-son** [comment]
> [NLB 자원의 scope] TB의 NLB 자원은 다음의 두 가지 중 하나 (또는 이외의 옵션) 로 정의할 수 있을 것 같은데, 어떤 것이 더 적합하다고 보이시나요? 😊
> 
> 1. 다른 MCIR (vNet, SG, ...) 등과 동일하게
>    namespace 범위의 자원이며
>    특정 MCIS에 속하지는 않음
> 2. 특정 MCIS에 속함

@jihoon-seo 질문 감사합니다. :) 

- 일단, Spider에서 정의한 NLBInfo struct와 API (현재)를 고려하면, 
  TB 기준, vNet은 NLB와 필수적으로 연계해야 할 것으로 판단하고 있습니다.
  vNet은 Namespaced 리소스이므로, NLB도 마찬가지로 (Namespaced 리소스로) 다루게 될 것 같습니다.

- 리소스 오브젝트 자체를 특정 MCIS에 속하도록 처리할 필요는 없을 것 같습니다. (실제로 내부적으로는 VM들에 의해 연계가 됩니다.) 다만, 고아 리소스(ex: vNet은 삭제되었는데, NLB는 삭제되지 않았다든지, NLB에 등록된 VM이 삭제되었는데 NLB 오브젝트에는 여전히 포함되어 있든지)가 생성되지 않도록 유의할 필요가 있겠습니다.

API: https://documenter.getpostman.com/view/9027676/UzQypiBx

```
type NLBInfo struct {
        IId             IID     // {NameId, SystemId}
        VpcIID          IID     // {NameId, SystemId}

        Type            string  // PUBLIC(V) | INTERNAL
        Scope           string  // REGION(V) | GLOBAL

        //------ Frontend
        Listener        ListenerInfo

        //------ Backend
        VMGroup         VMGroupInfo
        HealthChecker   HealthCheckerInfo

        CreatedTime     time.Time
        KeyValueList []KeyValue
}
```

**Comment by seokho-son** [comment]
@jihoon-seo 
1단계: CB-SP NLB관련 동작 현황 파악 및 API 테스트
및 MCIR 등과 마찬가지로, Spider의 API의 기능을 TB 단위 기능으로 올리는 작업을 부탁드려도 될까요?

 - TB API 생성 (우선: Create NLB, List NLB, Get NLB, Delete NLB // 향후: 나머지 add remove health 등)
 - TB NLB 오브젝트 생성 

일단 MCIS의 형상을 크게 고려하지 않고 진행해도 될 것 같습니다.

[Create NLB](https://documenter.getpostman.com/view/9027676/UzQypiBx#bd989a23-d434-473b-a681-4e7b0ed1f8f7)

SP API를 기준으로 대략 생각해본, TB NLB 생성 요청 struct의 예시 입니다.

```json
{
    "ConnectionName": "aws-ohio-config",
    "ReqInfo": {
                        "Name": "spider-nlb-01", (TB의 NLB 객체 ID와 동일)
                        "VNetID(VPCName)": "vpc-01", (TB vNet을 입력하면, SP VPCName으로 전달)
                        "Type": "PUBLIC", 
                        "Scope": "REGION",
                        "Listener": {
                                "Protocol" : "TCP",
                                "Port" : "22" 
                        },
                        "VMGroup": {
                                "Protocol" : "TCP",
                                "Port" : "22", 
                                "VMs" : ["vm-01", "vm-02"] (TB VMID를 입력하면, SP VPC Name으로 전달),
                                "MCIS" : "tb-mcis01" (Spider의 Struct에 없는 필드이며, VM아이디를 생성하기 위한 인자임)
                        },
                        "HealthChecker": {
                                "Protocol" : "TCP", 
                                "Port" : "22", 
                                "Interval" : "10", 
                                "Timeout" : "-1", 
                                "Threshold" : "3" 
                        }
    }
}
```
나머지 값들은 아직 상세 설정이 가능한 단계가 아니므로
default 값으로 지정하고, 사용자 입력은 가능하도록 처리하면 되겠습니다.

---

TB NLB 메타데이터 struct는 
[SP: Get NLB](https://documenter.getpostman.com/view/9027676/UzQypiBx#2b577125-ebac-478e-a3e8-35f8c62a47b3)
의 형상을 nested 형태로 가급적 유지하여, 향후 SP의 struct 변경시에도 쉽게 변경할 수 있도록 처리하면 어떨까 싶습니다.

**Comment by seokho-son** [comment]
@jihoon-seo 

NLB ID와 vmGroup ID를 동일하게 하여, (NLB Name을 입력 받지 않고, vmGroup ID를 NLB ID로 자동 처리)
향후 vmGroup에 연계된 NLB를 쉽게 찾을 수 있도록 처리하면 어떨까요?
