### ISSUE TITLE
Change func name `CoreDelAllMcis` into `DelAllMcis`

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#1232]
**What would you like to be enhanced**
: Change func name `CoreDelAllMcis` into `DelAllMcis`

**Why is this needed**
: CorePost is meaningless and not compatible with coding style

**Proposed solution**
: Search `CoreDelAllMcis` in source code (cb-tumblebug/src/*) and replace all with `DelAllMcis`

- Source code build test is required (try `make` on cb-tumblebug/src/)
- No functional test is required

**Comment by shrishti147** [comment]
hi, please assign me.

**Comment by seokho-son** [comment]
Thanks @shrishti147 
Let me know if you have any difficulty during contribution !

**Comment by ankitkumar0622** [comment]
Hi can you please assign me.

**Comment by seokho-son** [comment]
Hi @ankitkumar0622 
This issue was assigned to @shrishti147 already.

Let me open additional good first issue so that you can contribute :)

**Comment by arshad-k7** [comment]
Please look into my PR

**Comment by seokho-son** [comment]
Hi @shrishti147 
Let me accept the PR from @arshad-k7 
I will open `good first` issues so that you can keep contributing to our project!.
