### ISSUE TITLE
Suggestion: Refine structs in MCIS codes

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#125]
@seokho-son 

MCIR 코드에서
예를 들어 [`image.go`](https://github.com/cloud-barista/cb-tumblebug/blob/master/src/core/mcir/image.go) 를 보면

---

```Go
type SpiderImageReqInfo struct { // Spider
	ConnectionName string
	ReqInfo        ImageReqInfo
}
```
이것은 TB 가 Spider 에 API call 날릴 때 JSON body 를 만들기 위해 넣은 struct 입니다.
위 struct 를 Marshal 하여 JSON body 를 만듭니다.
=> 현재는 `SpiderImageReqInfoWrapper` 로 이름을 바꿨습니다.

---

```Go
type ImageReqInfo struct { // Spider
	//IId   IID 	// {NameId, SystemId}
	Name string
	// @todo
}

type ImageInfo struct { // Spider
	//IId     IID    // {NameId, SystemId}
	Name    string
	GuestOS string // Windows7, Ubuntu etc.
	Status  string // available, unavailable

	KeyValueList []common.KeyValue
}
```

~`ImageReqInfo`~ 는 위의 `SpiderImageReqInfo` 에서 필요로 하고,
~`ImageInfo`~ 는 Spider 의 응답을 Unmarshal 하기 위해 넣은 것입니다.
=> 현재는 `SpiderImageReqInfo` 는 사용하지 않고 있고,
`ImageInfo` -> `SpiderImageInfo` 로 이름을 바꿔서 
Req unmarshal & Response unmarshal 에 공통으로 활용하고 있습니다.

---

```Go
type imageReq struct {
	//Id             string `json:"id"`
	Name           string `json:"name"`
	ConnectionName string `json:"connectionName"`
	CspImageId     string `json:"cspImageId"`
	CspImageName   string `json:"cspImageName"`
	//CreationDate   string `json:"creationDate"`
	Description string `json:"description"`
}

type imageInfo struct {
	Id             string            `json:"id"`
	Name           string            `json:"name"`
	ConnectionName string            `json:"connectionName"`
	CspImageId     string            `json:"cspImageId"`
	CspImageName   string            `json:"cspImageName"`
	CreationDate   string            `json:"creationDate"`
	Description    string            `json:"description"`
	GuestOS        string            `json:"guestOS"` // Windows7, Ubuntu etc.
	Status         string            `json:"status"`  // available, unavailable
	KeyValueList   []common.KeyValue `json:"keyValueList"`
}
```

~`imageReq`~ 는 사용자가 TB 에 날리는 JSON body 를 Unmarshal 할 때에도 쓰이고,
`func createSshKey(nsId string, u *sshKeyReq) (sshKeyInfo, int, []byte, error) {` 등에도 쓰입니다.

~`imageInfo`~ 는 TB Object 생성 결과를 API 로 내어 주기 위해 JSON 으로 Marshal 할 때에도 쓰이고,
`func createSshKey(nsId string, u *sshKeyReq) (sshKeyInfo, int, []byte, error) {` 등에도 쓰입니다.

=> 각각 `TbImageReq`, `TbImageInfo` 로 이름을 바꿨습니다.

---

위와 같이,
~대문자로 시작하는 struct 는 Spider 와 통신하기 위해 넣은 것이며
소문자로 시작하는 struct 는 TB 에서 사용하기 위해 넣은 것입니다.~

---

MCIS 코드에서도 비슷하게 되어 있는 것 같은데
좀 더 정리가 되었으면 좋겠고..
(예: 제가 올릴 예정인 PR 에서 `vmCspViewInfo struct` 를 주석처리 했습니다.)

---

~struct 내 항목들, JSON 으로 나가는 항목들이
MCIR 코드에는 camelCase 로 되어 있고
MCIS 코드에는 snake_case 로 되어 있는 것도 있습니다.
통일감을 주는 방안도 있고, 그대로 두는 방안도 있겠습니다.~
=> Resolved by Change snakeCase to camelCase in MCIS #490

**Comment by seokho-son** [comment]
@jihoon-seo Let's enhance this point after Cappuccino release.

**Comment by jihoon-seo** [comment]
[Related PRs]
- Separate REST and core logic, and export MCIR structs and functions (#169)
- Rename and export MCIS structs and functions (#175)
- Integrate struct pairs xxxReq and xxxInfo (#181)
- Integrate struct TbVmReq into TbVmInfo, and update RestPostMcisVm (#188)
- Separate xxReq from xxInfo struct, and Add Swagger annotations (#198)

**Comment by seokho-son** [comment]
```
struct 내 항목들, JSON 으로 나가는 항목들이
MCIR 코드에는 camelCase 로 되어 있고
MCIS 코드에는 snake_case 로 되어 있는 것도 있습니다.
통일감을 주는 방안도 있고, 그대로 두는 방안도 있겠습니다.
```
Resolved by Change snakeCase to camelCase in MCIS #490
