### ISSUE TITLE
Terminated VM state handling needs to be supplemented

### ISSUE THREAD

**Issue by dogfootman** [cloud-barista/cb-tumblebug#1302]
**What happened**
: 

**What you expected to happen**
: 

VM 상태조회 부분에서 보완할 점이 있어서 알려드립니다.

mcis 조회 성능이 저하되는 현상이 있어서 확인해보니
aws에서 vm을 Teminate 된 vm 에 대한 정보 조회를 하려고 하면서 대기시간이 길어지는 경우가 있습니다.

vm 조회 결과
{
    ...
    "connectionName": "aws-cortado-con",
    "createdTime": "2023-03-14 23:51:19",    
    "specId": "mc01-t2-small",
    "sshKeyId": "mc01",
    "sshPort": "0",
    **"status": "Resuming",**
    "subGroupId": "vm001",
    "subnetId": "mc-sn01",
    **"systemMessage": "This VM has been terminated. No action is acceptable except deletion",**
    "targetAction": "Resume",
    "targetStatus": "Running",
    "vNetId": "mc-vpc01",
    "vmUserAccount": "cb-user"
}

위 결과에서 보듯이 vm은 terminated 되었으나 status가 Resunimg이 존재함에 따라 발생하는 현상으로 보입니다.

ControlVm(nsId string, mcisId string, vmId string, action string)에서 
UpdateVmInfo(nsId, mcisId, temp) 을 먼저 호출하고 spider을 호출하는데
결과에 따른 조치부분이 누락되어 해당 vm의 실제 상태와 상관없이 상태값이 변경되고

GetVmStatus(nsId string, mcisId string, vmId string) (TbVmStatusInfo, error) 에서
if cspVmId != "" && temp.Status != StatusTerminated {) 안으로 들어가게 되면서
retry count : 5, time Sleep : 5 second 로 25초 대기하게 됩니다.

이에 따라 해당 상태를 가진 vm이 1개라도 있게되면
mcis 전체 조회 및 해당 mcis 조회에서 응답시간이 25초 이상 걸리게 됩니다.

**How to reproduce it (as minimally and precisely as possible)**
: 
1. ing, 또는 terminate 관련해서는 요청이 완료될 때까지 control 불가해야 함
2. retry는 생성이나 ing일 때만 수행

**Comment by seokho-son** [comment]
버그리포트 감사합니다. 오류 상황 파악은 완료했고, 현재 refactoring 겸 개선 중에 있습니다.
완료되면 프리릴리스로 공유드리겠습니다.
