### ISSUE TITLE
When using test scripts for MS Azure, is there a test script for creating a ResourceGroup?

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-tumblebug#1400]
cb-tumblebug/src/testclient/scripts에 포함된 스크립트 사용과 관련하여 문의 드립니다.
MS Azure를 대상으로 시험 중인데.. ResourceGroup 등은 사전에 생성해 둬야 하는 것 같은데..
혹시 자동 생성하거나 삭제하는 등의 스크립트가 있을까요?

**Comment by seokho-son** [comment]
https://github.com/cloud-barista/cb-spider/issues/1008 관련 오류에 의해서 자동으로 생성되지 않는 상태이며, spider의 bug fix를 기다리면 될 것 같습니다.

**Comment by seokho-son** [comment]
fix :)
