### ISSUE TITLE
Is it valid that scripts that creating vNet/securityGroup/sshKey/... for all csp regions?

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-tumblebug#1401]
cb-tumblebug/src/testclient/scripts에 각 MCIR별 생성/삭제 등을 수행하는 스크립트가 각각 포함되어 있습니다.
이 중 생성과 삭제 관련 스크립트들을 살펴보면 아래와 같이 모든 CSP Region을 대상으로 반복 수행하는 코드와 단일 Region을 대상으로 수행하는 코드로 구분되어 있습니다.
CallTB를 호출하기 전 MCIRRegionName 등 전달 파라미터가 다른 상황이라 서로 다르게 동작합니다.

cb-tumblebug/src/testclient/scripts/sequentialFullTest와 연계하여 생각해보니..
모든 CSP Region을 대상으로 하는 코드가 sequentialFullTest 하위 스크립트쪽으로 옮겨가서
각 MCIR별 폴더 내 스크립트 내에서는 이제 불필요해 진 것이 아닌가 조심스럽게 예측해보긴 합니다.

https://github.com/cloud-barista/cb-tumblebug/blob/34d63b7bcc45aa549db709611f92bce0d99364f7/src/testclient/scripts/3.vNet/create-vNet.sh#L34-L60

**Comment by seokho-son** [comment]
단위 기능 테스트시에 필요했었습니다. 만 말씀하신 것과 같이, 단위 테스트도 대부분 API (example)로 직접 수행하는 현황이라, 스크립트에서 많이 사용하지 않는 방식인 것으로는 인지하고 있습니다.

**Comment by sykim-etri** [comment]
@seokho-son 
필요시 수정하여 PR 올리도록 하겠습니다~
