### ISSUE TITLE
[testclient/scripts/sequentialFullTest] Call register-cloud.sh and unregister-cloud.sh 

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-tumblebug#1418]
testclient/scripts/sequentialFullTest 내에서 1.configureSpider/register-cloud.sh와 1.configureSpider/unregister-cloud.sh 호출하는 부분이 일부 코멘트 처리가 되어 있고 활용하고 있는 코드도 있습니다.

* 호출 스크립트
  * create-mcis-for-df.sh
  * create-mcis-for-ws.sh

* 호출 코멘트 처리 스크립트
  * clean-mcir-ns-cloud.sh
  * create-mcir-ns-cloud.sh
    * https://github.com/cloud-barista/cb-tumblebug/blob/6d076e1e24fbe3bfdc1441a75da704f7984a20f6/src/testclient/scripts/sequentialFullTest/create-mcir-ns-cloud.sh#L13

스크립트 내 register-cloud.sh나 unregister-cloud.sh가 코멘트 처리된 특별한 이유가 있을지 궁금합니다.

**Comment by seokho-son** [comment]
@sykim-etri 
현재 cb-tb 사용 가이드상, https://github.com/cloud-barista/cb-tumblebug/blob/main/scripts/initMultiCloudEnv.sh 를 먼저 시작하는 것으로 안내하고 있는데, 
해당 스크립트 사용 이후에는 서버에 등록된 정보에 따라 이미 모든 cloud가 등록되어 있는 상태이므로,

스크립트 실행마다 register-cloud.sh 를 unregister-cloud.sh 과정을 반복적으로 수행할 필요가 없어서, disable 해둔 상태인 것 같습니다. ^^
