### ISSUE TITLE
A question about error code

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cb-tumblebug#1447]
(I'm asking this question first because it can affect many areas.)

**How about returning `400 Bad Request` like the following case?**

I encountered the message below when I requested `POST /ns/{nsId}/mcisDynamic`. By the error code 500, it was difficult for me to find it was a request body issue (ref #1446).
```json
{
  "message": "[Error from: http://localhost:1323/tumblebug/ns/ns01/mcisDynamic] Status code: 500 Internal Server Error"
}
```

**Comment by seokho-son** [comment]
Sure, we need to enhance it. Actually, I think it is kind of a bug that I introduced recently.

the misleadings are from https://github.com/cloud-barista/cb-tumblebug/blob/main/src/core/common/client.go#L224
and https://github.com/cloud-barista/cb-tumblebug/blob/main/src/api/rest/server/mcis/provisioning.go#L117 for instance.

Let me touch minimal aspects to fix the matter.

**Comment by seokho-son** [comment]
@yunkon-kim 
Even Though #1451 will fix the major issue here, the PR does not enhance error handling in terms of well classified error codes (for both system and http). Let's revisit again when we are considering about log enhancement.
