### ISSUE TITLE
Are there other options for the GCP VM spec in `gcp-asia-northeast3` ?

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cb-tumblebug#1498]
**Question***
Are there other options for the GCP VM spec in `gcp-asia-northeast3` ?

**What happened**
: When I was trying to create a VM by `POST /ns/{nsId}/mcisDynamic` with the request body below.
```json
{
    "description": "Test infra for VPN tunnel",
    "installMonAgent": "no",
    "label": "DynamicVM",
    "name": "",
    "systemLabel": "",
    "vm": [
        {
            "commonImage": "ubuntu18.04",
            "commonSpec": "aws-ap-northeast-2-t3-small"
        },
        {
            "commonImage": "ubuntu18.04",
            "commonSpec": "az-krc-standard-b1s"
        },
        {
            "commonImage": "ubuntu18.04",
            "commonSpec": "gcp-asia-northeast3-e2-standard-2"
        }
    ]
}
```

: Spider encountered the error below. (CC. @powerkimhub)
```
systemMessage:"[Error from: http://localhost:1024/spider/vm] Status code: 500 Internal Server Error, Message: {\"message\":\"googleapi: Error 400: e2 instances do not support onHostMaintenance=TERMINATE unless they are preemptible., badRequest\"}"
```

**Note**
`commonImage` and `commonSpec` were made by combining the following information:
  - CONN_CONFIG: [assets/cloudconnection.csv](https://github.com/yunkon-kim/cb-tumblebug/blob/main/assets/cloudconnection.csv)
  - Specs: [assets/cloudspec.csv](https://github.com/yunkon-kim/cb-tumblebug/blob/main/assets/cloudspec.csv)
  - Images: [assets/cloudimage.csv](https://github.com/yunkon-kim/cb-tumblebug/blob/main/assets/cloudimage.csv)
  
Versions:
  - CB-Spider v0.8.10
  - CB-Tumblebug 5629f000cce19c47c6e44e4a81a0dc1930375c3c (The version immediately before the latest version)

**Comment by seokho-son** [comment]
https://cloud.google.com/compute/docs/instances/setting-vm-host-options 와  관련이 있겠네요.

**Comment by seokho-son** [comment]
- https://github.com/cloud-barista/cb-spider/issues/1125

**Comment by powerkimhub** [comment]
@yunkon-kim @seokho-son 

<br>

**[현황]**
- GPU 지원 Spec지원을 위한 다음 이슈의 임시 patch 영향으로 보입니다. 
  - https://github.com/cloud-barista/cb-spider/issues/1125
  - patch revoke 후 test시 `e2-standard-2` 정상 동작

**[대안]**
- (1) `e2` 계열외 Spec으로 대체 활용(`n1`, `n21` 계열 등)
- (2) Spider GCP Driver 정식 patch 기다림
- 시험 특성상 (1)이 불가하면, 바로 조치 해보도록 하겠습니다.

**Comment by seokho-son** [comment]
안녕하세요. @powerkimhub 

최근 CB-Spider에 https://github.com/cloud-barista/cb-spider/issues/1125 해결을 위해서 하기 패치가 진행되었습니다.
- https://github.com/cloud-barista/cb-spider/commit/841ec6c60c71f7793233f5eb36f12754c42ae240

해당 패치는 GCP GPU VM 생성을 임시적으로 지원하기 위한 패치이나, 반대로 기존에 동작하던 e2와 같은 스펙이 프로비저닝되지 않는 문제를 야기하는 것 같습니다. Spider 차원에서 대안 마련이 필요해 보입니다.

**Comment by yunkon-kim** [comment]
@seokho-son @powerkimhub 

CB-Tumblebug의 `POST /ns/{nsId}/mcisDynamic`를 활용하는 경우에는 `n1`, `n2` 계열 spec 활용이 어려운 것으로 보입니다. 
* `n1-highcpu-2` 를 활용한 생성 테스트 진행시, `"Failed to get the spec gcp-asia-northeast3-n1-highcpu-2"`
* 위 API는 Tumblebug 차원에서 테스트를 수행한 commonSpec이 활용되기 때문입니다. (아래 테이블 참고)

**Spider에서 진행하시는 패치와 별개로 Tumblebug의 자원 별 APIs를 활용하는 쪽을 고민해보겠습니다.** 

(참고 - [assets/cloudspec.csv](https://github.com/yunkon-kim/cb-tumblebug/blob/main/assets/cloudspec.csv))
providerName | connectionName | cspSpecName | CostPerHour | evaluationScore01 | evaluationScore02 | evaluationScore03 | evaluationScore04 | evaluationScore05 | evaluationScore06 | evaluationScore07 | evaluationScore08 | evaluationScore09 | evaluationScore10 | rootDiskType | rootDiskSize
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
436 | gcp | gcp-asia-northeast3 | g1-small | 0.0311 | 34.18 |   |   |   |   |   |   |   |   |   | default | default
437 | gcp | gcp-asia-northeast3 | e2-standard-2 | 0.085964 | 54.43 |   |   |   |   |   |   |   |   |   | default | default
438 | gcp | gcp-asia-northeast3 | e2-standard-4 | 0.171928 | 54.43 |   |   |   |   |   |   |   |   |   | default | default
439 | gcp | gcp-asia-northeast3 | e2-standard-8 | 0.343856 | 54.43 |   |   |   |   |   |   |   |   |   | default | default
440 | gcp | gcp-asia-northeast3 | e2-standard-16 | 0.687712 | 54.43 |   |   |   |   |   |   |   |   |   | default | default

**Comment by yunkon-kim** [comment]
@seokho-son @powerkimhub 

MapUI에서 지도 클릭을 통해 MCIS를 생성하면서 아래 조합이 가능한 것을 알게 되었습니다. 

현재 진행중인 e2 계열의 이슈가 해소 될때 까지, 당분간 아래 Request Body를 활용하도록 하겠습니다.

Request body of `POST /ns/{nsId}/mcisDynamic`
```json
{
    "description": "Test infra for VPN tunnel",
    "installMonAgent": "no",
    "label": "DynamicVM",
    "name": "mcis-001",
    "systemLabel": "",
    "vm": [
        {
            "commonImage": "ubuntu18.04",
            "commonSpec": "aws-ap-northeast-2-t3-small"
        },
        {
            "commonImage": "ubuntu18.04",
            "commonSpec": "az-krc-standard-b1s"
        },
        {
            "commonImage": "ubuntu18.04",
            "commonSpec": "gcp-asia-northeast3-g1-small"
        }
    ]
}
```
