### ISSUE TITLE
Azure k8s cluster provisioning failure

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#1506]
**What happened**
스크립트 기반 Azure k8s 클러스터 생성 실행시, 오류 발생으로 생성 실패

**How to reproduce it (as minimally and precisely as possible)**
스크립트 기반 Azure k8s 클러스터 생성 진행

**Anything else we need to know?**

### 주요 에러 메시지
- \"message\":\"Failed to Create Cluster. err = Failed Validation Check NodeGroup. err = The Cluster in Azure does not provide Image Designation. Please remove the name of the image and try\"
```
[Waiting for initialization of CLUSTER: (3s)]
Dozing for 3 : 1 ####################################################################
## 13. CLUSTER: Create
####################################################################

====================================================================
CSP=azure
NSID=ns01
INDEX=1
REGION=1
POSTFIX=tb
NAME=ng11
IMAGEID=azure-westus-tb
RootDiskType=default
RootDiskSize=default
DesiredNodeSize=1
MinNodeSize=1
MaxNodeSize=1
VERSION=1.29.0
CLUSTERID=tb111
====================================================================
2 3 (Finish dozing. Back to work)
{
  "message": "[Error from: http://localhost:1024/spider/cluster] Status code: 500 Internal Server Error, Message: {\"message\":\"Failed to Create Cluster. err = Failed Validation Check NodeGroup. err = The Cluster in Azure does not provide Image Designation. Please remove the name of the image and try\"}\n"
}
```

### 주요 에러 메시지 (상기 문제 임시 패치: 소스코드에서 임의로 이미지 명칭 삭제, 이후)

```
{
  "message": "[Error from: http://localhost:1024/spider/cluster] Status code: 500 Internal Server Error, Message: {\"message\":\"Failed to Create Cluster. err = containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code=\\\"AvailabilityZoneNotSupported\\\" Message=\\\"Availability zone is not supported in region westus.\\\" Target=\\\"agentPoolProfile.availabilityZone\\\"\"}\n"
}
```

**Environment**
- Source version or branch: cb-tb latest + cb-sp v0.8.11
- OS: ubuntu

**Proposed solution**
CB-TB 최신 소스 및 cb-sp v0.8.11를 기반으로 각 클러스터 프로비저닝 동작 여부 재확인, 오류 개선

**Comment by seokho-son** [comment]
@sykim-etri 해당 이슈 확인 부탁 드립니다. 스크립트를 기반으로 Azure 실행시 오류가 발생하지 않도록 처리 필요해 보입니다.

**Comment by sykim-etri** [comment]
상기 Azure 실행 오류와 관련하여,
CB-SP 수준에서의 오류 처리를 말씀하시는 걸까요? 혹은 CB-TB 수준에서의 오류 처리를 말씀하시는 걸까요?

**Comment by seokho-son** [comment]
@sykim-etri 
(현재 가이드대로 진행하면 오류가 발생하는 상황이므로) CB-TB 수준에서의 오류 처리 요청입니다만, 
CB-SP를 통해 먼저 해결해야 하는 사항이라면 미리 알려주시면 좋을 것 같습니다.

**Comment by sykim-etri** [comment]
@seokho-son 
오류 내용상으로는 CB-SP의 Azure Cluster 드라이버 수정이 필요한 사항으로 보입니다.
Azure Cluster 드라이버 개발을 이노그리드에서 진행해 왔기 때문에 오류 처리에 시간이 다소 소요될 것으로 예상됩니다.

cc: @powerkimhub

**Comment by seokho-son** [comment]
- will be fixed by : #1538
