### ISSUE TITLE
[NCP, NCPVPC, NHNCLOUD, KTCLOUD, KTVPC] request for region, zone list and Spec/image test set information

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#1529]
@innodreamer 

각 국내 CSP에 대해서 region, zone list 와 테스트용 Spec/image 세트 정보 공유 요청 드립니다.

업스트림에 Credential 및 ConnectionConfig 관련하여, 신규 활용 방식이 도입되어서, 
정상 동작 여부를 테스트하고자 합니다.

업데이트 예정 파일
- https://github.com/cloud-barista/cb-tumblebug/blob/main/assets/cloudinfo.yaml
- https://github.com/cloud-barista/cb-tumblebug/blob/main/assets/cloudimage.csv
- https://github.com/cloud-barista/cb-tumblebug/blob/main/assets/cloudspec.csv

아래와 같은 포멧으로 알려주시면 감사하겠습니다.

### 1 (예시)
region: `kr1`
zone: `68fb7e1a-191c-45bf-8328-b7864f9fbaf4`
spec: `m2.c4m8`
image: `68fb7e1a-191c-45bf-8328-b7864f9fbaf4` , `Ubuntu 22.04`

### 2
region: 
zone: 
spec: 
image: 
...

**Comment by seokho-son** [comment]
@innodreamer 혹시 대략 공유 시점 알려주실 수 있으실까요? 상기 정보는 완벽할 필요는 없고, 1개의 set 만이라도 조금씩 추가해주시면 좋을 것 같습니다.

**Comment by seokho-son** [comment]
@innodreamer 진행 현황 문의드립니다.

**Comment by innodreamer** [comment]
@innodreamer 상기 PR 확인 후 반영 부탁드립니다.
