### ISSUE TITLE
Check Docker image works for CB-TB v0.8.8 and latest main

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#1540]
**What would you like to be enhanced**
- v0.8.8 릴리스 이후부터 신규 credential 입력 방법 및 클라우드 정보 입력 방법이 도입됨.
- Docker 이미지도로 정상 구동 및 credential 등록에 문제가 없는지 확인 필요. (오류 발생시 Dockerfile 개선 필요)

**Comment by seokho-son** [comment]
@yunkon-kim 
May I get a contribution from you ? :)

**Comment by yunkon-kim** [comment]
@seokho-son

Of course. I will handle this issue ^^
