### ISSUE TITLE
In the case of CSPs where region/zone names are written in uppercase letters, an error occurs because the cloud resource name or connection name includes uppercase letters..

### ISSUE THREAD

**Issue by innodreamer** [cloud-barista/cb-tumblebug#1593]
**What happened**
: 최근 update된 CB-TB는 모든 CSP region/zone 정보를 통합 관리하고, CB-TB test script로 자원을 생성하거나 Map-UI로 자원을 생성할때, 그리고 connection config 이름을 지정할때 그 region/zone 정보를 기준으로 자동으로 이름이 지정되어 자원을 생성함.
하지만, 국내 CSP 중 region/zone 이름이 영어 대문자로 표기되어야하는 CSP가 있으며, 그러한 경우 자원 이름에 대문자가 포함되거나 connection config 에 대문자가 포함되는데, 그런 경우 자원 이름에 대문자가 포함되면 자원 생성시 혹은 자원 정보 조회시 오류가 발생하고, connection config 에 대문자가 포함되어도 오류가 발생함.

**What you expected to happen**
: CB-TB server에서 자원 이름 지정시와 connection config 이름 지정시 대문자가 포함된 이름 string을 전체적으로 소문자로 변경하여 지정되게하고, 자원 정보나 connection 정보 조회시에도 자원 이름이 필요한 경우도 소문자 이름 기준으로 조회되도록 보완되어야함.

**How to reproduce it (as minimally and precisely as possible)**
: 

**Anything else we need to know?**
: 

**Environment**
- Source version or branch: 
- OS: 
- Others: 

**Proposed solution**
: 

**Any other context**
:

**Comment by seokho-son** [comment]
대응 방향
- 리소스 ID (요청 name)에 대문자를 허용하도록 규칙을 수정하겠습니다. (국내 CSP 구동 및 현 Test 스크립트 기반 실행 지원 차원)
- 요청하신 내용과는 다르게, 임의로 사용자가 지정한 리소스 명칭을 소문자로 수정하지는 않도록 하겠습니다. 단, 사용자가 요청한 값이므로, 향후 case를 확인하고 사용해야 합니다.

**Comment by seokho-son** [comment]
fixed by https://github.com/cloud-barista/cb-tumblebug/pull/1598

@innodreamer 최신 버전으로 리전명이 대문자인 국내 CSP 테스트 진행해주시면 되겠습니다.
