### ISSUE TITLE
Need a guideline for Localization and Globalization of CB-Tumblebug

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#161]
We don't have a guideline for Localization and Globalization of CB-Tumblebug.

I would like to suggest the following guideline.

---------------------------

Localization and Globalization of CB-Tumblebug.

As an opensource project initiated by Korean members, we would like to promote participation of Korean contributors during initial stage of this project. So, CB-Tumblebug Repo will accept use of Korean language in its early stages.

On the other hand, we hope this project flourishes regardless of contributor's country eventually.
So, the maintainers recommend using English at least for the title of Issues, Pull Requests, and Commits, while CB-Tumblebug Repo accommodates local languages in the contents of them.

---------------------------
CB-Tumblebug의 현지화 및 세계화

한국인이 시작한 오픈 소스 프로젝트로서이 프로젝트의 초기 단계에 한국 기여자들의 참여를 촉진하고자합니다. 따라서 초기 단계의 CB-Tumblebug 저장소는 한국어 사용을 받아 들일 것입니다.

다른 한편으로, 우리는이 프로젝트가 기여자의 국가에 관계없이 번성하기를 희망합니다.
따라서 최소한 이슈, 풀 요청, 커밋에 대해서는 제목을 영어로 사용하는 것을 추천하며, 내용에는 현지 언어 사용을 수용할 것입니다.

**Comment by seokho-son** [comment]
CF to @powerkimhub

**Comment by seokho-son** [comment]
CF to @dongjae 
This guideline might be applicable to all Cloud-Barista Repositories.

**Comment by seokho-son** [comment]
@jihoon-seo 
Are you agree with this guideline ?

**Comment by jihoon-seo** [comment]
@seokho-son Sure!!

**Comment by seokho-son** [comment]
This guideline has been confirmed by Cloud-Barista steering meeting !

**Comment by seokho-son** [comment]
Resolved by https://github.com/cloud-barista/cb-tumblebug/commit/d8be7cf7c7ae11d6a6b8ba58a91abc79625a6488
