### ISSUE TITLE
Need to determine a database(s) for Spec and Image objects

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#165]
@seokho-son 
현재, Spec 에 대해서는 MySQL 도입이 확정되었습니다.
검색 등의 기능을 고려하면 Image 도 같은 상황 같습니다.

위의 사항을 고려할 때
- 1안: MySQL + K-V store 동시 저장
consistency (정합성) 이슈, 불일치 시 롤백 이슈.. 등이 있을 수 있습니다.
각 이슈/상황에 대한 로직을 넣어 해결할 수 있겠습니다.
- 2안: K-V store 사용하지 않고 MySQL 만 사용
이럴 경우, 다른 MCIR, MCIS, NS 등이 K-V store 를 사용하는 것과 배치/상충됩니다.
- 3안: 모든 MCIR, MCIS, NS 에 대해 K-V store 대신 MySQL 사용하는 것으로 전환
(이 안으로 선택될 확률은 낮을 것 같습니다.)

1안과 2안, 또는 다른 새로운 안에 대해 고민이 필요할 것 같습니다.

**Comment by seokho-son** [comment]
@jihoon-seo 
우선 저는 1안을 선호 합니다. 
다만 아직 많은 량의 이미지를 조회하는 상황이 아니라서, 시급성은 조금 떨어질 것 같습니다.
이미지 오브젝트에 대해서는 기본적인 처리(기 오픈된 PR #166 수준) 진행하면 어떨까합니다.
