### ISSUE TITLE
When registering a spec by swagger, it requires registeringMethod

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-tumblebug#1654]
PostSpec API 호출시 registeringMethod 항목이 필수 입력으로 되어 있는데, specName으로 등록하려는 경우 어떤 값을 설정해야 할지 설명이 부족한 상태로 보입니다.
필수 항목이라 특정 값을 입력해야 할 것 같은데.. 한칸(" ")으로 입력시 동작하기는 했습니다.

![image](https://github.com/cloud-barista/cb-tumblebug/assets/25163268/3fa3fd56-d9a1-4fde-8cfb-170455dc3ad6)

**Comment by seokho-son** [comment]
@sykim-etri 개선 의견 감사합니다.

https://github.com/cloud-barista/cb-tumblebug/pull/1657#issuecomment-2191006082

와 같이, 선택 가능하게 옵션을 제공하였습니다.
다만, mcir 쪽 api 및 문서 개선은 추가적으로 필요할 것 같습니다. 급한대로 https://github.com/cloud-barista/cb-tumblebug/pull/1657 로 대응하고자 합니다.
