### ISSUE TITLE
How to create a subnet in a specific zone

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-tumblebug#1672]
AWS EKS의 경우 K8s 클러스터 생성시 서로 다른 존(AZ)에 위치한 두 개 이상의 Subnet 설정을 요구하고 있습니다.
이를 위해 임의의 Zone에 Subnet 생성이 필요한데, API 상 아직 지원하지 않는 것 같아 보이기도 합니다. CB-SP 수준에서는 지원하는 것처럼 보이기도 한데, 혹시 방법이 있다면 안내를 부탁드립니다.

**Comment by yunkon-kim** [comment]
@sykim-etri (cc. @seokho-son)

현황을 공유드립니다. "Zone을 지정하여 Subnet을 생성"하기 위해서 개선이 필요한 상황입니다.

빠르게 살펴본 바로는 아래와 같이 개선을 진행하면 하면 될 것 같습니다.
1. 네트워크 자원 관련 기능 및 API 검토
2. MCIR vNet, Subnet 기능 및 API 개선: 업데이트된 CB-Spider API 반영
3. MCIS 네트워크 구성 기능 (및 API) 추가: 여러 VPC 및 Subnet의 CIDR block이 겹치지 않도록 네트워크 구축
4. MCIS provisioning 기능 및 API 개선:  K8s 인프라에 우선적으로 적용되어야 할 것으로 판단됩니다.
(+ 테스트 및 디버깅)

추진 시기는 별도로 공유드릴 예정이오며, 필요시 Draft PR을 올리도록 하겠습니다.

--- 

(참고 - 관련 일정)
* K8s 인프라 배포 완료 시기 ~10월
* CB-Spider의 테스트 완료 시기: 미정
* Connection Config 관련 개선: 미정/예정

(참고 - CB-Spider에서 공유해주신 현황)

[적용 대상 자원 및 API 변경 개요]
* 대상 자원: Subnet, VM, Disk (Subnet-VM-Disk 연계 필요시: 같은 Zone으로 구성해야 함)
* 제공 CSP: AWS, 타 CSP 검증 중
* https://github.com/cloud-barista/cb-spider/issues/1067#issuecomment-2022605540
 
[Rest API Guide 관련]
* 현재 미제공(대신 아래 AdminWeb 방법 임시 참고)

[AdminWeb 기반 Test 가이드]
* AdminWeb 실행 후 하단 Log청에서 curl 명령 참고 가능
* https://github.com/cloud-barista/cb-spider/issues/1067#issuecomment-2032196281

**Comment by sykim-etri** [comment]
상기 기능 제약 및 변경 예정 항목들로 인해 K8sCluster 통합 시험/보완 일정을 일부 변경하여 진행할 예정입니다.
(cc: @powerkimhub)

* 기존: AWS, GCP, Azure 순
* 신규: Azure(최근 업데이트), GCP, AWS 순

**Comment by yunkon-kim** [comment]
@sykim-etri 

#1720 이 반영되면 Subnet 생성 시 Zone을 지정할 수 있습니다. 참고하시기 바랍니다 :-)
