### ISSUE TITLE
Fatal error reading jwt_auth info from file when AUTH_MODE is basic

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-tumblebug#1674]
`conf/setup.env` 내 AUTH_ENABLED=true, AUTH-MODE=basic인 상태에서 jwt_auth 파일이 없어 에러가 발생합니다. AUTH_MODE가 jwt 인 경우 해당 파일을 읽어야 할 것 같습니다.
더불어 .gitignore 때문인지 template-jwt-auth.yaml(?)도 보이지 않습니다.

```
4:30PM ERR main.go:211 > fatal error reading jwt_auth info from file: %!w(viper.ConfigFileNotFoundError={jwt_auth [/home/sykim/workspace/cb-tumblebug/src /home/sykim/workspace/cb-tumblebug/
src/conf /home/sykim/workspace/cb-tumblebug/conf]}) error="Config File \"jwt_auth\" Not Found in \"[/home/sykim/workspace/cb-tumblebug/src /home/sykim/workspace/cb-tumblebug/src/conf /home/
sykim/workspace/cb-tumblebug/conf]\""

```

https://github.com/cloud-barista/cb-tumblebug/blob/c1d8afa99aa2110f6e7ebbf3686e3b36a53b13b2/src/main.go#L207-L213

* Commit: c1d8afa99aa2110f6e7ebbf3686e3b36a53b13b2

**Comment by yunkon-kim** [comment]
빠르게 살펴보겠습니다!
