### ISSUE TITLE
Need to check Dockerfile, DockerCompose, CI, CD from its experts

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#1739]
최근 docker의 buildx 툴킷을 활용하여, 빌드 속도 향상과 여러 측면에서의
Dockerfile, DockerCompose, CI, CD 개선이 진행되었음.

- https://github.com/cloud-barista/cb-tumblebug/pull/1732
- https://github.com/cloud-barista/cb-tumblebug/pull/1733 https://github.com/cloud-barista/cb-tumblebug/pull/1734

결과적으로 빌드 성능이 상당히 개선된 것으로 보이며, 
오류 등의 특이사항도 없는 것으로 보임.

그러나, PR 리뷰 절차가 진행되지 않았으므로, 
전문가이신 ~ @yunkon-kim 님의 추가 확인을 거치고자 함.

**Comment by yunkon-kim** [comment]
@seokho-son 올려주신 PR을 보니 컨테이너 이미지 빌드 시간이 대폭 개선된 것 같습니다 :-)

빠르게 살펴보면서 파악한 의견을 남겨드립니다. 상황에 맞게 반영하시거나, 이슈 발생 시 대응해주시면 될 것 같습니다.

1. 상대 경로로 인한 이슈 (기여자별 환경 상이)

https://github.com/cloud-barista/cb-tumblebug/blob/da7bbfeba15339f6431367f0d5e5bd738034cf95/Dockerfile#L13-L16

https://github.com/cloud-barista/cb-tumblebug/blob/da7bbfeba15339f6431367f0d5e5bd738034cf95/Dockerfile#L25-L27

https://github.com/cloud-barista/cb-tumblebug/blob/da7bbfeba15339f6431367f0d5e5bd738034cf95/docker-compose.yaml#L145-L150

2. CI, CD 워크플로우 관련 확인 필요

캐시 적용 및 컨테이너 이미지 빌드를 위해서는 CI와 CD 워크플로우 간에 일관성을 맞출 필요가 있어 보입니다.

그 동안, `docker/setup-buildx-action`에도 변화가 있었던 것 같고요. 캐시와 관련하여 동작이 되고 있으나, 아래 컴포넌트들이 쓰임새에 맞게 적용되고 있는지에 대한 의문점이 있습니다.

export cache에 대해서 다음과 같이 안내되고 있으나, 
> By default, the docker-container driver will be used to be able to build multi-platform images and export cache using a BuildKit container. - https://github.com/docker/setup-buildx-action?tab=readme-ov-file#about 

`moby/buildkit`에서는 현재 GitHub Actions cache가 experimental 상태 입니다.
> GitHub Actions cache (experimental) https://github.com/moby/buildkit?tab=readme-ov-file#github-actions-cache-experimental

buildkit과 `actions/cache@v4`간에도 캐시하는 대상의 차이가 있어 보입니다. 자세한 사항은 추가로 분석 후, 개선하는 쪽이 좋을 것 같습니다.

**Comment by seokho-son** [comment]
@yunkon-kim 감사합니다! 항목별로 답변이 있어서, 답변에 기존 코멘트를 수정활용하였습니다.

**Comment by yunkon-kim** [comment]
@seokho-son 마찬가지로 수정을 통해 답글 남겨놓았습니다 ^^

**Comment by seokho-son** [comment]
> A from @yunkon-kim:
> 기여자가 compose를 수정 및 활용하는 것은 가급적 피하고자 하셨던것 같아 코멘트 남겨본 사항입니다. 앞으로는 기여자의 수정 및 활용도 고려하면 되겠죠?

네넵! 일단 저만해도 개발을 위해 build할때는 cb-tumblebug/docker-compose.yaml 를 주로 활용하게 되네요 ^^;;
git ignore가 우리가 원하는 형태로 잘 컨트롤되면 좋을텐데 좀 아쉽습니다.

docker-compose-custom.yaml (.env 활용) 도 향후에 유용하게 될 것 같은데, 일단, docker-compose.yaml 를 중심적으로 정형화(개선 등)을 해보고, 안정화되면 docker-compose-custom.yaml 의 개선도 고려해보면 좋을 것 같습니다.
