### ISSUE TITLE
Fix code scanning alert - Flask app is run in debug mode

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#1741]
Tracking issue for:
- [ ] https://github.com/cloud-barista/cb-tumblebug/security/code-scanning/493

@yunkon-kim may I change it?

```diff
-app.run(host="0.0.0.0", port=5000, debug=True)
+app.run(host="0.0.0.0", port=5000, debug=False)
```

**Comment by yunkon-kim** [comment]
@seokho-son Yes, you could change it to `debug=False` or read it from the env.

**Comment by seokho-son** [comment]
Let's simply set debug=False :)
