### ISSUE TITLE
Remove MCIR term

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#1764]
코드 내부에서 기존 MCIR 용어의 사용은, 명확성 및 적합성이 낮은 측면이 있음. (MCIS는 MCI (MC-Infra)로 변경이 완료됨)

사람들이 직관적으로 파악하기 어려운 새로운 용어를 제시하기 보다는, 플랫한 용어를 채용하여

코드 리더빌리티를 향상 시킬 필요가 있음.

% 주의 사항: pkg 명칭이 변경되며, 수정 파일의 범위가 광범위할 예정. (통합을 위한 1차 프리릴리스 09/02 이전에 정리할 예정)

**Comment by seokho-son** [comment]
FYI: @yunkon-kim @sykim-etri

**Comment by yunkon-kim** [comment]
@seokho-son 

다음주부터 진행 예정인 네트워크 Feature 개선에 영향이 있어 문의를 드립니다.

pkg 명칭을 `mcir`에서 `xxx`으로 변경하는 정도일까요? 각 자원별 pkg화 `vnet` / `network`를 고려하고 계시는 것일까요?

**Comment by seokho-son** [comment]
@yunkon-kim 

일단은 영향 최소화를 위해서, pkg 명칭을 mcir에서 xxx으로 변경하는 정도를 고려한게 맞습니다.

혹시 이번에, 각 자원별 pkg화 vnet / network 를 진행하는 것이 좋을까요?

**Comment by seokho-son** [comment]
현재 cb-tb에서는 pkg 모듈화가 잘 되어 있지 않아서, 아마 수정 범위가 더 커질 가능성이 있긴할 것 같습니다. 
코드 개선 측면에서는 pkg 모듈화도 함께 진행하면 좋긴 합니다. ^^

**Comment by yunkon-kim** [comment]
@seokho-son 

기존에 계획하시던 방향으로 진행하시면 될 것 같고요.

pkg 모듈화에 대해서는 변경 가능한 쪽으로 자유도가 생긴 것으로 이해했습니다. 네트워크 Feature 진행하면서 가볍게 살펴보겠습니다.
