### ISSUE TITLE
Request for Additional Features in /region API

### ISSUE THREAD

**Issue by SungWoongz** [cloud-barista/cb-tumblebug#1786]
@seokho-son 
- 안녕하세요
- 현재 region 전체 목록을 조회하는 api는 있지만
- csp별로 필터하는 기능이 추가로 제공 가능하신지 여쭙고 싶습니다.

- API 링크 : [swagger](https://cloud-barista.github.io/cb-tumblebug-api-web/?url=https://raw.githubusercontent.com/cloud-barista/cb-tumblebug/main/src/api/rest/docs/swagger.yaml#/%5BAdmin%5D%20Multi-Cloud%20Information/GetRegionList)

**Comment by seokho-son** [comment]
@SungWoongz 아래 api를 사용하시면 csp별 구분이 가능합니다. :)

https://cloud-barista.github.io/cb-tumblebug-api-web/?url=https://raw.githubusercontent.com/cloud-barista/cb-tumblebug/main/src/api/rest/docs/swagger.yaml#/%5BAdmin%5D%20Multi-Cloud%20Information/GetCloudInfo

단, 크리덴셜이 연동 및 검증되어 실제 csp에 호출이 가능한 csp 및 리전(존)인지 확인하려면,

https://cloud-barista.github.io/cb-tumblebug-api-web/?url=https://raw.githubusercontent.com/cloud-barista/cb-tumblebug/main/src/api/rest/docs/swagger.yaml#/%5BAdmin%5D%20Credential%20Management/GetConnConfigList

로 확인해보시는 것이 좋고요.

**Comment by SungWoongz** [comment]
@seokho-son 
답변 감사합니다.
response에 CSP별로 정렬되어 나오는 api들은 확인했습니다.
여쭙고자 하는 것은 csp를 필터조건으로 해당 csp의 리전들만 검색할 수 있는 기능이 제공 가능한지 입니다.

**Comment by seokho-son** [comment]
@SungWoongz 
API를 수정해서 지원하도록 하겠습니다. :)
수정 후에 공유 드릴게요.

**Comment by SungWoongz** [comment]
@seokho-son 
감사합니다 !

**Comment by seokho-son** [comment]
@SungWoongz `csp를 필터조건으로 해당 csp의 리전들만 검색` 하는 api를 추가하였습니다. 
- #1791

Connection 개념은 내부적으로 복잡함을 유발하고 있는 상황이라, 앞으로 API 사용자에게는 노출하지 않는 방향으로 진행할 예정입니다. (현재 API의 요청 body에 connectionName이 들어가는 경우가 전부 변경될 것으로 생각하시면 됩니다.) 
앞으로 CB-TB 사용자에게는 무관한 개념이 될 예정이므로, 의존도를 미리 줄이기 위해서, 해당 개념과 관련된 API 편의 개선은 추가로 진행하지 않고자 합니다. :)
