### ISSUE TITLE
In /ns/{nsId}/resources/spec, the parameter 'specName' name is confusing because it can be mistaken for 'cspResourceId'

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-tumblebug#1804]
https://github.com/cloud-barista/cb-tumblebug/blob/6f281e19ed7d2cfe087187a966896588cfea0680/src/api/rest/server/resource/spec.go#L40

swagger 문서에 specName으로 되어 있는데, 내부 필드에 cspResouceId를 입력받도록 되어 있습니다.
다른 API에 cspResourceName도 있어서 보다 명확히 할 필요가 있습니다.

@seokho-son

**Comment by seokho-son** [comment]
@sykim-etri 몇군데 누락한 곳들이 있네요. 감사합니다. 조금 더 고민해서 개선 PR을 올리도록 하겠습니다.

**Comment by seokho-son** [comment]
@sykim-etri #1805 를 통해서 추가 정비하였습니다. 괜찮으신지 한번 살펴봐주세요.. ^^

**Comment by seokho-son** [comment]
@sykim-etri 이대로 정리하면 될까요? ^^ (정리되는 경우, 프리릴리스를 추가로 찍을 예정입니다.)
