### ISSUE TITLE
How do we handle to delete a VNet when subnets are missing?

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-tumblebug#1808]
https://github.com/cloud-barista/cb-tumblebug/blob/525924c2a31ebfb770d830b88cf3ed5193b208ba/src/core/resource/vnet.go#L708-L712

VNet 삭제시 withSubnets 파라미터를 통해서 Subnet들도 함께 삭제하는 옵션이 존재합니다.
사용자(콘솔에서 삭제 등) 또는 다른 이유로 Subnet이 사라지거나 삭제시 에러가 발생하는 경우 VNet을 삭제하지 못하는 이슈가 있습니다.

**Comment by yunkon-kim** [comment]
@sykim-etri 

말씀해주신 내용을 이해해보자면, 
사용자가 Tumblebug을 활용하지 않고 Subnet을 삭제한 경우 이를 대응할 방안이 필요한 것으로 파악됩니다.

이는 예외적인/비정상적인 케이스로 보입니다. 관련하여 방안을 마련해보겠습니다.

**Comment by yunkon-kim** [comment]
@sykim-etri (cc. @seokho-son)

위 케이스는 2가지로 나누어 볼 수 있을 것 같습니다.

1. Spider에서 metadata가 삭제되고, CSP에 리소스가 남아 있는 경우
2. Spider에 metadata가 있으나, CSP에서 리소스가 삭제된 경우

가장 직관적인 방법은 강제로 삭제하는 방법일 것 같습니다.

관련하여 Spider API를 확인해보니, subnet을 강제 삭제하는 옵션이 없는 상태입니다.
: https://cloud-barista.github.io/api/?url=https://raw.githubusercontent.com/cloud-barista/cb-spider/master/api/swagger.yaml#/%5BVPC%20Management%5D/remove-subnet

@powerkimhub 관련하여 다음 사항에 대해 Spider에서 가능하신 부분들을 공유하여 주시기 바랍니다.
: 개별 subnet을 강제로 삭제하는 option을 추가해 주실 수 있는지 문의 드립니다.

: (살짝 별도의 사안이기도 한데요.) 확신한 제어를 위해 개별 Subnet의 정보를 조회할 수 있는 API도 필요해 보입니다. 현재는, VPC 정보를 조회 후, Looping을 통해 해당 subnet을 조회하는 상황입니다.

**Comment by powerkimhub** [comment]
[Sync Error]
- 현황을 제공하는 다음 API 참고하세요. 
- [/allvpc](https://cloud-barista.github.io/api/?url=https://raw.githubusercontent.com/cloud-barista/cb-spider/master/api/swagger.yaml#/%5BVPC%20Management%5D/list-all-vpc)

<br>

[Subnet force option]
- 다음 API에서 실제 옵션을 제공하는데, Swagger 정의에서 실수로 빠져 있네요. 
- 반영 후 공유 드리지요.
  - [/vpc/{VPCName}/subnet/{SubnetName}](https://cloud-barista.github.io/api/?url=https://raw.githubusercontent.com/cloud-barista/cb-spider/master/api/swagger.yaml#/%5BVPC%20Management%5D/remove-subnet)


<br>

[개별 Subnet 정보 조회]
- 대략, 다음 형식의 API 추가 해드리겠습니다.
  - Method: GET
  - input: ConnectionName, VPCName, SubnetName
  - output: SubnetInfo

**Comment by powerkimhub** [comment]
@yunkon-kim (cc. @sykim-etri @seokho-son)

<br>

- 반영 버전이 다음과 같습니다.
  - https://github.com/cloud-barista/cb-spider/commit/c1f4920370f57640e7a902ed3b7058aa0d4bc41e
  - docker pull cloudbaristaorg/cb-spider:edge

<br>

- 추가된 API
  - [/vpc/{VPCName}/subnet/{SubnetName}](https://cloud-barista.github.io/api/?url=https://raw.githubusercontent.com/cloud-barista/cb-spider/master/api/swagger.yaml#/%5BVPC%20Management%5D/get-subnet)

<br>

- Pre-release 필요한가요?

**Comment by yunkon-kim** [comment]
@powerkimhub 

Spider에서 원래 계획하시던 일정에 Pre-release 찍어주셔도 괜찮을 것 같습니다.

**Comment by yunkon-kim** [comment]
Resolved by #1814
: Supported the `refine` option to remove missing subnet objects due to exceptional/abnormal case

Reopen this issue if needed :-)
