### ISSUE TITLE
Is there recommended regions for each CSP?

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-tumblebug#1818]
현재 GCP에서 제공하는 리전은 총 40개로 보입니다. 

https://github.com/cloud-barista/cb-tumblebug/blob/a0bc69f75ca46f508376025dc7c9eb0a822b5317/assets/cloudinfo.yaml#L1112-L1117

예전 테스트 스크립트에 보니 25개 중 22개 정도가 추천되어 있는데.. assets 형태로도 recommeded 항목을 관리하고 있는지요?
https://github.com/cloud-barista/cb-tumblebug/blob/a0bc69f75ca46f508376025dc7c9eb0a822b5317/src/testclient/scripts/testSet.env#L126-L156

**Comment by seokho-son** [comment]
@sykim-etri [cb-tumblebug/src/testclient/scripts/testSet.env](https://github.com/cloud-barista/cb-tumblebug/blob/a0bc69f75ca46f508376025dc7c9eb0a822b5317/src/testclient/scripts/testSet.env#L126-L156) 에 있는 리전 리스트는 이제 outdated 상태입니다. 기존에 recommend를 지정한 이유는, Cloud-Barista에서 구동할 수 없는 제약이 있었기에, 작성해둔 내용입니다. 아마도 해당 사항도 이미 outdated 되어 있을 것입니다.

## assets 측면
[cb-tumblebug/assets/cloudinfo.yaml](https://github.com/cloud-barista/cb-tumblebug/blob/a0bc69f75ca46f508376025dc7c9eb0a822b5317/assets/cloudinfo.yaml#L1112-L1117) 에는 알려진 region 리스트를 전부 다 포함하는 것을 가정하고 있습니다. (도구 등을 통해 반자동으로 작성)

내부에 따로 recommend 등을 표기하고 있지는 않습니다. 

다만 유사하게 동작하는 부분은, credential 등록시 시스템 내부적으로 모든 region/zone에 해당하는 connections를 자동으로 만들어 내고, 이 connections가 실제로 동작하는지 validation을 진행하고 표기하고 있으므로, 기존 스크립트에서 Recommend에 해당하던 region들이, 이 validation을 통해 가용 region이 자동으로 정리되어 있다고 생각하셔도 괜찮을 것 같습니다.

GET [/connConfig](https://cloud-barista.github.io/api/?url=https://converter.swagger.io/api/convert?url=https://raw.githubusercontent.com/cloud-barista/cb-tumblebug/main/src/api/rest/docs/swagger.json#/[Admin]%20Credential%20Management/GetConnConfigList) 에서 옵션을 filterVerified=true 로 주시면 validation된 항목만 표기됩니다.

이외에 추가적인 (추천에 해당하는) 기능이 필요하신 상태이신지요?

**Comment by sykim-etri** [comment]
K8sCluster 대상으로 각 CSP의 리전별 현황 파악을 위한 문의라서 추가적으로 필요한 기능이 있는 것은 아닙니다.^^
