### ISSUE TITLE
How to access swagger-ui from no localhost?

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-tumblebug#1834]
[추천된 CB-TB 실행 방법](https://github.com/cloud-barista/cb-tumblebug?tab=readme-ov-file#2-1-option-1-run-cb-tumblebug-with-docker-compose-recommended)으로 CB-TB를 실행했습니다.
swagger-ui도 실행되는 것으로 확인되어 외부 브라우저에서 접근을 시도하였으나 페이지 접근이 되지 않는 것으로 보입니다.
localhost에서 curl로는 데이터가 출력되는데, 혹시 외부 브라우저에서 접근할 수 있는 방법이 있을까요?

CB-TB v0.9.12
CB-SP v0.9.3

**Comment by seokho-son** [comment]
@sykim-etri CORS 때문에 아마 접속되지 않으실 것 같습니다. 여러가지 방법이 있긴한데..

혹시 map-ui에 포함된 swagger ui는 접속 되시나요?

**Comment by sykim-etri** [comment]
@seokho-son map-ui의 내부 소스코드에 localhost로 고정되어 있어서 접속은 불가하네요.
혹시 localhost를 해당 VM의 IP주소로 바꾸려면 어떻게 하면 될까요?

**Comment by seokho-son** [comment]
아마

https://github.com/cloud-barista/cb-tumblebug/blob/main/conf%2Fsetup.env#L17-L17

에 host ip를 지정해서 구동해보시면 될 것 같습니다. 해당 상황에서 쓰기 위해서 예전에 만들었었습니다. 최근 테스트 해보진 않았네요. (컨테이너로 구동하는 경우에도 해당 환경변수가 함께 넘어가야함)

**Comment by powerkimhub** [comment]
@sykim-etri (@seokho-son)

<br>

- 다음 Port Forwarding 방법도 참고해보세요. 
- [Swagger UI에서 Remote Spider 서버 활용 가이드](https://github.com/cloud-barista/cb-spider/wiki/Swagger-Guide#-%EC%B0%B8%EA%B3%A0-swagger-ui%EC%97%90%EC%84%9C-remote-spider-%EC%84%9C%EB%B2%84-%ED%99%9C%EC%9A%A9-%EA%B0%80%EC%9D%B4%EB%93%9C)

**Comment by seokho-son** [comment]
@sykim-etri 혹시 해결 되셨나요~? 
사용 방식에 대한 사항이므로, 특별히 문제가 없으시다면 close 하려고 합니다.

**Comment by sykim-etri** [comment]
TB_SELF_ENDPOINT 설정으로 동작하지 않았습니다.
조금 살펴보니 코드 상에 반영이 되지 않은 상황인 것으로 보입니다.
https://github.com/cloud-barista/cb-tumblebug/blob/07e7c75964f23c6e507523ae5d3099f160102507/src/api/rest/server/server.go#L520-L521

**Comment by seokho-son** [comment]
제가 개선을 좀 해두도록 하겠습니다. :)

**Comment by seokho-son** [comment]
@sykim-etri 

Swagger Dashboard가 완전 동적으로 endpoint를 지정하는 방법에 다소 제약이 있습니다만..

일단 활용하시는데는 어려움이 없도록 정리해두었습니다. 

그래도 외부에서 접속해서 사용하시기 보다는 가급적 localhost를 이용하시기 바랍니다. ^^ (백엔드 서버에서 swagger dashboard 자체를 서빙하는 것이 별로 바람직하지 않습니다. 현재는 개발 편의용으로 제공하는 것으로 이해해 주세요.)

**Comment by seokho-son** [comment]
https://github.com/cloud-barista/cb-tumblebug/blob/main/docker-compose.yaml#L33 만 외부 접속 주소로 변경해주시면 됩니다.
