### ISSUE TITLE
Remove deprecated gRPC related comments

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#1845]
**What would you like to be enhanced**
- Code clean up for deprecated comments

**Why is this needed**
- To improve code readability and reduce the source file size.

**Proposed solution**
- Remove gPRC server related comments around https://github.com/cloud-barista/cb-tumblebug/blob/v0.9.14/src/main.go#L467C5-L467C33

---

**Additional note**
- This is for a new contributor!

**Comment by ShehzadAhm** [comment]
Hi @seokho-son, can you assign it to me?
