### ISSUE TITLE
Remove the misleading comment

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#1846]
**What would you like to be enhanced**
- Code clean up by correcting misleading comment

**Why is this needed**
- To improve code readability.

**Proposed solution**
- Refind the comment `// A context for graceful shutdown (It is based on the signal package)selfEndpoint := os.Getenv("TB_SELF_ENDPOINT")`
  - `selfEndpoint := os.Getenv("TB_SELF_ENDPOINT")` should be removed
  - ref: https://github.com/cloud-barista/cb-tumblebug/blob/v0.9.14/src/api/rest/server/server.go#L544

---

**Additional note**
- This is for a new contributor!

**Comment by tharun634** [comment]
Hey! I'd like to work on this
