### ISSUE TITLE
Integrate CB-SP v0.9.6 into CB-TB and conduct testing

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#1851]
**What would you like to be added**

Integrate CB-SP v0.9.6 into CB-TB and conduct testing

- [x] Basic functionalities (assignee: @seokho-son)
- [x] Network features (assignee: @yunkon-kim)
- [x] Kubernetes cluster features (assignee: @sykim-etri)

Works should be conducted in parallel. (parallel PRs)
After this issue, a new CB-TB pre-release will be published!

**Comment by seokho-son** [comment]
PTAL @yunkon-kim @sykim-etri

**Comment by seokho-son** [comment]
별도의 dev 브랜치들을 생성하지 않을 예정이므로, 피쳐가 다른 PR간 상호 rebase가 필요할 수 있습니다. :) 
참고하시기 바랍니다.

**Comment by sykim-etri** [comment]
@seokho-son 
https://github.com/cloud-barista/cb-tumblebug/pull/1854 을 통해 CB-SP API 변경 등을 반영하였습니다.

**Comment by seokho-son** [comment]
resolved by https://github.com/cloud-barista/cb-tumblebug/releases/tag/v0.9.16

Thanks to all!
