### ISSUE TITLE
Remove the redundant code for fmt.Print

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#1876]
**What would you like to be enhanced**
- Code clean up by removing redundant codes for fmt.Print

**Why is this needed**
- To improve code readability and to provide clear stdout

**Proposed solution**
- Remove the following print codes (or replace it with log.Info().Msg(".....")

https://github.com/cloud-barista/cb-tumblebug/blob/1d56aec43071926557d6cb9fda2f8d11182d3e79/src/core/common/config.go#L152

```
	fmt.Println("UpdateConfig(); ===========================")
	fmt.Println("UpdateConfig(); Key: " + keyValue.Key + "\nValue: " + keyValue.Value)
	fmt.Println("UpdateConfig(); ===========================")
```

---

**Additional note**
- This is for a new contributor!

**Comment by MohitKambli** [comment]
Hello,
Hope you're doing well
I would like to work on this issue

Thanks and Regards,
Mohit Kambli
