### ISSUE TITLE
GET /tumblebug/ns/default/k8scluster returns 404 when the current k8s object list is empty

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#1941]
**What happened**
: GET /tumblebug/ns/default/k8scluster returns 404 when the list empty

**What you expected to happen**
: GET /tumblebug/ns/default/k8scluster returns empty list when the current k8s object list is empty

**Anything else we need to know?**
: it is required for consistency with other resources

**Environment**
- Source version or branch: main latest

**Proposed solution**
: make /tumblebug/ns/default/k8scluster returns empty list when the current k8s object list is empty

**Comment by seokho-son** [comment]
PTAL @sykim-etri

**Comment by sykim-etri** [comment]
It is presumed to be an error occurring when a k8scluster has never been created in the current code.
I will refer to ListMciInfo() and make the necessary adjustments.
