### ISSUE TITLE
Issue: List and style of CB-Tumblebug CLI tool arguments

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#202]
- Candidates of binary's name
  - tbctl
  - tb
  - tumblebug

---

[Style 1]
| Subcommands | Subsubcommands |
|---|---|
| ns & namespace | create / get / list / listid / delete / deleteall / (update/modify) |
| vnet & vpc | " |
| sg & securitygroup | " |
| sshkey & keypair | " |
| image | " |
| spec & flavor | " |
| mcis | " |
| vm | " |
| (subnet) | " |

[Style 2] (K8s-style)
| Subcommands | Subsubcommands |
|---|---|
| list & getall | ns / vnet / sg / sshkey / image / spec / mcis / vm / (subnet) |
| listid | " |
| create | " |
| register | " |
| get | " |
| (update & modify) | " |
| delete | " |
| deleteall | " |

---

FYI: CB-Spider CLI tool's argument-passing style

![CB-Spider 구현 및 CB-Tumblebug 개발 계획-19](https://user-images.githubusercontent.com/46767780/87019667-d7da6900-c20d-11ea-8fa7-27b67a0d1d40.png)

**Comment by seokho-son** [comment]
@jihoon-seo 
cbadm (cbctl) 에 대한 이슈인가요? 
아니면 tbctl (가칭, 텀블벅 시험 전용 cli 도구) 에 대한 이슈인가요?

cbadm (cbctl) 의 경우,
1번 스타일(개별 자원을 기준으로 처리)이 기본적 제공 사항으로 개발하는 것으로  sig-cli와 협의가 되어 있고,
2번 스타일(apply, list 의 커맨드를 기준으로 처리)도 제가 sig-cli에 제안한 바 있습니다. (구현이 진행되는지 여부는 확인이 필요합니다)

tbctl 자체에 대한 이슈라면,
현재는 1번 스타일을 위한 틀 정도만 구현되어 있어서,
어느쪽 스타일로 가든지 무관할 것 같고, 개인적으로는 2번 스타일을 선호합니다.

**Comment by jihoon-seo** [comment]
@seokho-son 
> cbadm (cbctl) 에 대한 이슈인가요?
아니면 tbctl (가칭, 텀블벅 시험 전용 cli 도구) 에 대한 이슈인가요?

이 이슈 작성 당시에는 tbctl 에 대한 이슈라고 생각하고 작성하였고,
cbadm (cbctl) 에 대해서도 논의될 수 있겠습니다.

> cbadm (cbctl) 의 경우,
1번 스타일(개별 자원을 기준으로 처리)이 기본적 제공 사항으로 개발하는 것으로 sig-cli와 협의가 되어 있고,
2번 스타일(apply, list 의 커맨드를 기준으로 처리)도 제가 sig-cli에 제안한 바 있습니다. (구현이 진행되는지 여부는 확인이 필요합니다)

알겠습니다.

> tbctl 자체에 대한 이슈라면,
현재는 1번 스타일을 위한 틀 정도만 구현되어 있어서,
어느쪽 스타일로 가든지 무관할 것 같고, 개인적으로는 2번 스타일을 선호합니다.

알겠습니다. 추후 tbctl 에 대한 필요성이 높아져서 tbctl 개발이 진행되면
2번 스타일로 개발하는 방안도 있겠습니다.
