### ISSUE TITLE
GitHub says v0.1.0-americano is the latest release

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#205]
[[CB-TB Repo main page](https://github.com/cloud-barista/cb-tumblebug)]
![main](https://user-images.githubusercontent.com/46767780/87398434-d388c400-c5f0-11ea-8bcc-30b6873d34f7.png)

---

[[CB-TB Releases page](https://github.com/cloud-barista/cb-tumblebug/releases)]
![releases](https://user-images.githubusercontent.com/46767780/87398509-e8655780-c5f0-11ea-978a-59fc15b2892d.png)

**Comment by seokho-son** [comment]
I am working on this

**Comment by seokho-son** [comment]
v0.1.0-americano had a wrong commit which leads the latest release.

I changed the commit and date for v0.1.0-americano tag.
Please check, https://github.com/cloud-barista/cb-tumblebug/releases/tag/v0.1.0-americano

Now, the latest release bug has been resolved.

### FYI : procedure to change commit and date for an existing tag. (cf: @jihoon-seo, @powerkimhub)

1. `git show-ref --tags`
// check existing tags
2. `git log`
// check commit log to find a target commit
3. `git checkout c6b6d73`
// checkout to the target commit
4. `GIT_COMMITTER_DATE="$(git show --format=%aD | head -1)" git tag -a v0.1.0-americano -m "v0.1.0-americano" -f`
// retag for a target tag with the target commit with the force option ("-f")
5. `git checkout v0.1.0-americano`
// checkout to the target tag
6. `git log`
// check the target commit is HEAD
7. `git push upstream v0.1.0-americano -f`
// push the changed tag to upstream with the force option ("-f")
