### ISSUE TITLE
Suggestion: Move `action=terminate` from HTTP GET to HTTP PUT

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#23]
As-is:
`GET /ns/1/mcis/2?action=terminate`
`GET /ns/1/mcis/2?action=monitor`

To-be:
`PUT /ns/1/mcis/2?action=terminate`

**Comment by seokho-son** [comment]
@jihoon-seo Since API has been released, let's keep as-is and think about this issue later.

**Comment by jihoon-seo** [comment]
@seokho-son 님과 논의하여,
MCIS / VM 라이프사이클 제어 API를
GetMcis / GetVm API 에서 분리해 내기로 하였습니다. 😊

e.g.
- GET /ns/ns-01/control/mcis/mcis-01
- GET /ns/ns-01/control/mcis/mcis-01/vm/vm-01
