### ISSUE TITLE
TODO: Move(+Rename) cbadm

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#239]
- Current location
  - [cb-spider/interface/cli/cbadm/](https://github.com/cloud-barista/cb-spider/tree/master/interface/cli/cbadm)
  - [cb-tumblebug/src/api/grpc/cbadm/](https://github.com/cloud-barista/cb-tumblebug/tree/master/src/api/grpc/cbadm)

---

- Name candidates
  - cbadm
  - cbctl
  - (tbctl - Fork and modify to a tool for controlling CB-Tumblebug)
  - ...

- Location candidates
  - https://github.com/cloud-barista/cbadm/ (New repo)
  - https://github.com/cloud-barista/cb-tumblebug/tbctl/ (New directory)
  - ...

**Comment by powerkimhub** [comment]
## CB-Waterstrider(Cloud-Barista Interface)
###    = API(REST or Go) + CLI + WebTool

[already exist]
- https://github.com/cloud-barista/cb-webtool

[suggest]
- https://github.com/cloud-barista/cb-cli
- https://github.com/cloud-barista/cb-api

**Comment by jihoon-seo** [comment]
Yet another reference: **GitHub CLI**

- Repo URL: https://github.com/cli/cli
- Filename of binary: `gh`

**Comment by seokho-son** [comment]
This issue has a long tail. Let me close for this moment.
Let's reopen when this issue is rexxed again.
