### ISSUE TITLE
Suggestion: Singular/plural form of objects in cbadm subcommands

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#240]
사소하다고 볼 수도 있겠습니다만..

[cbadm subcommands]
| Subcommands | Subsubcommands |
|---|---|
| connect-infos | create, list, get, delete |
| credential | create, list, get, delete |
| driver | create, list, get, delete |
| region | create, list, get, delete |
| - | - |
| namespaces | create, list, get, delete |
| - | - |
| images | create, list, list-csp, get, get-csp, delete, fetch |
| keypairs | create, list, get, save, delete |
| networks | create, list, get, save, delete |
| securitygroup | create, list, get, save, delete |
| specs | create, list, list-csp, get, get-csp, delete, fetch |
| - | - |
| mcis | create, list, get, delete, <br>status, suspend, resume, reboot, terminate, <br>add-vm, list-vm, get-vm, del-vm, <br>status-vm, suspend-vm, resume-vm, reboot-vm, terminate-vm, <br>command, command-vm, deploy-milkyway, access-vm, benchmark |

---

[현황]
- "Subcommands" 에 단수형과 복수형이 혼재되어 있습니다.
- "Subcommand" 를 정확히 적지 않으면 cbadm이 에러를 리턴합니다.
```
❯ ./cbadm image                  
Error: unknown command "image" for "cbadm"

Did you mean this?
        images

Run 'cbadm --help' for usage.
2020-08-25 10:49:57.557050 I | cbadm terminated with error:  unknown command "image" for "cbadm"

Did you mean this?
        images
```

---

[다른 예: kubectl (cbadm과 Subcommands - Subsubcommands 순서가 반대이기는 함)]
- 단수형과 복수형 모두 인식함
```
❯ kubectl get node
NAME   STATUS   ROLES    AGE   VERSION
vm     Ready    master   27d   v1.18.3

❯ kubectl get nodes
NAME   STATUS   ROLES    AGE   VERSION
vm     Ready    master   27d   v1.18.3
```

- 약어도 인식함
```
❯ kubectl get service                    
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   27d

❯ kubectl get svc                        
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   27d
```

---

[제안]
- 1안: 단수형, 복수형, 약어 모두 인식하도록 함
  - 예: ns, namespace, namespaces // sg, securitygroup, securitygroups
- (1안이 힘들다면) 2안: 단수형으로 통일
  - Subsubcommands 중 create, get, delete 등은 입력/출력이 자원 복수개가 아닌 1개 입니다.
  - 입력/출력이 자원 복수개인 다른 Subsubcommands 에 단수형 Subcommands를 써도 별로 어색하지 않아 보입니다. 그런데 반대의 경우에는 어색해 보입니다.

**Comment by seokho-son** [comment]
@jihoon-seo 저는 
"2안: 단수형으로 통일" 우선 통일하는 것이 좋을 것 같습니다.
코브라에서 자동으로 만들어주는 help 기능을 고려하면, 명령어가 1개로 명확 것이 좋을 것 같기 때문입니다.

kubectl의 경우 오퍼레이션을 우선적으로 명시하는 방식이라, 현재 cbadm 의 명령어 구성 방식과는 다소 차이가 있겠네요.
