### ISSUE TITLE
Suggestion: Make cbadm executable without sourcing setup.env

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#242]
@powerkimhub 
(이 이슈는 cb-store / cb-log 와 관련이 있습니다.)

---

현재 `cbadm` 을 실행할 때, (예: CB-Tumblebug 에서 사용하던) `setup.env` 를 적용해야 실행이 가능합니다.

---

```
❯ cd cb-tumblebug/src/api/grpc/cbadm
❯ ./cbadm
2020/08/27 13:10:33 error: open /conf/log_conf.yaml: no such file or directory
```

(`cbadm`이 cb-log 패키지를 활용하였고,
cb-log에서는
`CBLOG_ROOT` 환경변수에 기재된 경로 아래의 `./conf/log_conf.yaml` 를 오픈하는데
`CBLOG_ROOT` 환경변수가 설정되어 있지 않아 `/conf/log_conf.yaml` 를 오픈 시도 했고 실패했음)

---

```
❯ export CBLOG_ROOT=$GOPATH/src/github.com/cloud-barista/cb-tumblebug

❯ ./cbadm                                                            
[CLOUD-BARISTA].[ERROR]: 2020-08-27 13:16:38 config.go:63, github.com/cloud-barista/cb-store/config.GetConfigInfos() - open /conf/store_conf.yaml: no such file or directory
panic: open /conf/store_conf.yaml: no such file or directory

goroutine 1 [running]:
github.com/cloud-barista/cb-store/config.GetConfigInfos(0x10)
        /root/go/pkg/mod/github.com/cloud-barista/cb-store@v0.1.1/config/config.go:64 +0x2ee
github.com/cloud-barista/cb-store/store-drivers/nutsdb-driver.initialize()
        /root/go/pkg/mod/github.com/cloud-barista/cb-store@v0.1.1/store-drivers/nutsdb-driver/nutsdb-driver.go:31 +0x34
github.com/cloud-barista/cb-store/store-drivers/nutsdb-driver.init.0()
        /root/go/pkg/mod/github.com/cloud-barista/cb-store@v0.1.1/store-drivers/nutsdb-driver/nutsdb-driver.go:27 +0x20
```

(`cbadm`이 cb-store 패키지를 활용하였고,
cb-store에서는
`CBSTORE_ROOT` 환경변수에 기재된 경로 아래의 `./conf/store_conf.yaml` 를 오픈하는데
`CBSTORE_ROOT` 환경변수가 설정되어 있지 않아 `/conf/store_conf.yaml` 를 오픈 시도 했고 실패했음)

---

```
❯ export CBSTORE_ROOT=$GOPATH/src/github.com/cloud-barista/cb-tumblebug

❯ ./cbadm                                                              
This is a lightweight grpc cli tool for Cloud-Barista
(실행이 됨)
```

---

`cbadm` 이 cb-store 와 cb-log 를 활용하고 있어서 그렇다는 것은 알겠는데..
CB를 이용하기 위한 툴인 `cbadm`을 실행하는 데에도
`CBSTORE_ROOT`, `CBLOG_ROOT` 환경변수를 설정하기 위해
`source setup.env` 등의 작업을 해야 하는 것은 사용자에게 비직관적이고 불편해 보입니다.

`source setup.env` 등의 작업을 하지 않아도
`cbadm` 이 실행 가능하도록 하는 것은 어떨까요?
(그리고 장기적으로는 CB-Spider, CB-Tumblebug, ... 들도..)

**Comment by powerkimhub** [comment]
@jihoon-seo @jmleefree 

- cbadm이 cb-store를 사용해야 하는 부분이 있나요?

**Comment by seokho-son** [comment]
@jihoon-seo Please change the title of this PR in English :)

**Comment by jmleefree** [comment]
@powerkimhub  @jihoon-seo 
- cbadm 이 CBSTORE_ROOT 를 사용하는 것은 버그로 수정사항 커밋했습니다.

**Comment by powerkimhub** [comment]
@powerkimhub @jihoon-seo @seokho-son 

이제 남은 환경변수들이 다음과 같군요.

- Client
  - CBLOG_ROOT: logger 설정 파일 위치를 위한 환경변수

- Server
  - CBLOG_ROOT: logger 설정 파일 위치를 위한 환경변수
  - CBSTORE_ROOT: 메타 정보 저장소 및 설정 파일 위치를 위한 환경변수
  - {FW}_ROOT: 프레임워크 내 특정 path 및 파일 위치를 위한 환경변수

필요한 시점이 되면 이런 방식으로 변경 하면 될듯합니다. 
- (방법-1) /etc/cloud-barista/* 등 특정 위치에 설정 파일 설치
- (방법-2) 설치시 cloud-barista 경로 하나만 입력 받거나, 환경 변수($CLOUD-BARISTA 등) 설정 요청 해서 내부에서 이를 활용
- (참고) 통상 제품에서도 사용자의 환경 변수 설정은 일반적입니다. 
             현재는 개발버전이라서 갯수가 많고, 프레임워크마다 달라서 그렇지^^
