### ISSUE TITLE
Suggestion: Separate common components installation guides to common repo

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#246]
@powerkimhub @seokho-son 

현재 Spider, TB, Dragonfly 등의 README 에
Go, Docker 등의 설치 방법을 안내하고 있을텐데요
이 부분을 분리하여 공통 repo에 두고
TB README 안에는 [공통 repo / Go 설치 방법.md] 로의 링크를 제공하는 방식으로 바꾸는 것은 어떨지
제안해 봅니다.

- 사유
  - 공통 부분 중복을 줄임
  - 한 곳만 업데이트하면 됨
- 단점
  - 사용자가 TB 등의 README 를 따라가다가, 다른 파일도 조회해 봐야 함 (context 전환)
- 기타
  - 다른 곳에서도 이런 식(링크)으로 제공하는 경우가 있음

**Comment by seokho-son** [comment]
중복되는 내용이 많으면 공통으로 사용하는 것도 방법인데,
해당 사항은 중복되는 내용이 그리 많지는 않을 것 같네요.
보통 파일을 공통으로 사용하게되면 해당 파일의 오너십이 약해져서 관리가 안되는 경향도 있는것 같습니다.
그래서 이건은 지금처럼 각 리포에서 관리하는 것이 좋을 것 같습니다.
