### ISSUE TITLE
Code convention: Use tab indentation for Go files (Follow gofmt)

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#262]
I (@jihoon-seo) prefer
- **space indents** to tab indents
- **4-space indents** to 2-space indents

---

It would be appreciated if you share any ideas!

**Comment by seokho-son** [comment]
재미로 읽어보시기 바랍니다..^^
https://thenewstack.io/spaces-vs-tabs-a-20-year-debate-and-now-this-what-the-hell-is-wrong-with-go/

**Comment by seokho-son** [comment]
@jihoon-seo 
gofmt 의 기본 포멧을 사용하는 것은 어떨까요..?
https://golang.org/cmd/gofmt/

**Comment by jihoon-seo** [comment]
@seokho-son 
Go 는 tab 이 대세라는 것도,
gofmt 가 tab indent 로 맞춰주는 것도 처음 알았습니다.

현재 대부분의 .go 파일은 tab indent 인 것 같습니다.
(@cloud-barista/cb-tumblebug-maintainer 인 @seokho-son 과 @jihoon-seo 가
VSCode + Go extension 쓰고 있어서 그런 것 같습니다.)

말씀하신 대로, .go 파일은 gofmt 기본 포맷을 따르면 좋을 것 같습니다.

---

TB Repo에는 test 용 shell scripts 도 많은데요
몇 개를 확인해 보니 tab indent 도 있고 space indent 도 있습니다.

.sh 파일 등에 대해서는
1. 일단은 자유롭게 골라서 사용한다.
2. 어느 정도 code convention / indent style 을 가이드한다.
등의 방안이 있을 수 있겠습니다.

**Comment by seokho-son** [comment]
test 용 shell scripts 는 쉽게 변경될 수도 있어서, 1번 안을 선호합니다.. ^^
이 정도로 일단락하고, 향후에 정리하면 좋을 것 같습니다.
