### ISSUE TITLE
Suggestion: Add UMLs of CB-Tumblebug operation flows

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#265]
Reference: https://github.com/cloud-barista/cb-ladybug/pull/2/files

[PlantUML WYSIWYG editors]
- https://liveuml.com/
- https://plantuml-editor.kkeisuke.com/
- https://www.planttext.com/

**Comment by seokho-son** [comment]
@jihoon-seo This would be a nice feature !! but priority seems low.
Is the upcoming API tracking feature of the cb-apigateway a possible way to draw this information?

**Comment by jihoon-seo** [comment]
@seokho-son I agree that the priority of this issue is low.
And it seems uncertain whether the sequence diagrams can be generated/drawn from the results of cb-restapigw's global tracing / API tracking.
