### ISSUE TITLE
TODO: Implement some functions

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#27]
As-is:
There are some missing functions in:

- mcism_namespace.go
- mcism_mcis.go
- mcism_resource_manage_image.go
- mcism_resource_manage_network.go
- mcism_resource_manage_securityGroup.go
- mcism_resource_manage_spec.go
- mcism_resource_manage_sshKey.go
- mcism_resource_manage_subnet.go

e.g. `mcism_resource_manage_image.go`

| REST-handling func  | Actual func |  |
| ------------- | ------------- | --- |
| restDelAllImage  | -  | The logic is implemented in restDelAllImage function. |
| restDelImage  | delImage  |
| restGetAllImage  | getImageList  |
| restGetImage  | -  | The logic is implemented in restGetImage function. |
| restPostImage  | createImage, registerImage  |
| restPutImage  | -  | e.g. `modifyImageInfo()` function might be needed or not. |

Since there is no `delAllImage()` or `getImage()` function,
a user cannot delete all images or get image info using gRPC.

---

To-be:
e.g. `mcism_resource_manage_image.go`

| REST-handling func  | Actual func |  |
| ------------- | ------------- | --- |
| restDelAllImage  | **delAllImage**  | The logic is implemented in **delAllImage** function. |
| restDelImage  | delImage  |
| restGetAllImage  | getImageList  |
| restGetImage  | **getImageInfo**  | The logic is implemented in **getImageInfo** function. |
| restPostImage  | createImage, registerImage  |
| restPutImage  | **(modifyImageInfo)**  | `modifyImageInfo()` function might be implemented or not. |

**Comment by jihoon-seo** [comment]
As of 2020-07-29:

| REST-handling func  | Actual func |  |
| ------------- | ------------- | --- |
| RestDelAllImage  | DelAllResources | (Unified common function) |
| RestDelImage  | DelResource | (Unified common function) |
| RestGetAllImage  | ListResource | (Unified common function) |
| **(Does not exist)** | ListResourceId | (Unified common function) |
| RestGetImage  | GetResource | (Unified common function) |
| RestPostImage  | RegisterImageWithId, RegisterImageWithInfo |
| RestPutImage  | **(Does not exist)**  | `ModifyImageInfo()` function might be implemented or not. |

---

[REST API for `ListResourceId` function]
- Option 1: Implement and provide the REST API for `ListResourceId` function
- Option 2: Do not implement and provide the REST API for `ListResourceId` function

---

[`ModifyImageInfo()` (and so on) function]
- Option 1: Implement and provide the `ModifyImageInfo()` (and so on) function
  - There exists possibility that the actual logic of these functions might be `Delete and Register`.
- Option 2: Do not implement and provide the `ModifyImageInfo()` (and so on) function

**Comment by seokho-son** [comment]
이 이슈는 어느 정도 해결이 되어 있는 것으로 보이네요 ^^ 일단 close 하겠습니다.
/close

**Comment by jihoon-seo** [comment]
/close
K8s prow bot 은 command 위치에 상관없이 동작하는데
저희가 쓰고 있는 것은 command 가 comment 의 맨 처음에 와야 동작을 하고
한 comment 에 복수 command 있으면 맨 처음 것만 처리하네용..
Improved version 이 있으면 좋겠네용 😊
