### ISSUE TITLE
Question: stable branch for CB-Ladybug development

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-tumblebug#284]
에스프레소 릴리즈를 위한 CB-Ladybug 개발에 활용할 수 있는 안정적인 CB-Tumblebug 버전이 궁금합니다.
참고로 현재는 tag:v0.2.0-cappuccino을 기준으로 개발 중에 있습니다.

**Comment by seokho-son** [comment]
(cc @jihoon-seo )

@sykim-etri 텀블벅의 어떤 기능을 활용하시나요?

텀블벅은 master (개발 브랜치)가 항상 동작 가능하도록 유지하고 (노력하고) 있습니다. 
따라서 master 최신 버전을 사용해도 무관할 것으로 보입니다.

그러나, 사용하시는 텀블벅의 기능이 tag:v0.2.0-cappuccino 로도 충분하시다면 꼭 최신 버전을 사용하실 필요는 없습니다.
