### ISSUE TITLE
NS, MCIS emptiness check

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#29]
#25 에서 이슈가 제기되었고
#28 PR을 통해
'삭제하려는 NS에 적어도 하나의 MCIS, Image, Network, SecurityGroup, Spec, SshKey, Subnet이 있으면 NS 삭제 실패를 리턴하는 로직' 을
delNs() 함수에 추가하였습니다.

이렇게 하니, 사용자가 '삭제하려는 NS에 적어도 하나의 MCIS, Image, Network, SecurityGroup, Spec, SshKey, Subnet이 있더라도 NS를 강제로 삭제' 할 수는 없는 상태입니다.

또한, delMcis() 함수는 #28 의 delNs() 함수와 다르게, 삭제하려는 MCIS 아래에 VM이 있으면 이를 Terminate & Delete 하고, 최종적으로 MCIS를 삭제하는 로직으로 작성되어 있습니다.

---

[Emptiness check 로직을 어디에 둘 것인가]
- 1안: delNs() 함수와 같이 del**() 함수 안에 둔다
  - Webtool 등에서 restDelNs() / delNs() 함수만 호출해도 Emptiness check이 수행됨
  - 강제 삭제 함수는 없는 상태임 (필요 시 구현 가능)
  - 1안으로 결정되면, delMcis() 함수를 업데이트 해야 합니다.
- 2안: del**() 함수 안에 두지 않는다
  - Webtool 등에서 restGetAllMcis, restGetAllImage, ... 등을 호출하여 Emptiness check을 수행하고, 통과되면 restDelNs() / delNs() 를 호출하여 실제로 삭제 (SEO 의견: 이렇게 하면 API call이 너무 많음)
  - del**() 함수 자체가 강제 삭제 함수의 역할을 함
  - 2안으로 결정되면 delNs() 함수를 업데이트 해야 합니다.

**Comment by seokho-son** [comment]
NS를 강제로 삭제해야하는 경우는 어떤 경우일까요?
아마 관리자 입장에서, 시스템 오류(삭제된 NS에 포함된 MCIS 발생 등)가 발생한 경우에 강제 삭제가 필요할 것 같습니다. 이 경우, 사용자 API로 기능을 내어주기 보다는 향후 관리자 도구 등을 통해 기능을 제공하는 것이 좋을 것 같습니다.

강제 삭제 함수를 만들지 말고, 해당 NS에 포함된 모든 MCIR, MCIS 리스트를 사용자에게 제공하는 방식은 어떨까요? 사용자가 확인 후, 직접 삭제할 수 있도록.

**Comment by jihoon-seo** [comment]
2019년 10월 8일에
#28 PR을 통해
'삭제하려는 NS에 적어도 하나의 MCIS, Image, Network, SecurityGroup, Spec, SshKey, Subnet이 있으면 NS 삭제 실패를 리턴하는 로직' 이
delNs() 함수에 추가되었었는데요.

---

2019년 11월 6일에
https://github.com/cloud-barista/cb-tumblebug/commit/d45305b12ce7be4942ccd844ee222dbe6a918d1b#diff-cd085ee3c4f966bb3b46b0750bce7895R210
이 commit 에서 주석처리 되었습니다.

주석처리된 부분을 살리려고 오늘 시도해 봤더니
```
import cycle not allowed
package github.com/cloud-barista/cb-tumblebug/src
        imports github.com/cloud-barista/cb-tumblebug/src/apiserver
        imports github.com/cloud-barista/cb-tumblebug/src/common
        imports github.com/cloud-barista/cb-tumblebug/src/mcir
        imports github.com/cloud-barista/cb-tumblebug/src/common
```
위와 같은 에러가 납니다.
(이미 `src/mcir/common.go` 에서 `src/common` package 를 import 하고 있는 상황에서,
`src/common/namespace.go` 에서 `src/mcir` package 를 import 하려고 하니
import cycle 이 발생하여 에러 표출)

2019년 11월 6일 당시에도
import cycle 이 발생하는 문제 때문에
해당 부분을 주석처리 한 것 같습니다.

---

해당 기능을 살릴 수 있으면 좋을 것 같습니다.

**Comment by jihoon-seo** [comment]
- NS emptiness check: Implemented in PR #267 
- MCIS emptiness check: Delete MCIS 명령을 내리면 하위 VM들을 모두 terminate & delete 하도록 되어 있어서, MCIS emptiness check 은 불필요 할 것 같습니다.
