### ISSUE TITLE
Almost hang when creating MCIS with non existing image

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-tumblebug#299]
실수로 없는 AMI ID로 MCIS 생성을 요청하였는데, InstallMonAgent까지 진행되면서 계속 SSHRUN을 시도하고 있는 상황이오니 검토를 부탁드립니다.

o Tested version: v0.2.5
o Log : [non-existing-image.log](https://github.com/cloud-barista/cb-tumblebug/files/5456981/non-existing-image.log)

**Comment by seokho-son** [comment]
@sykim-etri Bug 리포트 감사합니다. 해당 Bug는 0.3.0 이상 버전으로 릴리스되며 여러 커밋들에 의해서 해결된 것으로 보입니다.

현재 TB의 master 버전에서 다양하게 테스트를 해보았고, 
실수로 없는 Image ID (AMI) 로 MCIS(VM)를 생성하면, TB가 VM 생성시 바로 오류 처리를 합니다.
그리고, 정상 생성되지 않은 VM의 경우 모니터링 Agent 설치 등을 수행하지 않고 바로 결과를 리턴합니다.

마스터 또는 곧 생성될 차기 프리릴리스 (CB-Tumblebug v0.3.5) 에서 시험해보시면 좋을 것 같습니다.
감사합니다.. ^^
