### ISSUE TITLE
Enhancements for MCIS and MCIR (backlog)

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#30]
[근시일]
- ~~파일 새로 만들기~~
  - ~~mcism_resource_manage_publicIp.go~~
  - ~~mcism_resource_manage_vNic.go~~
- ~~"csp": "aws" 로 되어 있는 부분을 "connectionName": "aws-connect01" 으로 변경~~
- ~~CSP 와 통신하는 부분이 farmoni 코드로 되어 있는데, 이를 Spider 에서 제공할 REST API 로 변경. HTTP client 는 "net/http" 사용. `cb-spider/cloud-control-manager/cloud-driver/drivers/cloudit/client` 참고. HTTP client 코드는 많이 쓰일 것이므로 모듈화를 잘 해놓는 것이 좋을 것임. Published Postman doc 에서 Go 코드를 얻을 수도 있음. Echo 를 client 로 사용할 수도 있음.~~

[추후]
- ~~(Spider 에서 interfaces_v2 가 완성되면) `cb-spider/cloud-control-manager/cloud-driver/interfaces/new-resources` 에 적혀 있는 struct 를 Tumblebug 에도 도입~~
- ~~Tumblebug 에서, Create-Delete 는 메타정보 추가/삭제 + CSP에 명령 이고, Register-Unregister 는 메타정보 추가/삭제만 하는 것임. Register-Unregister 는 Spider 에서는 처리하지 않을 것이고, Tumblebug 에서 처리해야 함~~
- Spider 에서 CSP 에 있는 VM / 자원 전체를 긁어오지는 않을 것임. (CB 를 통하지 않고 만들어진 것도 있을 수 있어서.) Tumblebug 에서 메타정보를 보고 loop 을 돌려 긁어와야 할 것임.

[2019-10-17 추가]
TODO:
Support for
- ~~All files - `KeyValueList []KeyValue`~~
- ~~`SecurityHandler.go`~~
  - ~~`SecurityRules *[]SecurityRuleInfo`~~
- ~~`VMHandler.go`~~
  - ~~`SecurityGroupIds []string`~~
  - ~~`Region       RegionInfo`~~
- ~~`VNicHandler.go`~~
  - ~~`SecurityGroupIds []string`~~

[2019-10-23 추가]
TODO:
- `mcism_mcis.go` - `type vmInfo struct` - `StartTime    time.Time`
CB-Spider <=> CB-Tumblebug <=> CB-Store
Marshal / Unmarshal 시 Format 신경써야 함
Ref: https://stackoverflow.com/questions/25845172/parsing-date-string-in-go

**Comment by jihoon-seo** [comment]
- ~~"csp": "aws" 로 되어 있는 부분을 "connectionName": "aws-connect01" 으로 변경~~: 2019-10-10 완료

**Comment by seokho-son** [comment]
related with #37
