### ISSUE TITLE
Suggestion: Change workflow name // Integrate 2 workflows

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#342]
[As-is]

https://github.com/cloud-barista/cb-tumblebug/actions

![image](https://user-images.githubusercontent.com/46767780/103717397-be717880-5008-11eb-97a6-91d7c226e2d1.png)

---

https://github.com/cloud-barista/cb-tumblebug/blob/0c21eb426dc7ecd23b86d6721e8f3a13d30e1dc3/.github/workflows/dockerhub.yaml#L1

My suggestion: `Multi-arch -> Docker Hub`

---

https://github.com/cloud-barista/cb-tumblebug/blob/0c21eb426dc7ecd23b86d6721e8f3a13d30e1dc3/.github/workflows/ghcr-push.yaml#L1

My suggestion: `amd64 -> GHCR`

---

---

Those 2 workflows can be integrated,
e.g. `Multi-arch -> Docker Hub & GHCR`

**Comment by seokho-son** [comment]
This PR is `good first issue`. @hermitkim1 could you help us ~ ? ;)

**Comment by hermitkim1** [comment]
Why not! I can help you of course 😄

In my understanding, it's needed to integrate 2 workflows and publish container images to Docker Hub and GHCR (multi-arch to Docker Hub, amd64 to GHCR).

Can I proceed with the above and make a PR?

**Comment by jihoon-seo** [comment]
@hermitkim1 
저의 제안은..

[As-is]

https://github.com/cloud-barista/cb-tumblebug/blob/0c21eb426dc7ecd23b86d6721e8f3a13d30e1dc3/.github/workflows/dockerhub.yaml#L53-L72

- Docker Hub 에 로그인 하고
- multi-arch build 하고 push

의 순서로 진행되는데..

[To-be]

위의 파일에

- GHCR 에도 로그인 하고
- (위에서 build 했던) multi-arch 이미지를 GHCR 에도 push

하는 내용을 추가하면
여러 번 빌드하지 않고 한 번만 빌드하여 두 곳에 올릴 수 있어서 좋을 것 같습니다!

(현재 `dockerhub.yaml`, `ghcr-push.yaml` 두 파일의 스타일/내용 등이 조금씩 다릅니다..)

**Comment by hermitkim1** [comment]
@jihoon-seo 

설명 감사드립니다!

Multi-arch container image를 Docker Hub와 GHCR 모두에 Publish할 수 있도록 워크플로우 통합을 진행하겠습니다.

진행 순서는 아래와 같습니다.
1) 두 워크플로우를 분석
2) `ghcr-push.yaml`에서 필요한 내용 발췌
3) 발췌한 부분 `dockerhub.yaml`에 추가
4) 그 밖에 필요한 부분 정리(name, 주석 등) 
5) 통합된 워크플로우 Test
