### ISSUE TITLE
Suggestion: Use [skip ci] in GitHub Actions

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#359]
How about supporting [skip ci] for GitHub Actions.

With this, we can skip CI if a commit title includes `[skip ci]`.

I think it is useful for handling bot generated PRs. 

For instance, `allcontributors`-bot includes `[skip ci]` in every commit titles like [this PR](https://github.com/cloud-barista/cb-tumblebug/pull/355/commits).

Rf (How to): https://dev.to/epassaro/use-skip-ci-in-github-actions-1mnf

**Comment by seokho-son** [comment]
Call for experts : @jihoon-seo @hermitkim1

**Comment by hermitkim1** [comment]
I think it's a very useful magic trick, especially nice for bot-generated CI workflows. 👍 
And also, a contributor can have 2 options (Perform workflow / Skip workflow).
