### ISSUE TITLE
Check appropriate 3rd party pkg

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#368]
In https://github.com/cloud-barista/cb-tumblebug/blob/master/src/api/rest/server/common/utility.go

`github.com/astaxie/beego/validation` has been included.

https://github.com/cloud-barista/cb-tumblebug/blob/a8680e552d77057d1afefee546538f494937ac03/src/api/rest/server/common/utility.go#L8

I found that `github.com/astaxie/beego/validation` is a fork of `https://github.com/beego/beego`.
It seems `https://github.com/beego/beego` is official repo.

Should we use beego/beego instead of astaxie/beego ?

**Comment by seokho-son** [comment]
PTAL @jihoon-seo

**Comment by jihoon-seo** [comment]
제가 추정하기로는
원래는 `github.com/astaxie/beego` repo 만 있었는데
개발자 (astaxie) 가
`github.com/beego` org 를 만들고
`github.com/beego/beego` repo 도 만들고, base repo 를 이것으로 변경한 것이 아닐까 합니다.

CB-Tumblebug 코드에
`"github.com/astaxie/beego/validation"` 로 되어 있는 것을
`"github.com/beego/beego/v2/validation"` 로 업데이트하려고 시도했는데 잘 되지 않아서
beego repo 에 이슈를 작성했습니다. (https://github.com/beego/beego/issues/4457)
커멘트가 달리면 그에 따라 업데이트를 하겠습니다.
