### ISSUE TITLE
Add VM group feature to request multiple VMs simply

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#412]
**What would you like to be added**
MCIS 생성 요청시, VM 그룹 개념을 제공하여, 
동일한 MCIR을 공유하는 VM의 생성을 쉽게 제공하도록 특징 추가

**Why is this needed**
기존에는 MCIS 생성시 동일한 MCIR을 공유하는 VM에 대해서도, 중복적으로 MCIR 명시가 필요했으며, 
이는 향후 클러스터 단위의 VM 생성시 사용자의 불편을 야기할 수 있음.

**Comment by jihoon-seo** [comment]
- Related discussion: #405
