### ISSUE TITLE
Add TB APIs wrapping some Spider APIs

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#461]
**What would you like to be added**
: https://github.com/cloud-barista/cb-tumblebug/tree/master/src/testclient/scripts/1.configureSpider 에 해당하는 Spider API들을
TB API로 wrapping 하여, 
MCIS 사용자가 Spider를 몰라도 TB를 사용할 수 있도록 API 확장이 필요

**Why is this needed**
: MCIS 사용자 및 TB 개발자의 편의성 향상 측면
(Based on a discussion in https://cloud-barista.slack.com/archives/CUUR82Q4D/p1618387746085700)

**Comment by powerkimhub** [comment]
@seokho-son 

- 확장 API 형상(TB Utility or CB API ??)에 따라 Cloud-Barista 규격/구조 등 형상에 영향이 있을 듯합니다. 
- 추진 전에 확장 API 사전 공유 및 협의가 필요해 보입니다.

**Comment by seokho-son** [comment]
- fixed. see #1531

**Comment by seokho-son** [comment]
fixed since v0.8.9
