### ISSUE TITLE
Abnormal MCIS/VM object can be created

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#469]
**What happened**
: 
Although CB-Spider returned an error for the VM create request from CB-Tumblebug,
abnormal MCIS/VM object is created.
(정상적이지 않은 MCIS object 가 생성되는 경우가 있습니다.)

**What you expected to happen**
: 
If CB-Spider returns an error for the VM create request from CB-Tumblebug,
MCIS/VM object is **not** created

**How to reproduce it (as minimally and precisely as possible)**
: 
To be described

**Anything else we need to know?**
: 

**Environment**
- Source version or branch: 
- OS: 
- Others: 

**Proposed solution**
: 

**Any other context**
:

---

~**What would you like to be added**~
: 
~Force-delete option on MCIS/VM~

~**Why is this needed**~
:

- 정상적이지 않은 MCIS object 가 생성되는 경우가 있습니다.
- ~현재 MCIS 에 대해서는 강제 삭제 옵션이 없습니다.~
- ~c.f. MCIR 에 대해서는 강제 삭제 옵션이 있습니다.~
  - ~`mcir.DelResource(nsId, resourceType, resourceId, forceFlag)`~
  - ~`mcir.DelAllResources(nsId, resourceType, forceFlag)`~

**Comment by seokho-son** [comment]
@jihoon-seo 리포트 감사합니다.
정상적이지 않은 MCIS object 가 생성되는 경우는 어떤 경우인가요? (VM의 creating이 완료되지 않은 MCIS?)

문제가 있는 VM을 포함한 MCIS 오브젝트인 경우, MCIS 삭제 기능을 통해서 삭제가 가능한 것으로 알고 있는데,
혹시 삭제가 되지 않는 상황에 직면하신 것인가요?

**Comment by jihoon-seo** [comment]
@seokho-son 

> 정상적이지 않은 MCIS object 가 생성되는 경우는 어떤 경우인가요? (VM의 creating이 완료되지 않은 MCIS?)

예를 들어, Cloud-Twin 테스트 시
CB-Spider 에 등록해 놓은 Credential 객체가 다음과 같습니다.

```JSON
{
  "CredentialName": "cloudtwin-credential01",
  "ProviderName": "CLOUDTWIN",
  "KeyValueInfoList": [
    {
      "Key": "DomainName",
      "Value": "cloud-1"
    },
    {
      "Key": "IdentityEndpoint",
      "Value": "dK\u001a�Z`X-C\u0013y���`�&n=T�!�Q,����\u0005��\u0017n�\b�\u000e5�\u0001�U�燓N:��["
    },
    {
      "Key": "MockName",
      "Value": "mock_name-1"
    }
  ]
}
```

여기에서, 
`DomainName` 이 `cloud-1`  과 다른 형식이거나
`MockName` 이 `mock_name-1` 과 다른 형식이면
사용자가 CB-Tumblebug 을 통해 VM 을 생성할 때 
CB-Spider 에서 에러를 리턴하지만 (에러: "`DomainName` 이 `xxxx` 이다" 또는 "`MockName` 이 `xxxx` 이다")
CB-Tumblebug MCIS/VM 객체가 만들어지는 경우가 있습니다.
(이렇게 만들어진 MCIS/VM 객체는 `PublicIP`, `PrivateIP` 등이 비어 있는, 정상적이지 않은 객체임)

이렇게 만들어진 비정상적인 MCIS/VM 객체는
`cb-tumblebug/test/official/8.mcis/terminate-and-delete-mcis.sh` 스크립트로는 삭제가 되지 않습니다.

`# ./terminate-and-delete-mcis.sh cloudtwin 1 jhseo`
```
####################################################################
## 8. VM: Terminate and Delete MCIS
####################################################################
{
  "message": "Failed to delete the MCIS"
}
```

---

Cloud-Twin 말고도, TB 의 VM 생성 요청에 대해 CB-Spider 에서 에러를 리턴했는데
CB-Tumblebug 이 비정상적인 MCIS/VM 객체를 만드는 다른 경우도 있습니다.

---

추가: 위의 Cloud-Twin 사례에서, `DomainName` 과 `MockName` 을 제대로 입력하고 시도하여
정상적인 MCIS/VM 객체가 만들어졌음에도
CB-Tumblebug 에서 MCIS 삭제가 되지 않습니다.

참고: #472 (Test for supporting Cloud-Twin)

`# ./terminate-and-delete-mcis.sh cloudtwin 1 jhseo`
```
####################################################################
## 8. VM: Terminate and Delete MCIS
####################################################################
{
  "message": "Failed to delete the MCIS"
}
```

**Comment by jihoon-seo** [comment]
CB-Spider 의 오류일 가능성도 있겠습니다.
한 번 살펴 보겠습니다.

**Comment by jihoon-seo** [comment]
비정상적인 MCIS/VM 객체 예시

`# ./createAll-mcis-mcir-ns-cloud.sh all 1 jhseo`

```
####################################################################
## 8. Create MCIS with a single VM
####################################################################
####################
 AgentInstallOn: no
####################
{
  "id": "cloudtwin-region01-jhseo",
  "name": "cloudtwin-region01-jhseo",
  "status": "Failed-(1/1)",
  "targetStatus": "Running",
  "targetAction": "Create",
  "installMonAgent": "no",
  "label": "",
  "placement_algo": "",
  "description": "Tumblebug Demo",
  "vm": [
    {
      "id": "cloudtwin-region01-jhseo-lead-0",
      "name": "cloudtwin-region01-jhseo-lead-0",
      "vmGroupId": "cloudtwin-region01-jhseo-lead",
      "location": {
        "latitude": "36.3804",
        "longitude": "127.3650",
        "briefAddr": "South Korea (Daejeon)",
        "cloudType": "cloudtwin",
        "nativeRegion": "default"
      },
      "status": "Failed",
      "targetStatus": "Running",
      "targetAction": "Create",
      "monAgentStatus": "",
      "createdTime": "",
      "systemMessage": "{\"message\":\"Internal Server Error\"}\n",
```

CB-Spider 에서 `{\"message\":\"Internal Server Error\"}\n` 를 리턴했는데
CB-Tumblebug 이 비정상적인 MCIS/VM 객체를 만들었습니다.

**Comment by seokho-son** [comment]
> 비정상적인 MCIS/VM 객체 예시
> 
> `# ./createAll-mcis-mcir-ns-cloud.sh all 1 jhseo`
> 
> ```
> ####################################################################
> ## 8. Create MCIS with a single VM
> ####################################################################
> ####################
>  AgentInstallOn: no
> ####################
> {
>   "id": "cloudtwin-region01-jhseo",
>   "name": "cloudtwin-region01-jhseo",
>   "status": "Failed-(1/1)",
>   "targetStatus": "Running",
>   "targetAction": "Create",
>   "installMonAgent": "no",
>   "label": "",
>   "placement_algo": "",
>   "description": "Tumblebug Demo",
>   "vm": [
>     {
>       "id": "cloudtwin-region01-jhseo-lead-0",
>       "name": "cloudtwin-region01-jhseo-lead-0",
>       "vmGroupId": "cloudtwin-region01-jhseo-lead",
>       "location": {
>         "latitude": "36.3804",
>         "longitude": "127.3650",
>         "briefAddr": "South Korea (Daejeon)",
>         "cloudType": "cloudtwin",
>         "nativeRegion": "default"
>       },
>       "status": "Failed",
>       "targetStatus": "Running",
>       "targetAction": "Create",
>       "monAgentStatus": "",
>       "createdTime": "",
>       "systemMessage": "{\"message\":\"Internal Server Error\"}\n",
> ```
> 
> CB-Spider 에서 `{\"message\":\"Internal Server Error\"}\n` 를 리턴했는데
> CB-Tumblebug 이 비정상적인 MCIS/VM 객체를 만들었습니다.

"status": "Failed",
"systemMessage": "{\"message\":\"Internal Server Error\"}\n",

VM 오브젝트 자체를 생성하지 않으면, MCIS에 어떤일이 발생한 것인지 알기 어렵고 
그렇다고 MCIS 생성 자체를 도중에 중단하는 것도 어려울 것 같습니다. (여러 VM이 생성되고 있으므로)

따라서, status, systemMessage 를 통해서 해당 VM의 Provisioning이 정상적이지 않다는 것을 표시하고 있습니다. (단 애러메시지는 보완이 필요해보이네요..^^)

이는 비정상적인 MCIS / VM 객체라고 이야기하기 어려울 것 같습니다.
