### ISSUE TITLE
Swagger validator says TB's swagger.yaml is invalid

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#471]
**What happened**
: 
Swagger validator says TB's swagger.yaml is invalid.

https://cloud-barista.github.io/cb-tumblebug-api-web/?url=https://raw.githubusercontent.com/cloud-barista/cb-tumblebug/master/src/docs/swagger.yaml
![image](https://user-images.githubusercontent.com/46767780/115330471-135b8800-a1cf-11eb-8681-3ea85c5bb8f8.png)
https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fraw.githubusercontent.com%2Fcloud-barista%2Fcb-tumblebug%2Fmaster%2Fsrc%2Fdocs%2Fswagger.yaml

```JSON
{
  "messages": [
    "attribute paths.'/ns/{nsId}/monitoring/install/mcis/{mcisId}'. Declared path parameter mcisId needs to be defined as a path parameter in path or operation level",
    "attribute paths.'/ns/{nsId}/monitoring/mcis/{mcisId}/metric/{metric}'. Declared path parameter mcisId needs to be defined as a path parameter in path or operation level",
    "attribute paths.'/ns/{nsId}/monitoring/mcis/{mcisId}/metric/{metric}'. Declared path parameter metric needs to be defined as a path parameter in path or operation level",
    "attribute paths.'/ns/{nsId}/policy/mcis/{mcisId}'. Declared path parameter mcisId needs to be defined as a path parameter in path or operation level",
    "attribute paths.'/ns/{nsId}/resources/searchImage'. Declared path parameter nsId needs to be defined as a path parameter in path or operation level",
    "attribute paths.'/ns/{nsId}/resources/spec/{specId}'. Declared path parameter nsId needs to be defined as a path parameter in path or operation level",
    "attribute paths.'/ns/{nsId}/resources/spec/{specId}'. Declared path parameter specId needs to be defined as a path parameter in path or operation level"
  ]
}
```

**What you expected to happen**
: 
Swagger validator says TB's swagger.yaml is valid.

**How to reproduce it (as minimally and precisely as possible)**
: 
- Visit https://cloud-barista.github.io/cb-tumblebug-api-web/?url=https://raw.githubusercontent.com/cloud-barista/cb-tumblebug/master/src/docs/swagger.yaml
- Visit https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fraw.githubusercontent.com%2Fcloud-barista%2Fcb-tumblebug%2Fmaster%2Fsrc%2Fdocs%2Fswagger.yaml

**Anything else we need to know?**
: 

**Environment**
- Source version or branch: 
- OS: 
- Others: 

**Proposed solution**
: 

**Any other context**
:

**Comment by seokho-son** [comment]
![image](https://user-images.githubusercontent.com/5966944/116775789-eb5a0780-aa9f-11eb-84c8-0d58208a032a.png)

@jihoon-seo 실제로 잘못된 API 명세가 포함되어 있었어요~~
