### ISSUE TITLE
What is near USE: syntax error

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#487]
TB 실행시 발생하는 `near "USE": syntax error` 는 무었인가요?

```
Database access info set successfully
near "USE": syntax error
near "USE": syntax error
Table spec created successfully..
Table image created successfully..
```

`err = common.SelectDatabase(common.DB_DATABASE)`

**Comment by jihoon-seo** [comment]
`src/main.go` 의 `main()` 함수가 실행되면
다음 과정이 수행됩니다.

1. `OpenSQL("../meta_db/dat/cbtumblebug.s3db")`
2. `SelectDatabase(common.DB_DATABASE)`
   - SQL query: `USE cb_tumblebug;`
3. `CreateSpecTable()`
4. `CreateImageTable()`

SQLite 에서는 `USE cb_tumblebug;` 구문을 실행할 필요가 없는데
코드에 들어 있었습니다. 😢

해당 부분은 주석 처리 하겠습니다. 😊
