### ISSUE TITLE
Broken API documentation link

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-tumblebug#510]
릴리즈 페이지 (https://github.com/cloud-barista/cb-tumblebug/releases/tag/v0.3.0-espresso) 에 나오는 API Documentation 관련 링크가 끊겼으니 확인 부탁드립니다.
* Broken Link: https://cloud-barista.github.io/cb-tumblebug-api-web/?url=https://raw.githubusercontent.com/cloud-barista/cb-tumblebug/master/src/docs/tbapi-0.3.0.yaml

**Comment by jihoon-seo** [comment]
해당 링크가 https://cloud-barista.github.io/cb-tumblebug-api-web/?url=https://raw.githubusercontent.com/cloud-barista/cb-tumblebug/master/src/docs/v0.3.0.yaml 으로 수정되었습니다. 😊

다른 곳에 더 있는지 확인해 볼 수도 있겠네요.

**Comment by jihoon-seo** [comment]
https://github.com/cloud-barista/docs/blob/master/technical_docs/API/CB-User_REST-API.md#%EB%A9%80%ED%8B%B0-%ED%81%B4%EB%9D%BC%EC%9A%B0%EB%93%9C-%EC%9D%B8%ED%94%84%EB%9D%BC-%EC%84%9C%EB%B9%84%EC%8A%A4-%ED%86%B5%ED%95%A9-%EA%B4%80%EB%A6%AC-cb-tumblebug

업데이트 하겠습니다~~
