### ISSUE TITLE
bbolt issue in cb-tumblebug source-based installation

### ISSUE THREAD

**Issue by hermitkim1** [cloud-barista/cb-tumblebug#533]
### [Issue]
1. Run `go get -v github.com/cloud-barista/cb-tumblebug` for source-based installation
2. Encounter the issue below
```bash
root@DESKTOP-L3ETGKI:~# go get -v github.com/cloud-barista/cb-tumblebug
go get: github.com/cloud-barista/cb-tumblebug@v0.2.0-cappuccino updating to
        github.com/cloud-barista/cb-tumblebug@v0.3.6 requires
        github.com/cloud-barista/cb-spider@v0.3.0-espresso requires
        github.com/coreos/bbolt@v1.3.4: parsing go.mod:
        module declares its path as: go.etcd.io/bbolt
                but was required as: github.com/coreos/bbolt
```

### [Question]
Is it necessary to uncomment the blow line?
https://github.com/cloud-barista/cb-tumblebug/blob/b3f5c3099f78c1faebbeba93cf502968c5643d59/go.mod#L6

Ref: https://github.com/cloud-barista/cb-tumblebug/pull/115#issuecomment-615056661

**Comment by jihoon-seo** [comment]
[TB v0.3.6 의 `go.mod`](https://github.com/cloud-barista/cb-tumblebug/blob/v0.3.6/go.mod) 에는
```
	github.com/cloud-barista/cb-log v0.3.1
	github.com/cloud-barista/cb-spider v0.3.0-espresso
	github.com/cloud-barista/cb-store v0.3.2
```

이렇게 되어 있네용.. (옛날 버전들 이에요)

---

[최신 `go.mod`](https://github.com/cloud-barista/cb-tumblebug/blob/master/go.mod) 에는
```
	github.com/cloud-barista/cb-log v0.3.1
	github.com/cloud-barista/cb-spider v0.3.13
	github.com/cloud-barista/cb-store v0.3.14
```
이렇게 되어 있긴 한데..
저 에러가 동일하게 발생할지 발생하지 않을지는 모르겠네용..

---

README.md 에 적혀 있는 CB-Tumblebug 소스코드 다운로드 방법을
더 적합한 것으로 교체했습니다~~ (#534)
