### ISSUE TITLE
Runtime error occurred while `GetVmStatus()`

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#541]
**What happened**
: 
Runtime error occurred while `GetVmStatus()`.
```
[GetVmStatus]/ns/ns-01/mcis/mzc01-import/vm/mzc01-w-3-a1krn
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xef3b99]

goroutine 6026 [running]:
github.com/cloud-barista/cb-tumblebug/src/core/mcis.GetVmStatus(0xc00129c012, 0x5, 0xc000b3ae7f, 0x5, 0xc00012d740, 0x2e, 0x0, 0x0, 0x0, 0x0, ...)
        /root/cb-tumblebug/src/core/mcis/control.go:3827 +0x2b9
github.com/cloud-barista/cb-tumblebug/src/core/mcis.GetVmStatusAsync(0xc0000425c4, 0xc00129c012, 0x5, 0xc000b3ae7f, 0x5, 0xc00012d740, 0x2e, 0xc000edc2c0, 0x0, 0x0)
        /root/cb-tumblebug/src/core/mcis/control.go:3804 +0xe8
created by github.com/cloud-barista/cb-tumblebug/src/core/mcis.GetMcisStatus
        /root/cb-tumblebug/src/core/mcis/control.go:3679 +0x7bf
```

1. `GetMcisStatus()` 함수가 호출됨
2. `GetMcisStatus()` 함수가 `GetVmStatusAsync()` 함수를 호출
3. `GetVmStatusAsync()` 함수가 `GetVmStatus()` 함수를 호출
4. `GetVmStatus()` 함수의 3827번째 줄은 `fmt.Println(keyValue.Value)` 임.
   - `keyValue.Value` 가 nil 이라서 `invalid memory address or nil pointer dereference` 에러가 발생한 것일지..?

**What you expected to happen**
: 

**How to reproduce it (as minimally and precisely as possible)**
: 

**Anything else we need to know?**
: 

**Environment**
- Source version or branch: 
- OS: 
- Others: 

**Proposed solution**
: 

**Any other context**
:

**Comment by jihoon-seo** [comment]
Swagger UI 를 이용하여
다음을 테스트 해 보았지만
TB 강제종료 재현이 되지 않습니다.

[테스트 수행한 API]
- GET `/object`
- GET `/ns/{nsId}/mcis/{mcisId}/vm/{vmId}`
- GET `/ns/{nsId}/mcis/{mcisId}/vm/{vmId}` ?action=status

[테스트 수행한 object]
- `/ns/ns-01/mcis/mzc01-import/vm/mzc01-w-3-a1krn`
- `/ns/ns-01/mcis/mzc01-import/vm/mzc01-c-2-49ufn`
- `/ns/ns-01/mcis/mzc01/vm/mzc01-c-3-7zhex`
- ...

**Comment by jihoon-seo** [comment]
임시 조치:
`GetVmStatus` 함수에
```Golang
        defer func() {
                if runtimeErr := recover(); runtimeErr != nil {
                        common.CBLog.Error(runtimeErr)
                }
        }()
```
구문을 넣고
다시 컴파일하고 실행했습니다.
재현이 되는지 좀 더 살펴보겠습니다.

(위의 코드를 이 repo에는 아직 반영하지 않았습니다.)

**Comment by seokho-son** [comment]
https://github.com/cloud-barista/cb-tumblebug/pull/553#issuecomment-849309770
와 관련된 사안이려나요?

**Comment by jihoon-seo** [comment]
네 맞습니다.
이 이슈는 close 하겠습니다. 😊
