### ISSUE TITLE
Change all Korean comments inside source code into English

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#566]
**What would you like to be enhanced**
: Source code include some Korean language.

**Why is this needed**
: Not recommended way for internationalization.

**Proposed solution**
: Change all Korean comments inside source code into English. Guide developers to avoid using Korean in source code and commit message.

Tasks to resolve this issue partially.

Apply 

```bash
sed -i 's/CCM API 설정/Set CCM gRPC API/g' file.go
```
to tasks

1. - [x] https://github.com/cloud-barista/cb-tumblebug/blob/main/src/core/mcir/common.go
2. - [x] https://github.com/cloud-barista/cb-tumblebug/blob/main/src/core/mcir/image.go
3. - [x] https://github.com/cloud-barista/cb-tumblebug/blob/main/src/core/mcir/securitygroup.go
4. - [x] https://github.com/cloud-barista/cb-tumblebug/blob/main/src/core/mcir/spec.go
5. - [x] https://github.com/cloud-barista/cb-tumblebug/blob/main/src/core/mcir/sshkey.go
6. - [x] https://github.com/cloud-barista/cb-tumblebug/blob/main/src/core/mcis/control.go

**Comment by seokho-son** [comment]
Cf) @jihoon-seo 

`[^\x00-\x7F]+` 한글 코멘트 검색을 위한 정규식 (완벽하진 않아요)

VS Code에서 정규식으로 cb-tumblebug/src 를 검색하면~~

한.. 3000천개쯤 나오네요 ㅎㅎ

**Comment by seokho-son** [comment]
`.*[ㄱ-ㅎㅏ-ㅣ가-힣]+.*` 이게 낫네요 ^^
이렇게 하면 469개가 검색되는군용.

**Comment by seokho-son** [comment]
Tasks to resolve this issue partially.

Apply 

```bash
sed -i 's/CCM API 설정/Set CCM gRPC API/g' file.go
```
to tasks

- [ ] https://github.com/cloud-barista/cb-tumblebug/blob/main/src/core/mcir/common.go
- [ ] https://github.com/cloud-barista/cb-tumblebug/blob/main/src/core/mcir/image.go
- [ ] https://github.com/cloud-barista/cb-tumblebug/blob/main/src/core/mcir/securitygroup.go
- [ ] https://github.com/cloud-barista/cb-tumblebug/blob/main/src/core/mcir/spec.go
- [ ] https://github.com/cloud-barista/cb-tumblebug/blob/main/src/core/mcir/sshkey.go
- [ ] https://github.com/cloud-barista/cb-tumblebug/blob/main/src/core/mcis/control.go

**Comment by jangh-lee** [comment]
@seokho-son  2번 제가 해보고 싶습니다!

**Comment by limsg1234** [comment]
@seokho-son 안녕하세요. 4번 task 해보고 싶습니다.

**Comment by gbnam** [comment]
5번 해보고싶습니다

**Comment by seokho-son** [comment]
1. - [ ] https://github.com/cloud-barista/cb-tumblebug/blob/main/src/core/mcir/common.go // assigned to @seokho-son 
2. - [ ] https://github.com/cloud-barista/cb-tumblebug/blob/main/src/core/mcir/image.go // assigned to @jangh-lee  
3. - [ ] https://github.com/cloud-barista/cb-tumblebug/blob/main/src/core/mcir/securitygroup.go 
4. - [ ] https://github.com/cloud-barista/cb-tumblebug/blob/main/src/core/mcir/spec.go // assigned to @limsg1234 
5. - [ ] https://github.com/cloud-barista/cb-tumblebug/blob/main/src/core/mcir/sshkey.go // assigned to @gbnam 
6. - [ ] https://github.com/cloud-barista/cb-tumblebug/blob/main/src/core/mcis/control.go
