### ISSUE TITLE
Patch gRPC codes for updated fetchImages and fetchSpecs functions

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#569]
@jihoon-seo 

```
[이 PR에서 업데이트 하지 않은 것]

gRPC 서버 코드
Go (gRPC) client library 코드
cbadm 코드
```

요건 어떻게 정리하고 가면 좋을까요?

_Originally posted by @seokho-son in https://github.com/cloud-barista/cb-tumblebug/issues/567#issuecomment-850140407_

**Comment by jihoon-seo** [comment]
[Ref]
- PR #237 Add gRPC codes for new core functions
- PR #338 Add gRPC codes for new functions
