### ISSUE TITLE
Update README 

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#584]
**What would you like to be enhanced**
: v0.4.0에 앞서, Readme 현행화 필요 (사용 방법 등)

**Comment by jihoon-seo** [comment]
Suggested by @seokho-son :
- `README.md` 에, 동작 테스트 한 CB-Spider, CB-Dragonfly 의 버전을 명시
- "Prepare pre-release" 작업 시, `README.md` 의 해당 부분도 업데이트
