### ISSUE TITLE
`DelConfig()` is missing

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#587]
**What happened**
: 
`DelConfig()` is missing.

![image](https://user-images.githubusercontent.com/46767780/121157227-54ddea80-c884-11eb-8aa6-0eb9d7104b25.png)

**What you expected to happen**
: 

**How to reproduce it (as minimally and precisely as possible)**
: 

**Anything else we need to know?**
: 

**Environment**
- Source version or branch: 
- OS: 
- Others: 

**Proposed solution**
: 
- Add `DelConfig()`-related codes to
  - core
  - REST
  - gRPC

**Any other context**
:

**Comment by seokho-son** [comment]
음.. 요건 추가가 필요할지 고민이 좀 되네요. (사실 delete all conf 는 개발용이었어요^^;)
conf 는 아마도 삭제하면 system에 문제 발생 가능성이 있어서.. 
update 나 initialize 정도로 구분해두면 어떨까 싶기도 합니다.

**Comment by jihoon-seo** [comment]
@seokho-son 님과 논의하였습니다.

-> `DelConfig()` 를 대체하는 `InitConfig()` 의 예상 로직

- Delete config object
- Read system env var
- Update TB's global variable
