### ISSUE TITLE
Config without id/name can be created

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#588]
**What happened & How to reproduce it (as minimally and precisely as possible)**
: 
```
cd ~/go/src/github.com/cloud-barista/cb-tumblebug/src/testclient/scripts/2.configureTumblebug
./update-config.sh
./list-config.sh
```

```
####################################################################
## 0. Config: List
####################################################################
{
  "config": [
    {
      "id": "",
      "name": "",
      "value": ""
    }
  ]
}
```

**What you expected to happen**
: 
'Update config' 실행 시, `name` 이 명시되지 않으면 에러를 리턴함

**Anything else we need to know?**
: 

**Environment**
- Source version or branch: 
- OS: 
- Others: 

**Proposed solution**
: 
'Update config' 코드에 `name` 체크하는 로직 추가

**Any other context**
:

**Comment by seokho-son** [comment]
@jihoon-seo 이 config의 경우, 시스템 env 셋팅을 위한 것이어서
현재 setup.env 에 있는 env variable 에 해당하는 값이 name으로 들어갑니다. (내부적으로는 모두 소문자로 변경해서 비교 처리했던 것 같습니다) 참고하시기 바랍니다..^^

**Comment by jihoon-seo** [comment]
@seokho-son 네 맞습니다.
그런데, #527 에서, config 들에 대해서는 string 정제를 하지 않고 사용하는 것으로 변경했었습니다.

곧 올릴 PR을 통해, 이 이슈를 해결하겠습니다. 😊
