### ISSUE TITLE
Term: `vNet` -> `vpc`

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#591]
**What would you like to be enhanced**
: 
Term: `vNet` -> `vpc`

**Why is this needed**
: 
Many CSPs have been adopting the term "VPC".

**Proposed solution**
:

**Comment by seokho-son** [comment]
향후에 논의 및 결정 후에 추진하도록 하겠습니다.. ^^

**Comment by jihoon-seo** [comment]
FYI: CB-Tumblebug 팀에서 2019년 9월 17일에 검토 후 작성한 자료
https://docs.google.com/presentation/d/1gj-Vlhmxzf1hc8WZvbX8C4gYWbu7Ql6Aj_bjgd9iPU4/edit?usp=sharing

**Comment by jihoon-seo** [comment]
By @seokho-son on 2021-06-09:

회의에서 잠시 이슈된 VNET 용어(현재 CB-TB의 Network 오브젝트 명칭 / webtool에서 사용되는 명칭) 에 대해서, 

CSP에서 사용하고 있는 용어를 파악해보았습니다. 향후 결정에 참고하시기 바랍니다.

* 참고: VPC (Virtual Private Cloud)
•	AWS: VPC (VM 생성 화면에서는 그냥 Network으로 표기)
•	AZURE: VNET (Vritual Network)
•	Alibaba: VPC
•	GCP: VPC Network (VPC 자체가 네트워크를 의미하지 않는 것으로 보이며, 네트워크 서비스에 가까운 의미로 보입니다.)
•	Openstack: Virtual Network

[CB-TB 의견]
•	VPC가 더 트렌디한 용어로 보여집니다.
•	그러나 기존의 VNET(virtual network) 가 조금 더 일반화된 CSP 중립적인 용어로 보입니다.

**Comment by seokho-son** [comment]
ref (Spider): https://github.com/cloud-barista/cb-spider/issues/401

**Comment by jihoon-seo** [comment]
https://www.sosconhistory.net/soscon2019/content/data/session/Day%202_1330_2.pdf
OpenStack: **가상 네트워크** (테넌트 네트워크) 기능은 있으나
**VPC** (Virtual Private Cloud) 는 아직 없는 기능임 / 아이디어 제안 상태 (Blueprint)
https://wiki.openstack.org/wiki/Blueprint-VPC

**Comment by seokho-son** [comment]
AWS 스타일의 VPC API를 내어주고 싶은가보군요

**Comment by seokho-son** [comment]
해당 이슈는 close 해도 될 것 같습니다.

향후 변경 의견이 있으면, 해당 이슈를 다시 오픈하여 활용하면 되겠습니다.
