### ISSUE TITLE
Error can occur in using `ListVmId`

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#599]
- Related issues:
  - #546 (`ListVmId` returns not-prefix-trimmed vmID)
  - #576 (Malformed 'vmId' could be set)

**What happened**
: 

`/ns/ns-01/mcis/mock-seoul-jhseo1/vm/mock-seoul-jhseo1-0` 라는 자원들이 있는 상태에서

[올바른 조회]
```
❯ ./id-list-vm.sh mock 1 jhseo1
####################################################################
## 8. VM: List ID
####################################################################
mock-seoul-jhseo1
{
  "idList": [
    "mock-seoul-jhseo1-0"
  ]
}
```

[올바르지 않은 조회]
```
❯ ./id-list-vm.sh mock 1 jhseo
####################################################################
## 8. VM: List ID
####################################################################
mock-seoul-jhseo
{
  "idList": [
    "/ns/ns-01/mcis/mock-seoul-jhseo1/vm/mock-seoul-jhseo1-0"
  ]
}
```
-> Not found 가 나와야 정상인데,
조회되지 않아야 하는 자원이 조회되고,
VM ID 만 출력하는 것이 아니라 Key-Value store 의 Key 전체가 출력됨

Key-Value store 사용상의 이슈로 추정됨

**What you expected to happen**
: 

**How to reproduce it (as minimally and precisely as possible)**
: 

**Anything else we need to know?**
: 

**Environment**
- Source version or branch: 
- OS: 
- Others: 

**Proposed solution**
: 

**Any other context**
:

**Comment by powerkimhub** [comment]
@jihoon-seo 

cb-store가 제공하는 API 기능은 다음과 같습니다. 

- cb-sore: GetList("/xxx")
  - "/xxx"를 prefix로(앞에서부터) 만족하는(포함하는) 모든 키 fetch
    - 기능으로 보면, API 이름이 GetList보다는 PrefixFind 등이 적합하긴 하네요
 - cb-store: Get(/xxx")
   -  "/xxx" 동일한 키만 fetch
 
- 위와 같은 의도의 기능은
  - GetList()와 Get()을 조합하면 될듯합니다.

**Comment by seokho-son** [comment]
@jihoon-seo 오류 분석 완료하였습니다.

```
keyValue, err := common.CBStore.GetList(key, true) 
```
로 조회 후,

아래와 같이, 리스트를 정리하는데,
```
	for _, v := range keyValue {
		if strings.Contains(v.Key, "/vm/") {
			vmList = append(vmList, strings.TrimPrefix(v.Key, (key+"/vm/")))
		}
	}
```	

오류가 발생할 수 있는 상황이 보이네요.


mcis 이름으로 key 조회를 하면, 관련 mcis 에 대한 key 들만 나올 것이라고 봤으나,

예를 들어,
조회하는 mcis 가 `m-ali-is` 이고

`m-ali-is-expert`, `m-ali-is` 이름에 prefix 관계가 있는 2개의 mcis가 있는 상황이라면,

CBStore.GetList 를 했을 때, 아래와 같이 리스트가 조회되고,

```
{
  "object": [
    "/ns/mz-cbweb99/mcis/m-ali-is",
    "/ns/mz-cbweb99/mcis/m-ali-is-expert",
    "/ns/mz-cbweb99/mcis/m-ali-is-expert/vm/m-ali-is-server-expert",
    "/ns/mz-cbweb99/mcis/m-ali-is/vm/m-ali-is-server"
  ]
}
```

여기서 vm 리스트를 뽑아내기 위해서
`/vm/` 이 포함된 조건만 보게 되면.

(중간) 결과적으로
- /ns/mz-cbweb99/mcis/m-ali-is/vm/m-ali-is-server (정상적인 vm key)
- /ns/mz-cbweb99/mcis/m-ali-is-expert/vm/m-ali-is-server-expert (적합하지 않은 vm key)

가 포함됩니다.

그리고 /vm/을 기준으로 trim을 하게 되는데,
/ns/mz-cbweb99/mcis/m-ali-is`/vm/` 는 문제 없이 trim이 되어 `m-ali-is-server` 를 뽑아내게 되고

/ns/mz-cbweb99/mcis/m-ali-is`-expert/vm/`m-ali-is-server-expert 는 /vm/으로 시작 하지 않아서 trim이 정상적으로 되지 않을 것 입니다. 사용하는 `strings.TrimPrefix()` 함수를 보니,
정상적인 trim이 되지 않으면, 그냥 전체 값을 리턴하네요. 즉 `/ns/mz-cbweb99/mcis/m-ali-is-expert/vm/m-ali-is-server-expert` 를 통채로 리턴하게 되고,

```
func strings.TrimPrefix(s string, prefix string) string
strings.TrimPrefix on pkg.go.dev

TrimPrefix returns s without the provided leading prefix string. If s doesn't start with prefix, s is returned unchanged.
```

`/ns/mz-cbweb99/mcis/m-ali-is-expert/vm/m-ali-is-server-expert` 가 마치 vm의 id 처럼 인식하게 됩니다.

결과적으로
- /ns/mz-cbweb99/mcis/m-ali-is/vm/m-ali-is-server
- /ns/mz-cbweb99/mcis/m-ali-is/vm/`/ns/mz-cbweb99/mcis/m-ali-is-expert/vm/m-ali-is-server-expert`

가 만들어집니다.
