### ISSUE TITLE
Enhance source code tree and names

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#60]
Let's enhance source code tree and names.

I suggest as follows,
cb-tumblebug/
----------------/README.md
----------------config/
------------------------setup.env
------------------------log_conf.yaml
------------------------store_conf.yaml
----------------doc/
----------------source/
------------------------apiserver.go (mcism_server.go)
------------------------common/
-----------------------------------utility.go (some common utilities in mcism_server.go)
-----------------------------------namespace.go (mcism_namespace.go)
------------------------mcir/
-------------------------------image.go (mcir_image.go)
-------------------------------spec.go (mcir_spec.go)
....
-------------------------------vnic.go (mcir_vnic.go)
------------------------mcism/
--------------------------------control.go (mcism_mcis.go)
--------------------------------(will be extende)

**Comment by jihoon-seo** [comment]
cb-tumblebug/
----------------/README.md
----------------config/
------------------------setup.env
------------------------log_conf.yaml
------------------------store_conf.yaml
----------------docs/
----------------src/
------------------------mcism.go (mcism_server.go)
------------------------common/
-----------------------------------utility.go (some common utilities in mcism_server.go)
-----------------------------------namespace.go (mcism_namespace.go)
------------------------mcir/
-------------------------------image.go (mcir_image.go)
-------------------------------spec.go (mcir_spec.go)
....
-------------------------------vnic.go (mcir_vnic.go)
------------------------mcis/
--------------------------------control.go (mcism_mcis.go)
--------------------------------(will be extended)

**Comment by jihoon-seo** [comment]
cb-tumblebug/
----------------/README.md
----------------conf/
------------------------setup.env
------------------------log_conf.yaml
------------------------store_conf.yaml
----------------docs/
----------------src/
------------------------apiserver/
-----------------------------------apiserver.go (mcism_server.go)
------------------------mcism.go (contains main() which calls apiserver())
------------------------common/
-----------------------------------utility.go (some common utilities in mcism_server.go)
-----------------------------------namespace.go (mcism_namespace.go)
------------------------mcir/
-------------------------------image.go (mcir_image.go)
-------------------------------spec.go (mcir_spec.go)
....
-------------------------------vnic.go (mcir_vnic.go)
-------------------------------utility.go
------------------------mcis/
--------------------------------control.go (mcism_mcis.go)
--------------------------------utility.go
--------------------------------(will be extended)
----------------test/
------------------------tester-go/
------------------------tester-sh/
