### ISSUE TITLE
Location of Swagger doc files

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#614]
**What would you like to be enhanced**
: 
Location of Swagger doc files

**Why is this needed**
: 
현재 Swagger docs 는 REST API 에 대해서만 제공되고 있음

**Proposed solution**
:
Move `cb-tumblebug/src/docs/` to one of these:
- `cb-tumblebug/src/api/rest/docs/`
- `cb-tumblebug/src/api/rest/swaggerDocs/`
- `cb-tumblebug/src/api/rest/server/docs/`
- `cb-tumblebug/src/api/rest/server/swaggerDocs/`

[영향을 미치기 때문에 추가로 변경해야 하는 곳들의 후보]
- https://github.com/cloud-barista/docs
- https://github.com/cloud-barista/cloud-barista.github.io
- https://github.com/cloud-barista/cb-tumblebug-api-web
- ...

**Comment by jihoon-seo** [comment]
[CB-Spider 의 사례]
[최근 PR](https://github.com/cloud-barista/cb-spider/pull/418) 에서, `cb-spider/api-runtime/rest-runtime/docs/` 에 위치시킴

[저의 제안]
저는 네 후보 중에서는 `cb-tumblebug/src/api/rest/swaggerDocs/` 가 어떨까 합니다. 😊

**Comment by seokho-son** [comment]
@jihoon-seo 현황 파악 감사합니다... ^^
위치를 옮긴다면

저는 "cb-tumblebug/src/api/rest/docs/" 가 어떨까 싶네요.
swagger가 꼭 디렉토리 명칭에서 드러날 필요는 없을 것같다는 생각입니다.

디렉토리 path상 api + rest + docs  를 읽으면, REST API 문서. 로 보이니 괜찮을 것같기도 합니다..^^
