### ISSUE TITLE
Dragonfly-calling method (REST/gRPC)

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#643]
**What would you like to be added**
: 

**Why is this needed**
:

Ref: Spider-calling method in Tumblebug

**Comment by seokho-son** [comment]
@jihoon-seo 이 issue 는 close 해도 될까요?

**Comment by jihoon-seo** [comment]
@seokho-son 
관련하여 #671 ("TB -> DF gRPC 호출 시, DF endpoint 설정 방법 관련") 에서 논의가 있었으며,
gRPC 관련 개발은 2022년 이후로 미루어졌으므로
일단 close 해도 될 것 같습니다. 😊
