### ISSUE TITLE
Easy setting of cb-tb development env

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#650]
**What would you like to be enhanced**
: CB-TB 활용 및 개발 환경 구성 과정을 쉽고 간편하게 개선

**Why is this needed**
: MCIS 생성을 위한 기본 환경 구성 단계가, 신규 사용자 및 기여자의 진입 장벽이 되고 있음

**Proposed solution**
- [x] 기반 FW 구동 스크립트 제공 및 설정 간소화
- [ ] 클라우드 크리덴셜 등록 과정 간소화 (환경 설정 형태로 제공)

**Comment by seokho-son** [comment]
@jihoon-seo task "기반 FW 구동 스크립트 제공 및 설정 간소화" 관련하여, 
CB-TB 기여자들이 쉽게 CB-Spider 사용 환경을 구성(CB-TB와 연동되는 버전이 지정된 docker image 실행)할 수 있도록 
실행 Script를 하나 구성하면 어떨까요? (메뉴얼하게 알려주는 것이 더 좋을까요?)

**Comment by jihoon-seo** [comment]
"클라우드 크리덴셜 등록 과정 간소화 (환경 설정 형태로 제공)" 관련:

CB-Ladybug의 테스트 스크립트 중

[[파일에서 클라우드별 연결정보 얻기](https://github.com/cloud-barista/cb-ladybug/tree/master/docs/test#파일에서-클라우드별-연결정보-얻기)]
[[cb-ladybug/docs/test/env.sh](https://github.com/cloud-barista/cb-ladybug/blob/master/docs/test/env.sh)]

* GCP ( [jq](https://stedolan.github.io/jq/) 설치 필요)

```
$ source ./env.sh GCP "<json file path>"

# 예
$ source ./env.sh GCP "${HOME}/.ssh/google-credential-cloudbarista.json"
```

* AWS
```
$ source ./env.sh AWS "<credentials file path>"

# 예
$ source ./env.sh AWS "${HOME}/.aws/credentials"

# '${HOME}/.aws/credentials' file format which is created by awscli
$ cat ${HOME}/.aws/credentials
[default]
aws_secret_access_key = y7Ganz6A.................................
aws_access_key_id = AKIA2Z........................
```

GCP credential file에서
정보들을 뽑아서
`PROJECT`, `PKEY`, `SA` 환경변수에 저장하거나

AWS credential file에서
정보들을 뽑아서
`KEY`, `SECRET` 환경변수에 저장하는 스크립트입니다.

---

이후, CB-Ladybug의 테스트 스크립트 중 [connectioninfo-create.sh](https://github.com/cloud-barista/cb-ladybug/blob/master/docs/test/connectioninfo-create.sh) 를 실행하면
위의 환경변수에 저장된 값을 이용하여 CB-Spider에 등록합니다.

---

참고가 될 수도 있겠습니다.
