### ISSUE TITLE
Add English Readme.md for CB-TB

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#655]
**What would you like to be enhanced**
: Readme 제공 언어 개선

**Why is this needed**
: CB-TB의 국제화 및 국제 협업을 위해 영문 제공 필요

**Proposed solution**
: 한글 Readme.md 번역을 통한 영문 Readme.md 파일 생성

Tasks (contributors can take a task individually)
1. [x] cb-tumblebug/i18n 디렉토리 생성 및 README-EN.md 파일 생성
2. [x] cb-tumblebug/README.md 를 수정하여, README-EN.md 링크 제공 (WIP를 표시)
3. [x] README.md 내용을 영문으로 번역하여 README-EN.md 파일 업데이트 
4. [x] README.md 에 영문 README의 WIP 표기를 삭제

**Comment by ChobobDev** [comment]
제가  `cb-tumblebug/i18n 디렉토리 생성 및 README-EN.md 파일 생성` task에 기여해 보도록 하겠습니다.

**Comment by seokho-son** [comment]
감사합니다!! 
Tasks (contributors can take a task individually)
1. [x] cb-tumblebug/i18n 디렉토리 생성 및 README-EN.md 파일 생성 [@ChobobDev] 
2. [x] cb-tumblebug/README.md 를 수정하여, README-EN.md 링크 제공 (WIP를 표시) [@ChobobDev]
3. [ ] README.md 내용을 영문으로 번역하여 README-EN.md 파일 업데이트 
4. [ ] README.md 에 영문 README의 WIP 표기를 삭제

**Comment by ChobobDev** [comment]
I will work on the rest of the task for this issue.
제가 나머지 task들도 해보겠습니다.

Thank you
감사합니다.

**Comment by ChobobDev** [comment]
Should I one PR when I am done with translation or is it okay for me to PR and keep working on translation.

번역을 다 마친후에 한번에 PR을 하는게 좋을까요 아니면 task 1 & task 2 만 우선적으로 PR을 올린 후 다시 PR을 올릴까요?

**Comment by seokho-son** [comment]
@ChobobDev 독립적으로 올려주시는 것이 더 좋을 것 같습니다!! :)
