### ISSUE TITLE
Fix some REST API's HTTP methods

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#674]
**What happened**
: 
Some REST API's HTTP methods are inappropriate.

**What you expected to happen**
: 

**How to reproduce it (as minimally and precisely as possible)**
: 

**Anything else we need to know?**
: 

**Environment**
- Source version or branch: 
- OS: 
- Others: 

**Proposed solution**
: 

`cb-tumblebug/src/api/rest/server/server.go`

```diff
-	g.POST("/:nsId/resources/filterSpecs", rest_mcir.RestFilterSpecs)
-	g.POST("/:nsId/resources/filterSpecsByRange", rest_mcir.RestFilterSpecsByRange)
-	g.POST("/:nsId/resources/testSortSpecs", rest_mcir.RestTestSortSpecs)
-
-	g.POST("/:nsId/resources/searchImage", rest_mcir.RestSearchImage)

+	g.GET("/:nsId/resources/filterSpecs", rest_mcir.RestFilterSpecs)
+	g.GET("/:nsId/resources/filterSpecsByRange", rest_mcir.RestFilterSpecsByRange)
+	g.GET("/:nsId/resources/testSortSpecs", rest_mcir.RestTestSortSpecs)
+
+	g.GET("/:nsId/resources/searchImage", rest_mcir.RestSearchImage)
```

In addition, related Swagger annotations also need to be updated.

`cb-tumblebug/src/api/rest/server/mcir/spec.go`

```diff
-// @Router /ns/{nsId}/resources/filterSpecs [post]
+// @Router /ns/{nsId}/resources/filterSpecs [get]
```

\+ Swagger doc 파일도 re-generate 하시면 좋습니다.
다만 첫 기여자께서 Swagger doc 파일 업데이트가 어려우시다면
이 부분은 빼고 PR을 올려 주시면
CB-Tumblebug 메인테이너가 추후에 별도의 PR에서 Swagger doc 파일을 업데이트하는 것도 가능합니다. 😊

\+ 만약 cb-webtool 에서 해당 REST API 를 활용중이었다면,
cb-webtool 에서 CB-Tumblebug 을 호출하는 부분의
HTTP method 도 업데이트가 필요합니다.

**Any other context**
:

**Comment by seokho-son** [comment]
@jihoon-seo 
혹시 해당 REST method는 Swagger API 에서 Body가 있는 GET method를 허용하지 않아서, 
의도적으로 POST method로 지정한 것은 아닌가요? ^^
ref: https://github.com/cloud-barista/cb-tumblebug/discussions/502

**Comment by jihoon-seo** [comment]
@seokho-son 맞네요.. 깜빡했습니다 😢

**Comment by jihoon-seo** [comment]
다음 REST API는 호출할 때 JSON body를 적어야 하는데 GET method로 되어 있습니다.

`cb-tumblebug/src/api/rest/server/server.go`
```Go
e.GET("/tumblebug/lookupSpec", rest_mcir.RestLookupSpec)

e.GET("/tumblebug/lookupImage", rest_mcir.RestLookupImage)
```

`cb-tumblebug/src/api/rest/server/mcir/spec.go`
```Go
// Request structure for RestLookupSpec
type RestLookupSpecRequest struct {
	ConnectionName string `json:"connectionName"`
	CspSpecName    string `json:"cspSpecName"`
}

// RestLookupSpec godoc
// @Summary Lookup spec
// @Description Lookup spec
// @Tags [Admin] Cloud environment management
// @Accept  json
// @Produce  json
// @Param lookupSpecReq body RestLookupSpecRequest true "Specify connectionName & cspSpecName"
// @Success 200 {object} mcir.SpiderSpecInfo
// @Failure 404 {object} common.SimpleMsg
// @Failure 500 {object} common.SimpleMsg
// @Router /lookupSpec [get]
func RestLookupSpec(c echo.Context) error {
	u := &RestLookupSpecRequest{}
	if err := c.Bind(u); err != nil {
		return err
	}

	fmt.Println("[Lookup spec]: " + u.CspSpecName)
	content, err := mcir.LookupSpec(u.ConnectionName, u.CspSpecName)
	if err != nil {
		common.CBLog.Error(err)
		return c.JSONBlob(http.StatusNotFound, []byte(err.Error()))
	}

	return c.JSON(http.StatusOK, &content)

}
```

`cb-tumblebug/src/api/rest/server/mcir/image.go`
```Go
// Request structure for RestLookupImage
type RestLookupImageRequest struct {
	ConnectionName string `json:"connectionName"`
	CspImageId     string `json:"cspImageId"`
}

// RestLookupImage godoc
// @Summary Lookup image
// @Description Lookup image
// @Tags [Admin] Cloud environment management
// @Accept  json
// @Produce  json
// @Param lookupImageReq body RestLookupImageRequest true "Specify connectionName & cspImageId"
// @Success 200 {object} mcir.SpiderImageInfo
// @Failure 404 {object} common.SimpleMsg
// @Failure 500 {object} common.SimpleMsg
// @Router /lookupImage [get]
func RestLookupImage(c echo.Context) error {

	u := &RestLookupImageRequest{}
	if err := c.Bind(u); err != nil {
		return err
	}

	fmt.Println("[Lookup image]: " + u.CspImageId)
	content, err := mcir.LookupImage(u.ConnectionName, u.CspImageId)
	if err != nil {
		common.CBLog.Error(err)
		return c.JSONBlob(http.StatusNotFound, []byte(err.Error()))
	}

	return c.JSON(http.StatusOK, &content)

}
```

**Comment by atg0831** [comment]
@jihoon-seo 
Request에 body 값을 넣어서 REST API를 호출하기 위해서 method를 `e.GET` 에서 `e.POST` 로 변경하라는 뜻으로
이해했는데 혹시 맞을까요?

**Comment by seokho-son** [comment]
@atg0831 환영합니다.. ^0^
@jihoon-seo 신규 기여자를 위해, 해당 이슈에 대해서 조금 상세하게 가이드 부탁 드려도 될까요? ^^

**Comment by jihoon-seo** [comment]
@atg0831 안녕하세요~~
> Request에 body 값을 넣어서 REST API를 호출하기 위해서 method를 `e.GET` 에서 `e.POST` 로 변경

네 맞습니다.
관련 이력, 내용 및 논의는 #502 (How to handle `GET method` with body param in CB-TB API) 를 참고하시면 되겠습니다. 😊

HTTP method를 GET 에서 POST 로 바꾼다면, 함께 변경해야 하는 부분은 다음과 같습니다.
1. Go annotation for Swagger doc
   - https://github.com/cloud-barista/cb-tumblebug/blob/69ba857cb522e220f42b58f102a28201e9324368/src/api/rest/server/mcir/image.go#L110
   - https://github.com/cloud-barista/cb-tumblebug/blob/69ba857cb522e220f42b58f102a28201e9324368/src/api/rest/server/mcir/image.go#L139
   - https://github.com/cloud-barista/cb-tumblebug/blob/69ba857cb522e220f42b58f102a28201e9324368/src/api/rest/server/mcir/spec.go#L129
   - https://github.com/cloud-barista/cb-tumblebug/blob/69ba857cb522e220f42b58f102a28201e9324368/src/api/rest/server/mcir/spec.go#L157
2. CB-Tumblebug test scripts for REST APIs
   - https://github.com/cloud-barista/cb-tumblebug/blob/69ba857cb522e220f42b58f102a28201e9324368/src/testclient/scripts/6.image/lookupImage.sh#L7
   - https://github.com/cloud-barista/cb-tumblebug/blob/69ba857cb522e220f42b58f102a28201e9324368/src/testclient/scripts/6.image/lookupImageList.sh#L7
   - https://github.com/cloud-barista/cb-tumblebug/blob/69ba857cb522e220f42b58f102a28201e9324368/src/testclient/scripts/7.spec/lookupSpec.sh#L7
   - https://github.com/cloud-barista/cb-tumblebug/blob/69ba857cb522e220f42b58f102a28201e9324368/src/testclient/scripts/7.spec/lookupSpecList.sh#L7

**Comment by atg0831** [comment]
@jihoon-seo 
설명해주신 이슈 가이드를 참고해서 수정해보겠습니다!

**Comment by seokho-son** [comment]
@atg0831 감사합니다!! ^^

[CB-TB 기여 가이드](https://github.com/cloud-barista/cb-tumblebug#2-%EA%B8%B0%EC%97%AC-%EA%B0%80%EC%9D%B4%EB%93%9C)에 

[CB-TB 기여자의 테스팅 준수 사항](https://github.com/cloud-barista/cb-tumblebug/wiki/Basic-testing-guide-before-a-contribution#cb-tb-%EA%B8%B0%EC%97%AC%EC%9E%90%EC%9D%98-%ED%85%8C%EC%8A%A4%ED%8C%85-%EC%A4%80%EC%88%98-%EC%82%AC%ED%95%AD)도 참고해주시길 부탁드립니다.. ^^

API를 수정하는 경우에는
https://github.com/cloud-barista/cb-tumblebug/wiki/API-Document-Update 에 대한 처리도 해주시면 더욱 좋습니다! ^^

살펴보시고 어려움이 있는 경우 편하게 문의 주세요~~
