### ISSUE TITLE
One file is not gofmt-ed

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#680]
- Related issue: #654
- Related issue: #678

**What would you like to be enhanced**
: 
gofmt a file:
[cb-tumblebug/src/api/grpc/request/test/test_api.go](https://github.com/cloud-barista/cb-tumblebug/blob/master/src/api/grpc/request/test/test_api.go)

**Why is this needed**
: 
[Go Report Card](https://goreportcard.com/report/github.com/cloud-barista/cb-tumblebug#gofmt) is saying:
> cb-tumblebug/src/api/grpc/request/test/test_api.go
Line 1: warning: file is not gofmted with -s (gofmt)

**Proposed solution**
:
gofmt that file and open a PR.

(e.g. Open that file with VScode (gofmt-enabled),
click "Save" (then gofmt will gofmt automatically),
and open a PR.)

**Comment by atg0831** [comment]
제가 gofmt으로 파일 저장하고 PR 요청해도 될까요?

**Comment by seokho-son** [comment]
물론입니다^^
