### ISSUE TITLE
Deprecate `cbadm` test scripts, and integrate into REST API test scripts

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#696]
**What would you like to be enhanced**
: 
Deprecate `cbadm` test scripts, and integrate into REST API test scripts

**Why is this needed**
: 
[REST API test scripts](https://github.com/cloud-barista/cb-tumblebug/tree/main/src/testclient/scripts)는 필요에 따라 계속 업데이트되고 있으나
[`cbadm` test scripts](https://github.com/cloud-barista/cb-tumblebug/tree/main/src/api/grpc/cbadm/testclient/scripts)는 그렇지 못함

**Proposed solution**
:
[CB-Ladybug 사례](https://github.com/cloud-barista/cb-ladybug/blob/master/docs/test/cluster-create.sh)를 참고하여
[REST API test scripts](https://github.com/cloud-barista/cb-tumblebug/tree/main/src/testclient/scripts)에
'REST API 호출' / '`cbadm` 실행' 의 분기를 추가

**Comment by jihoon-seo** [comment]
그런데, `cbadm`이 다른 경로 또는 다른 repo로 옮겨질 가능성도 있어서,
일단은 CB-Tumblebug REST API test scripts에 위의 사항을 반영하지 않는 것이 좋을 수도 있겠습니다.

**Comment by seokho-son** [comment]
1. https://github.com/cloud-barista/cb-tumblebug/tree/main/src/testclient/scripts

1. https://github.com/cloud-barista/cb-tumblebug/tree/main/src/api/grpc/cbadm/testclient/scripts

에 포함된 스크립트의 코드가 중복되어 있으며, 관리의 부담을 높이고 있는 것으로 보입니다. (관리 측면에서 여러번 이슈화됨)

사용 빈도와 cbadm이 별도 저장소로 분리되는 상황을 고려하여,

https://github.com/cloud-barista/cb-tumblebug/tree/main/src/api/grpc/cbadm/testclient/scripts 의 코드들은 삭제하고,

향후 참조 및 활용 가능성을 고려하여 해당 파일들이 포함된 커밋만 디스커션 또는 위키 등으로 옮겨두고자 합니다.

**Comment by seokho-son** [comment]
#1064
