### ISSUE TITLE
Adopt Go reflect package

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#700]
@seokho-son referred the Go reflect package. 😊

- 예제 코드: https://play.golang.org/p/CGzM28ibuk4
- 참고 글
  - https://johngrib.github.io/wiki/golang-reflect/
  - https://w.cublr.com/programming/go/golang-reflect/
- 관련 이슈 및 PR
  - #654
  - #684
  - #699

**What would you like to be enhanced**
: 
Adopt Go reflect package

**Why is this needed**
: 
`TbSpecInfo` struct의 필드 이름을 `string` 으로 조회하는 사례가 있음
https://github.com/cloud-barista/cb-tumblebug/blob/f509051deff6cf4c9e5684c8829a2f4ab0a36251/src/core/mcir/spec.go#L1025

**Proposed solution**
:
=> `const StrNumvCPU string = "numvCPU"` 와 같이 정의하고, reflect도 활용하는 방향으로 개선할 수 있음

**Comment by seokho-son** [comment]
예제 코드: https://play.golang.org/p/CGzM28ibuk4

좋네요.. ㅎㅎ

근데 이 예제로 활용하려면 json tag가 필요하려나요.

**Comment by jihoon-seo** [comment]
예제 코드에서
struct 정의를 다음과 같이 하니

```Go
type Person struct {
	Name   string //`json:"name"`
	Nation string `json:"country"`
	Zip    int    `json:"zipCode"`
}
```

json 태그는 empty 라서 출력되지 않는 것을 확인했습니다. 😊

```
Type: *main.Person
Name		string		==>		JohnGrib, json:           
Nation		string		==>		Korea, json:    country
Zip		int		==>		12345, json:    zipCode
```

**Comment by seokho-son** [comment]
이런거 사용하려면 결국 json tag 를 살려야 하는 걸까요.. ㅠㅠ

**Comment by jihoon-seo** [comment]
위의 예제에서는, struct field에 JSON tag가 명시되어 있지 않아서 JSON 태그가 출력되지 않은 것으로 보입니다.

---

JSON tag를 명시하지 않으면,
현재 CB-Spider가 동작하는 것과 같이
JSON marshal, unmarshal, bind 가 별 문제 없이 될 것으로 추측됩니다. 😊
(다만, 현재 TB 소스에서 각 struct field의 JSON 태그를 '첫글자를 소문자화 한 것' 으로 명시하고 있는데,
TB 소스에서 JSON tag를 삭제하면,
TB REST API call 시에 JSON field 첫글자를 소문자로 하여 호출하던 것이 계속 문제없이 동작할지
아니면 struct field 이름과 동일하게 첫글자를 대문자로 하여 호출해야 할지는 테스트가 필요합니다.)

**Comment by seokho-son** [comment]
- fixed by #1552
