### ISSUE TITLE
Adopt Structure Validation

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#706]
Ref:
- https://blog.billo.io/devposts/go_struct_validation/
- https://genius-kim-1047.tistory.com/59
- ...

**What would you like to be enhanced**
: 
Adopt Structure Validation

**Why is this needed**
: 

**Proposed solution**
:

**Comment by seokho-son** [comment]
@jihoon-seo 하나가 강조되어 있네요.. ? ㅋㅋ

**Comment by seokho-son** [comment]
> https://echo.labstack.com/guide/request/#validate-data
> Echo를 사용할 때, go-playground/validator를 활용하는 예시

좋네요.. ^^

**Comment by jihoon-seo** [comment]
[적용 현황]

- image: https://github.com/cloud-barista/cb-tumblebug/blob/9c8b00900e354a3f1134b2c4d461bae1347255ba/src/core/mcir/image.go#L131
- SG: https://github.com/cloud-barista/cb-tumblebug/blob/9c8b00900e354a3f1134b2c4d461bae1347255ba/src/core/mcir/securitygroup.go#L142
- spec: https://github.com/cloud-barista/cb-tumblebug/blob/9c8b00900e354a3f1134b2c4d461bae1347255ba/src/core/mcir/spec.go#L398
- SSH key: https://github.com/cloud-barista/cb-tumblebug/blob/9c8b00900e354a3f1134b2c4d461bae1347255ba/src/core/mcir/sshkey.go#L132
- vNet: https://github.com/cloud-barista/cb-tumblebug/blob/9c8b00900e354a3f1134b2c4d461bae1347255ba/src/core/mcir/vnet.go#L160
- subnet: https://github.com/cloud-barista/cb-tumblebug/blob/9c8b00900e354a3f1134b2c4d461bae1347255ba/src/core/mcir/subnet.go#L47

---

- MCIS:
  - https://github.com/cloud-barista/cb-tumblebug/blob/9c8b00900e354a3f1134b2c4d461bae1347255ba/src/core/mcis/provisioning.go#L517
  - https://github.com/cloud-barista/cb-tumblebug/blob/9c8b00900e354a3f1134b2c4d461bae1347255ba/src/core/mcis/provisioning.go#L705

일단은 모든 자원에 대해 적용되어 있는 것으로 보입니다. 😊

**Comment by seokho-son** [comment]
그럼 close 하겠습니다!!
