### ISSUE TITLE
Add AWS Osaka region (ap-northeast-3) to test configuration

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#713]
**What would you like to be enhanced**
New Asia Pacific (Osaka) has been added in AWS.
I hope to add a basic test configuration for this region for CB-Tumblebug testclient.

**Why is this needed**
We can use AWS Osaka region easily to generate multi-clouds IaaS infra with CB-Tumblebug testclient.

**Proposed solution**

 - [ ] Add a new test configuration for AWS Osaka region (ap-northeast-3) as `# region22` in the following file.
    https://github.com/cloud-barista/cb-tumblebug/blob/e6572b69c9d2baa62907ce2eb327607a90499521/src/testclient/scripts/conf.env#L292
    For instance,
    ```
    # region22
    IY=$AwsApNortheast3
    # Location: Asia Pacific (Osaka)
    RegionName[$IX,$IY]=aws-ap-northeast-3
    RegionKey01[$IX,$IY]=Region
    RegionVal01[$IX,$IY]=ap-northeast-3
    RegionKey02[$IX,$IY]=Zone
    RegionVal02[$IX,$IY]=ap-northeast-3a
    CONN_CONFIG[$IX,$IY]=aws-ap-northeast-3
    IMAGE_NAME[$IX,$IY]=ami-092faff259afb9a26  # Ubuntu Server 18.04 LTS (HVM)
    SPEC_NAME[$IX,$IY]=t2.micro
    ```

 - [ ] Add a new index for AWS ap-northeast-3 in the following file.
    https://github.com/cloud-barista/cb-tumblebug/blob/e6572b69c9d2baa62907ce2eb327607a90499521/src/testclient/scripts/testSet.env#L52
    For instance,
    ```
    AwsApNortheast1=$((++IY))			# Location: Asia Pacific (Tokyo)
    AwsApNortheast3=$((++IY))			# Location: Asia Pacific (Osaka)
    AwsApSouth1=$((++IY))				# Location: Asia Pacific (Mumbai)
    ```

- Ref: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html
- Ref: https://github.com/cloud-barista/cb-tumblebug/pull/482

**Comment by seokho-son** [comment]
@irint92 Could you help us to resolve this issue? I think this is a good-first-issue. :)

**Comment by seokho-son** [comment]
Ping @irint92 :)

**Comment by seokho-son** [comment]
I'd like to open this issue to everyone :) 

Please let us know if you are interested !! FIFO

**Comment by jangh-lee** [comment]
@seokho-son  I want to join this issue.

**Comment by jangh-lee** [comment]
아 그런데, test script인 conf.env와 testSet.env 모두 osaka리전이 포함되어 작성이 되어있는 것 같네요.


![image](https://user-images.githubusercontent.com/72970232/134813354-27685bd7-86a5-4410-a96c-b9088aa63cee.png)

![image](https://user-images.githubusercontent.com/72970232/134813368-92014003-fd89-497c-a452-57970f82444c.png)

**Comment by seokho-son** [comment]
@jangh-lee 헉! 이건 저의 실수이네요. 이미 처리되어 있는 내용을 포함해달라고 이슈를 만들다니;;

확인 감사합니다!! 기여해보겠다고 하셨는데 ㅠㅠ 해당 이슈는 아쉽지만 close 하겠습니다.. ^^ 

다른 좋은 이슈를 또 찾아서 소개해드리겠습니다.
