### ISSUE TITLE
Add Graceful Shutdown of CB-Tumblebug server

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#716]
**What would you like to be added**
: Graceful Shutdown of CB-Tumblebug server (REST API, ...)

**Why is this needed**

> Whenever a server needs to shut down for various reasons, the common one being OS interrupts, we would want our servers to shut down gracefully. We would want our golang server to stop receiving new requests while complete the ongoing requests and return their responses and then finally shut down. - "Graceful shutdown of Golang servers using Context and OS signals" by Pinku Deb Nath

ref) https://echo.labstack.com/cookbook/graceful-shutdown/
ref) https://medium.com/@pinkudebnath/graceful-shutdown-of-golang-servers-using-context-and-os-signals-cc1fa2c55e97

**Comment by sypark9646** [comment]
제가 해당 task 진행해보겠습니다!

**Comment by seokho-son** [comment]
감사 감사합니다~~ :)

**Comment by yunkon-kim** [comment]
개선 사항이 있어 Reopen 하였습니다.
