### ISSUE TITLE
Dynamic config for server port

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#722]
**What would you like to be enhanced**
: Dynamic config for server port (REST api server for this moment)

**Why is this needed**
: Sometimes users want to use custom port

**Proposed solution**
- [ ] Add a new environment variable for CB-Tumblebug REST API port. 
  Where: https://github.com/cloud-barista/cb-tumblebug/blob/99bbff3b9b115b2e26fcdb2730cf8e052328d04a/conf/setup.env#L6
  Ex: TUMBLEBUG_REST_PORT=1323
- [ ] Replace a section using static port.
  Where: https://github.com/cloud-barista/cb-tumblebug/blob/99bbff3b9b115b2e26fcdb2730cf8e052328d04a/conf/setup.env#L21
  Ex: export SELF_ENDPOINT=localhost:$TUMBLEBUG_REST_PORT
- [ ] Replace a section using static port.
  Where: https://github.com/cloud-barista/cb-tumblebug/blob/99bbff3b9b115b2e26fcdb2730cf8e052328d04a/conf/setup.env#L21
  Ex: export SELF_ENDPOINT=localhost:$TUMBLEBUG_REST_PORT
- [ ] Update the server initiation code with $TUMBLEBUG_REST_PORT
  Where: https://github.com/cloud-barista/cb-tumblebug/blob/99bbff3b9b115b2e26fcdb2730cf8e052328d04a/src/api/rest/server/server.go#L263
  Ex: e.Logger.Fatal(e.Start(":" + os.Getenv("TUMBLEBUG_REST_PORT") ))

**Comment by betelgeuse-7** [comment]
Can't we require the user to pass, for example, `--port=1323` ? We can utilize flag package for parsing command line arguments. 
If the user doesn't give a port, we can use a default port such as 1323. 
¯\_(ツ)_/¯

**Comment by seokho-son** [comment]
@betelgeuse-7 Thank you for the suggestion !
I'd like to invite you to resolve this Issue ! (if you are available)

I think your suggestion is a better solution. :)

I hope to hear @jihoon-seo 's opinion though to check there are no other concerns.
PTAL: @jihoon-seo

**Comment by betelgeuse-7** [comment]
Okay. I am going to try to add this feature tomorrow. :)

**Comment by jihoon-seo** [comment]
This issue is resolved by the PR #802.
