### ISSUE TITLE
Not properly formatted source codes

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#747]
**What would you like to be enhanced**
Two files are not formatted in `gofmt`.
https://goreportcard.com/report/github.com/cloud-barista/cb-tumblebug

1. cb-tumblebug/src/core/common/utility.go
: warning: file is not gofmted with -s (gofmt)

2. cb-tumblebug/src/core/mcis/orchestration.go
: warning: file is not gofmted with -s (gofmt)

**Why is this needed**
Code enhancement. 

**Proposed solution**
Apply gofmt to each file.

 - [ ] 1. gofmt -s -w cb-tumblebug/src/core/common/utility.go
 - [ ] 2. gofmt -s -w cb-tumblebug/src/core/mcis/orchestration.go

PR example: https://github.com/cloud-barista/cb-tumblebug/pull/693

**Comment by seokho-son** [comment]
Hello, contributors ~! This is very simple issue :)
I'd like to recruit **two new contributors** !
Please let us know, if you are interested.

**Comment by jihoon-seo** [comment]
For anyone's information: 다음 위키 글도 참고해 보세요 😊
https://github.com/cloud-barista/cb-tumblebug/wiki/Enable-%60gofmt--s%60-(simplify)-flag-on-gopls-enabled-VScode

**Comment by ChobobDev** [comment]
제가 한번 기여해 보도록 하겠습니다.

**Comment by seokho-son** [comment]
감사합니다!! 어려움이 있으시면 공유해주세요~~~ :)

**Comment by ChobobDev** [comment]
넵
