### ISSUE TITLE
Typo in Readme

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#748]
#### Problem !

Missed `)` for a link in Readme.
[cb-tumblebug/blob/main/README.md](https://github.com/cloud-barista/cb-tumblebug#cb-tumblebug-%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-%EC%82%AC%EC%9A%A9)

#### Suggestion !

```diff
- 3 단계: [멀티 클라우드 인프라 유스케이스 자동 배포](#멀티-클라우드-인프라-유스케이스
+ 3 단계: [멀티 클라우드 인프라 유스케이스 자동 배포](#멀티-클라우드-인프라-유스케이스)
```

**Comment by seokho-son** [comment]
Hello, contributors ~! This is a very simple issue :)
I'd like to recruit **a new contributor** !
Please let us know, if you are interested.

**Comment by ChobobDev** [comment]
If no one is Interested,will it be okay for me to work on this issue?

**Comment by seokho-son** [comment]
Of course you can work on this issue. I will assign.
