### ISSUE TITLE
Organize MCIS control REST APIs

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#749]
336 라인에서 `status, ` 부분은 삭제하는 것이 맞겠습니다. 😊

As of 2021-09-15:

- `refine` 기능은 `/ns/{nsId}/mcis/{mcisId} [get]` API에 들어 있습니다 😊
- `suspend, resume, reboot, terminate` 기능이 `/ns/{nsId}/mcis/{mcisId} [get]` API에도 남아 있습니다.
  제거해도 괜찮다면 (cb-webtool, CB-MCKS 에 안내 등), 제거하면 좋겠네요 😊

---
 
- `/ns/{nsId}/mcis/{mcisId} [get]` API에는 정보/상태 조회 기능 (metadata, status, id, simple) 만 남긴다면,
  `refine` 기능은 다른 API로 옮기는 것이 좋을 것 같습니다. 😊
  - 그런데, `/ns/{nsId}/control/mcis/{mcisId} [get]` 은 약간.. 라이프사이클 컨트롤 API 같아 보이는 저의 고정관념이 있어서
    `refine` 기능을 `/ns/{nsId}/control/mcis/{mcisId} [get]` API로 옮기는 것이 적절한지는 저는 약간 고민스럽네요.. 🤔

_Originally posted by @jihoon-seo in https://github.com/cloud-barista/cb-tumblebug/pull/695#discussion_r708886283_

**Comment by seokho-son** [comment]
@jihoon-seo 공감합니다..^^ 일단 api를 읽기 전용 구분을 위해 나누는 상황이라 오브젝트에 수정을 가하는 refine은 옮기는 것이 맞을 것 같은데,

Refine이 라이프사이클을 위한 정리옵션을 것을 고려하면
/ns/{nsId}/control/mcis/{mcisId} 에 들어가도 되지 않을까 싶네요.^^ 아님 다른 함수를 만드는 것이 좋으려나요.

**Comment by seokho-son** [comment]
@jihoon-seo 

/ns/{nsId}/control/mcis/{mcisId}  에서 refine 이 처리되도록 contribution recruiting 해볼까요? ^^ 신규 이슈로??

**Comment by seokho-son** [comment]
I think this issue has been resolved by #760

**Comment by seokho-son** [comment]
Let me close :)
