### ISSUE TITLE
Current Dockerfile uses static endpoint for spider and dragonfly

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#765]
https://github.com/cloud-barista/cb-tumblebug/blob/main/Dockerfile#L48

현재 Dockerfile 에는
`ENV SPIDER_REST_URL http://cb-spider:1024/spider` 와 같은 형태로 엔드포인트(cb-spider)가 명시되어 있습니다.

dockercompose나, kubernetes 환경에서는 문제가 없을 것 같은데,

local 머신에서 독자적으로 컨테이너를 실행하게 되면

cb-spider 에 대한 도메인네임 리졸브가 바로 되지 않을 것 같네요.

개선이 필요할까요? 

PTAL: @jihoon-seo

**Comment by jihoon-seo** [comment]
@seokho-son 한번 쭉 적어 보았습니다.. 😊

CB-Tumblebug 컨테이너를 활용하는 방법은 다음과 같습니다.
1. `docker run` 명령을 이용하여 실행
2. `docker-compose.yaml` 파일을 작성하고, Docker Compose 이용하여 실행
3. Helm chart 작성하고, Helm 이용하여 실행

이 이슈에서는 `1. docker run 명령을 이용하여 실행` 에 대해 다루고 있기 때문에, 아래에서도 이 경우에 대해 다뤄 보겠습니다.

[CB-TB Dockerfile](https://github.com/cloud-barista/cb-tumblebug/blob/44a0bed527b3e40002817f225910f401d1729c91/Dockerfile#L48) 에는
`ENV SPIDER_REST_URL http://cb-spider:1024/spider` 라고 되어 있어서

이대로라면 "특정한 경우"에서만 resolve가 될 것입니다.
("특정한 경우": CB-SP 컨테이너와 CB-TB 컨테이너가 동일한 Docker Network에 존재하고
CB-SP 컨테이너의 이름이 정확히 "cb-spider" 인 경우)

본문에서 언급된 "local 머신에서 독자적으로 컨테이너를 실행" 하는 경우,
지금까지 저희가 제공했던 CB-SP / CB-TB 컨테이너 실행 command 예제들은
"CB-SP 컨테이너와 CB-TB 컨테이너가 동일한 Docker Network를 사용해야 한다" 라고 명시하지 않았기 때문에
CB-TB 컨테이너를 실행하면 "cb-spider" 라는 domain name을 resolve 하지 못해 reach 하지 못할 것입니다.

---

이제, `ENV SPIDER_REST_URL http://localhost:1024/spider` 로 바꿨다고 가정해 보겠습니다.
그러면, "특정한 경우들" 에서만 CB-SP 컨테이너에 reach가 가능할 것입니다.
("특정한 경우들": 
1. CB-SP 컨테이너와 CB-TB 컨테이너를 실행할 때, 둘 다 `--net=host` 옵션을 줬거나
2. CB-SP 컨테이너와 CB-TB 컨테이너가 하나의 컨테이너 네트워크를 공유하도록 설정했거나..

참조: https://bluese05.tistory.com/38 )

---

위의 사항을 고려할 때, 
`1. docker run 명령을 이용하여 실행`하는 경우에 있어서
사용자가 CB-SP, CB-TB 컨테이너를 실행할 때 Docker network에 대해 특별히 신경쓰지 않았다면

`Dockerfile` 에는 `http://cb-spider:1024` 로 되어 있든 `http://localhost:1024` 로 되어 있든
CB-TB -> CB-SP 로의 통신은 실패하게 됩니다.

위와 같은 상황에서
제 개인적인 의견은
둘 중에서는 `http://cb-spider:1024` 로 적어 놓는 것이 
"이 자리에는 CB-SP의 Hostname 또는 IP 주소를 적으세요 - cb-spider 일 수도 있고, localhost 일 수도 있고, ..." 라는 사실을
사용자에게 조금 더 명시적으로 알려줄 수 있지 않을까 싶습니다.

---

실제로는 어떻냐면..

"The priority used by Compose to choose which env var value to use" 가 다음과 같습니다.
1. Compose file
2. Shell environment variables
3. Environment file
4. Dockerfile
5. Variable is not defined

즉, `Dockerfile` 에 저렇게 명시를 했지만
1~3번 방법에 의해 override 됩니다.

cb-operator에서는 어떻게 하고 있냐면..
- Docker Compose mode: `docker-compose.yaml` 에 [`SPIDER_REST_URL=http://cb-spider:1024/spider`](https://github.com/cloud-barista/cb-operator/blob/79f433e195fd9335b51e1b461009c8ffac900f12/docker-compose-mode-files/docker-compose.yaml#L115) 라고 명시해 두었음. 
  필요 시, cb-operator 사용자가 이 부분을 수정하여 `./operator run` 실행하면 override 됨.
- K8s mode: CB-TB subchart의 `values.yaml` 에서 [`value: "http://cb-spider:1024/spider"`](https://github.com/cloud-barista/cb-operator/blob/79f433e195fd9335b51e1b461009c8ffac900f12/helm-chart/charts/cb-tumblebug/values.yaml#L14) 라고 명시해 두었음.
  필요 시, cb-operator 사용자가 이 부분을 수정하여 `./operator run` 실행하면 override 됨.

그리고 `1. docker run 명령을 이용하여 실행`하는 경우에 있어서는
#768 에서 하신 것과 같이
`docker run -e SPIDER_REST_URL=http://localhost:1024/spider ...` 로 실행하시면
override 가 됩니다. 😊

(그런데 제가 `docker run -e SPIDER_REST_URL=http://localhost:1024/spider ...` 로 실행해 보니 CB-SP 컨테이너로 접근을 못 하네요.. 🤔)
