### ISSUE TITLE
Exported type should have comment or be unexported (golint)

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#783]
**What would you like to be enhanced**
Exported type should have comment or be unexported (golint) for 

cb-tumblebug/src/core/mcir/common.go

- Line 431: warning: exported type SpiderNameIdSystemId should have comment or be unexported (golint)
- Line 436: warning: exported type SpiderAllListWrapper should have comment or be unexported (golint)
- Line 440: warning: exported type SpiderAllList should have comment or be unexported (golint)
- Line 446: warning: comment on exported type TbInspectResourcesResponse should be of the form "TbInspectResourcesResponse ..." (with optional leading article) (golint)
- Line 1031: warning: if block ends with a return statement, so drop this else and outdent its block (golint)
- Line 1236: warning: exported type ReturnValue should have comment or be unexported (golint)
- Line 1240: warning: exported type NameOnly should have comment or be unexported (golint)
- Line 1254: warning: if block ends with a return statement, so drop this else and outdent its block (golint)

**Why is this needed**
To resolve #654 (Update source codes to comply with golint) partially.

**Proposed solution**

Add comments in cb-tumblebug/src/core/mcir/common.go

1. - [x] Line 431: warning: exported type SpiderNameIdSystemId should have comment or be unexported (golint)
2. - [x] Line 436: warning: exported type SpiderAllListWrapper should have comment or be unexported (golint)
3. - [x] Line 440: warning: exported type SpiderAllList should have comment or be unexported (golint)
4. - [x] Line 446: warning: comment on exported type TbInspectResourcesResponse should be of the form "TbInspectResourcesResponse ..." (with optional leading article) (golint)
5. - [ ] Line 1236: warning: exported type ReturnValue should have comment or be unexported (golint)
6. - [ ] Line 1240: warning: exported type NameOnly should have comment or be unexported (golint)

**Comment by seokho-son** [comment]
Tip

1. - [ ] Line 431: warning: exported type SpiderNameIdSystemId should have comment or be unexported (golint)

// SpiderNameIdSystemId is struct for mapping NameID and System ID from CB-Spider response. 

2. - [ ] Line 436: warning: exported type SpiderAllListWrapper should have comment or be unexported (golint)

// SpiderAllListWrapper is struct for wrapping SpiderAllList struct from CB-Spider response. 

3. - [ ] Line 440: warning: exported type SpiderAllList should have comment or be unexported (golint)

// SpiderAllList is struct for OnlyCSPList, OnlySpiderList MappedList from CB-Spider response. 

4. - [ ] Line 446: warning: comment on exported type TbInspectResourcesResponse should be of the form "TbInspectResourcesResponse ..." (with optional leading article) (golint)

// Response struct for InspectResources 
-->
// TbInspectResourcesResponse is struct for response of InspectResources request

5. - [ ] Line 1236: warning: exported type ReturnValue should have comment or be unexported (golint)

6. - [ ] Line 1240: warning: exported type NameOnly should have comment or be unexported (golint)

**Comment by seokho-son** [comment]
제가 Task 1번을 처리해보겠습니다!

**Comment by ChobobDev** [comment]
제가 Task 3번을 처리해보겠습니다

**Comment by Modney** [comment]
제가 task 2번하겠습니다

**Comment by sypark9646** [comment]
제가 Task 4번을 처리해보겠습니다!
