### ISSUE TITLE
Mislead contents in Readme

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#793]
**What happened**
Mislead contents in Readme (https://github.com/cloud-barista/cb-tumblebug/blob/main/README.md).

https://github.com/cloud-barista/cb-tumblebug/blame/main/README.md#L422
https://github.com/cloud-barista/cb-tumblebug/blame/main/README.md#L423

```
  - CB-MapUI 를 통해 MCIS 형상 확인 및 제어 가능
    - `./command-mcis.sh -n shson -f ../testSetCustom.env`  # MCIS의 모든 VM에 IP 및 Hostname 조회를 수행
```

are mislead contents.

**Proposed solution**

Remove 
https://github.com/cloud-barista/cb-tumblebug/blame/main/README.md#L422
https://github.com/cloud-barista/cb-tumblebug/blame/main/README.md#L423

```diff
-  - CB-MapUI 를 통해 MCIS 형상 확인 및 제어 가능
-    - `./command-mcis.sh -n shson -f ../testSetCustom.env`  # MCIS의 모든 VM에 IP 및 Hostname 조회를 수행
```

**Comment by MukulKolpe** [comment]
Hey @seokho-son can I work on this issue?

**Comment by jihoon-seo** [comment]
@MukulKolpe Sure!
Thank you for your interest on this project! 😊

**Comment by seokho-son** [comment]
@MukulKolpe 
We always welcome new contributors !! Please go ahead :)

I hope to share this notice regarding language used in this project.
[Localization and Globalization of CB-Tumblebug](https://github.com/cloud-barista/cb-tumblebug#localization-and-globalization-of-cb-tumblebug-cb-tumblebug%EC%9D%98-%ED%98%84%EC%A7%80%ED%99%94-%EB%B0%8F-%EC%84%B8%EA%B3%84%ED%99%94)
```
[English] As an opensource project initiated by Korean members, 
we would like to promote participation of Korean contributors during initial stage of this project. 
So, CB-Tumblebug Repo will accept use of Korean language in its early stages.
On the other hand, we hope this project flourishes regardless of contributor's country eventually.
So, the maintainers recommend using English at least for the title of Issues, Pull Requests, and Commits, 
while CB-Tumblebug Repo accommodates local languages in the contents of them.
```
We can communicate in English. So, please feel free to ask any question regarding this project.
