### ISSUE TITLE
Error in `docker run ...` command

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#796]
**What happened**
: 
In https://github.com/cloud-barista/cb-tumblebug#2-컨테이너-기반-실행 ,
local path to mount is hardcoded as `/root/`.

```shell
docker run -p 1323:1323 -p 50252:50252 \
-v /root/go/src/github.com/cloud-barista/cb-tumblebug/meta_db:/app/meta_db \
--name cb-tumblebug \
cloudbaristaorg/cb-tumblebug:0.4.xx

```

**What you expected to happen**
: 

**How to reproduce it (as minimally and precisely as possible)**
: 

**Anything else we need to know?**
: 

**Environment**
- Source version or branch: 
- OS: 
- Others: 

**Proposed solution**
: 
Update [README.md](https://github.com/cloud-barista/cb-tumblebug/blob/main/README.md) to:
```shell
docker run -p 1323:1323 -p 50252:50252 \
-v ${HOME}/go/src/github.com/cloud-barista/cb-tumblebug/meta_db:/app/meta_db \
--name cb-tumblebug \
cloudbaristaorg/cb-tumblebug:0.4.xx

```

**Any other context**
:

**Comment by Jayita10** [comment]
I want to work on this issue

**Comment by seokho-son** [comment]
@Jayita10 I am happy to see a new contributor !! 
Sure, you can work on this issue :)

Let me assign you to this issue.
