### ISSUE TITLE
Add 'paths to ignore' to auto-build GitHub workflows

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#797]
Resolves https://github.com/cloud-barista/cb-tumblebug/pull/794#issuecomment-927450541

**What would you like to be enhanced**
: 
Add 'paths to ignore' to auto-build GitHub workflows.

**Why is this needed**
: 
[`docs/`](https://github.com/cloud-barista/cb-tumblebug/tree/main/docs) 디렉토리 아래에 있는 파일들은 업데이트 되더라도
- 빌드 테스트를 필요로 하지 않고
- 컨테이너 이미지 업데이트도 필요로 하지 않기 때문임

**Proposed solution**
:

[Line to add]
```diff
    paths-ignore:
+      - 'docs/**'
```

[Files to update]
- https://github.com/cloud-barista/cb-tumblebug/blob/main/.github/workflows/build-amd64-container-image.yaml
- https://github.com/cloud-barista/cb-tumblebug/blob/main/.github/workflows/publish-multi-arch-container-images.yaml

**Comment by seokho-son** [comment]
@jangh-lee 
간단하지만~ Github workflow 를 개선해볼 수 있는 이슈입니다! :) 
혹시 기여에 관심이 있으신가요? ^^

**Comment by jangh-lee** [comment]
@seokho-son 넵! 참여하겠습니다!! files to update에 있는 파일 수정 진행해보겠습니다.

**Comment by seokho-son** [comment]
감사합니다! workflow 연습/공부? 도 devops에 도움이 되지 않을까 싶어요 ㅎㅎ

**Comment by jangh-lee** [comment]
@seokho-son  @jihoon-seo Good first issue 감사합니다. PR 진행했으나,
학습을 위해서 불필요한 브랜치 및 커밋이 많았어서 전부 삭제하고 올리는 것이라서 잘 되었는지 모르겠습니다.
검토 부탁드립니다.

**Comment by seokho-son** [comment]
resolved by #810
