### ISSUE TITLE
Set `CBTUMBLEBUG_ROOT` based on a project root directory

### ISSUE THREAD

**Issue by hermitkim1** [cloud-barista/cb-tumblebug#815]
**What would you like to be enhanced**
: To set `CBTUMBLEBUG_ROOT` in `setup.env` based on a project root directory
: Refs (Thanks, @computerphilosopher):
- https://github.com/cloud-barista/cb-spider/issues/458#issue-978197964
- https://github.com/cloud-barista/cb-spider/pull/459#issue-982139909

**Why is this needed**
: It must be more convenient for contributors to configure their own development environment (e.g., VSCode and GoLand) 😃 

**Proposed solution**
```
SCRIPT_DIR=`dirname ${BASH_SOURCE[0]-$0}`
export CBTUMBLEBUG_ROOT=`cd $SCRIPT_DIR && cd .. && pwd`
```

**Comment by seokho-son** [comment]
@hermitkim1 Thanks!!
Do you want to open a PR or should we invite a contributor ? (help-wanted ? good-first ?)

**Comment by hermitkim1** [comment]
@seokho-son 
If no issues are expected, I think it's better to apply this by direct commit to the upstream `main`.

It's because `conf/` is in the `.gitignore`

**Comment by hermitkim1** [comment]
By the offline discussion with @seokho-son 

I'd like to handle this issue.
