### ISSUE TITLE
Change MCIS provisioning meta data for not assigned IP address

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#816]
**What would you like to be enhanced**
 - https://github.com/cloud-barista/cb-tumblebug/blob/main/src/core/mcis/provisioning.go 에는 MCIS 생성관련 소스가 포함되어 있습니다.
 - https://github.com/cloud-barista/cb-tumblebug/blob/11af4b1c221dd0f3942cbcdc9b0f1a1e7ad9fcac/src/core/mcis/provisioning.go#L706 `func CreateMcis` 로 MCIS를 생성하면, 요청된 VM들이 CSP에 생성이 됩니다.
 - VM 생성이 완료되면 vmInfoData.PublicIP 와 vmInfoData.PublicDNS 에 실제 IP, DomainName정보가 저장됩니다.
 - VM 생성이 진행 중이거나, 문제가 발생한 경우에는 "Not assigned yet" 이라는 메시지를 출력하도록 값이 지정되어 있습니다.
   - "Not assigned yet" 메시지가 의미 없이 길고, "yet" 이라는 시점이 불명확하므로, 이를 "empty"로 변경하면 좋겠습니다.

**Why is this needed**
 - MCIS 프로비저닝 출력 메시지 개선

**Proposed solution**

https://github.com/cloud-barista/cb-tumblebug/blob/main/src/core/mcis/provisioning.go 에서 

"Not assigned yet" 를 검색하여 "empty" 로 변경

- https://github.com/cloud-barista/cb-tumblebug/blob/11af4b1c221dd0f3942cbcdc9b0f1a1e7ad9fcac/src/core/mcis/provisioning.go#L404
- https://github.com/cloud-barista/cb-tumblebug/blob/11af4b1c221dd0f3942cbcdc9b0f1a1e7ad9fcac/src/core/mcis/provisioning.go#L629
- https://github.com/cloud-barista/cb-tumblebug/blob/11af4b1c221dd0f3942cbcdc9b0f1a1e7ad9fcac/src/core/mcis/provisioning.go#L849

[CB-TB 기여자의 테스팅 준수 사항](https://github.com/cloud-barista/cb-tumblebug/wiki/Basic-testing-guide-before-a-contribution) 확인 필요합니다..^^

해당 이슈가 정리되면
`$ ./create-all.sh` 의 결과에서 VM 정보 항목이 밀려나는 문제도 해결이 됩니다..^^ (아래 그림에서 Status가 Failed인 항목 참고)

![image](https://user-images.githubusercontent.com/5966944/135334658-7b8a75ff-42d3-4b2a-b0cb-4802afc88aef.png)

**Comment by seokho-son** [comment]
@leedohun 님~ 
해당 이슈는 소스코드를 살짝 수정해볼 수 있는 good first issue 입니다.
혹시 관심 있으신가요~? ^^

**Comment by jihoon-seo** [comment]
이 이슈는 PR #826 에 의해 해결되었으므로 close 합니다~~ 😊
