### ISSUE TITLE
Rename `CoreGetAllBenchmark` function name

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#834]
**What would you like to be enhanced**
: Change `CoreGetAllBenchmark` function name

**Why is this needed**
: The func name is not appropriate.

**Proposed solution**
: Search `CoreGetAllBenchmark`. Replace it with `RunAllBenchmarks`

- cb-tumblebug/src/api/grpc/server/mcis/control.go
  -   516,22: 	result, err := mcis.CoreGetAllBenchmark(req.NsId, req.McisId, mcisObj.Host)

- cb-tumblebug/src/api/rest/server/mcis/control.go
  -   763,22: 	result, err := mcis.CoreGetAllBenchmark(nsId, mcisId, req.Host)

- cb-tumblebug/src/core/mcis/benchmark.go
  -   195,4: // CoreGetAllBenchmark is func to get alls Benchmarks
  -   196,6: func CoreGetAllBenchmark(nsId string, mcisId string, host string) (*BenchmarkInfoArray, error) {

관련 소스 간략 설명: 

- `cb-tumblebug/src/core/mcis/benchmark.go` 에는 각 CSP 및 리전의 VM Spec의 성능을 측정하기 위한 벤치마킹 관련 함수들이 포함되어 있습니다. 
- 그 중, `CoreGetAllBenchmark` 는 MCIS에 포함된 모든 VM들에게 다중 항목("cpus", "cpum", "memR", "memW", "fioR", "fioW", "dbR", "dbW", "rtt")에 대한 성능 평가를 하고, 그 정보를 CB-TB 서버가 위치하는 곳에 내부 파일(benchmarking.csv)로 저장해 주는 기능을 제공합니다.
- 해당 함수는 REST 및 gRPC 인터페이스를 통해서 호출할 수 있습니다. 관련 소스는 아래에 위치합니다.
  - REST API: - cb-tumblebug/src/api/rest/server/mcis/control.go
  - gRPC API: - cb-tumblebug/src/api/grpc/server/mcis/control.go

CB-TB의 소스코드는 대부분 이런 형태로 구성이 되어 있습니다. (생각보다 간단)

 - CB-TB 시스템이 구동되면, REST API 서버 / gRPC 서버 / 오케스트레이션 관리 모듈 이렇게 3가지가 고루틴(쓰레드와 비슷한 개념)으로 병렬로 상시 구동 됩니다. 

 - REST API 를 받는 함수 -> 해당 기능을 수행하는 핸들러
 - gRPC API 를 받는 함수 -> 해당 기능을 수행하는 핸들러
 - 오케스트레이터는 시간에 따라 주기적으로 동작하며 -> 지정된 액션(함수)을 수행

**Comment by ChobobDev** [comment]
@seokho-son  I found typos in your comment so @limsg1234  was not assigned to this issue as you desired.
 So I have assigned @limsg1234  by myself so others can know whether this issue is already taken by someone from the issue list.

Thank you

**Comment by seokho-son** [comment]
MyLovelyTypo !! ;) 
Thanks.
