### ISSUE TITLE
Hide some contents in Readme.md

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#837]
**What would you like to be enhanced**
- https://github.com/cloud-barista/cb-tumblebug/blob/main/README.md is too long. 
- we can hide some contents that do not requires immediate attention..

**Why is this needed**
: Enhance readability

**Proposed solution**

Change the following part

> - 알려진 에러 및 해결 방법 
>   ``` 
>   panic: /debug/requests is already registered. 
>   You may have two independent copies of golang.org/x/net/trace in your binary, 
>   trying to maintain separate state. 
>   This may involve a vendored copy of golang.org/x/net/trace.
>   ```
> 
>   에러 발생 시, 다음을 실행하여 해결
>   ```bash
>   rm -rf $GOPATH/src/go.etcd.io/etcd/vendor/golang.org/x/net/trace
>   make
>   ```

to 

> <details>
> <summary>알려진 에러 및 해결 방법</summary>
>   
> - golang.org/x/net/trace 관련 에러 및 해결 방법 
>   ``` 
>   panic: /debug/requests is already registered. 
>   You may have two independent copies of golang.org/x/net/trace in your binary, 
>   trying to maintain separate state. 
>   This may involve a vendored copy of golang.org/x/net/trace.
>   ```
> 
>   해결 방법: 다음을 실행하여 중복된 파일 정리
>   ```bash
>   rm -rf $GOPATH/src/go.etcd.io/etcd/vendor/golang.org/x/net/trace
>   make
>   ```
>   
> </details>

by using `<details>`

The suggested source looks like this,

```
<details>
<summary>알려진 에러 및 해결 방법</summary>
  
- golang.org/x/net/trace 관련 에러 및 해결 방법 
  \``` 
  panic: /debug/requests is already registered. 
  You may have two independent copies of golang.org/x/net/trace in your binary, 
  trying to maintain separate state. 
  This may involve a vendored copy of golang.org/x/net/trace.
  \```

  해결 방법: 다음을 실행하여 중복된 파일 정리
  \```bash
  rm -rf $GOPATH/src/go.etcd.io/etcd/vendor/golang.org/x/net/trace
  make
  \```
  
</details>
```

**Comment by ChobobDev** [comment]
I will try to solve this issue along with the English README.md

Thank you

**Comment by saadfareed** [comment]
can you assign it to me

**Comment by seokho-son** [comment]
/assign @saadfareed 
For https://github.com/cloud-barista/cb-tumblebug/blob/main/README.md

**Comment by seokho-son** [comment]
/assign @ChobobDev
for https://github.com/cloud-barista/cb-tumblebug/blob/main/i18n/README-EN.md

**Comment by seokho-son** [comment]
Hi @saadfareed
Are you working on this issue ?
I just want to check everything regarding this issue is going well :)

> @ChobobDev Could you handle this issue only for https://github.com/cloud-barista/cb-tumblebug/blob/main/i18n/README-EN.md (English Readme) ?
> 
> I'd like to assign this issue (for handling https://github.com/cloud-barista/cb-tumblebug/blob/main/README.md which is Korean Readme) to new contributor @saadfareed
> 
> @saadfareed Thank you for the interest on this project ! This issue is to update Korean readme. However, you don't need to know Korean context to resolve this issue. So, I think you can work on this ~
> 
> Let me assign you ~ ! If you face any difficulty, let us know.
