### ISSUE TITLE
Remove `gen-sshKey-withGivenMcisName.sh` script not in use

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#842]
**What would you like to be enhanced**
Delete the following file.
https://github.com/cloud-barista/cb-tumblebug/blob/main/src/testclient/scripts/sequentialFullTest/gen-sshKey-withGivenMcisName.sh

**Why is this needed**
We do not need `gen-sshKey-withGivenMcisName.sh` any more. 
We can use `gen-sshKey.sh` instead of it

**Proposed solution**
Delete the following file.
https://github.com/cloud-barista/cb-tumblebug/blob/main/src/testclient/scripts/sequentialFullTest/gen-sshKey-withGivenMcisName.sh

**Comment by leedohun** [comment]
제가 한번 작업해보겠습니다.
