### ISSUE TITLE
Add path to be ignored by auto-build workflows 

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#853]
**What would you like to be enhanced**
Add path to be ignored by auto-build workflows 

**Why is this needed**
[`src/api/rest/docs/`](https://github.com/cloud-barista/cb-tumblebug/tree/main/src/api/rest/docs) 디렉토리 아래에 있는 파일들은 프로그램 구동에 무관하므로 업데이트 되더라도 
- 빌드 테스트, 
- 컨테이너 이미지 업데이트를 자동으로 수행할 필요가 없음.

**Proposed solution**

[Line to add]
```diff
on:
  # On pull-request event with detailed condition below.
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.all-contributorsrc'
      - '.gitignore'
      - 'LICENSE'
      - 'CODEOWNERS'
      - 'assets/**'
      - 'scripts/**'
      - 'src/testclient/scripts/**'
+     - 'src/api/rest/docs/**'
```

[Files to update]
- https://github.com/cloud-barista/cb-tumblebug/blob/main/.github/workflows/build-amd64-container-image.yaml
- https://github.com/cloud-barista/cb-tumblebug/blob/main/.github/workflows/publish-multi-arch-container-images.yaml

**Comment by jihoon-seo** [comment]
훔.. 지금 생각해 보니..

[시나리오]
1. 사용자가 코드를 수정했으나, Swagger doc 은 업데이트하지 않음 ('상태 A')
2. `update-swagger-doc` workflow가 작동하여 PR open
3. 메인테이너가 PR을 merge ('상태 B')

이 이슈에 제안된 내용을 적용하면
'상태 A' 에 대한 컨테이너 이미지는 Docker Hub 등으로 build & push 되는데
'상태 B' 에 대한 컨테이너 이미지는 Docker Hub 등으로 build & push 되지 않아서

사용자가 이 이미지를 이용하여 컨테이너를 실행하고 Swagger doc을 조회하면
2~3번이 적용되기 전의 Swagger doc을 보게 되는 문제가 있습니다. 🤔

**Comment by seokho-son** [comment]
@jihoon-seo 그렇군요! update-swagger-doc workflow 가 도입되어서 상황이 달라졌을 수 있겠네요.

해당 issue는 close 하면 될까요? ^^

**Comment by jihoon-seo** [comment]
@seokho-son 네 close 하면 될 것 같습니다. 😊
