### ISSUE TITLE
Remove obsolete comments in `securitygroup.go`

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#865]
**What would you like to be enhanced**
: Remove obsolete comments in `image.go`

**Why is this needed**
: Code enhancement

**Proposed solution**

Remove following comments from `cb-tumblebug/src/core/mcir/securitygroup.go`

- `// 2020-04-13 https://github.com/cloud-barista/cb-spider/blob/master/cloud-control-manager/cloud-driver/interfaces/resources/SecurityHandler.go`
 - `/*
type SpiderSecurityReqInfo struct { // Spider
	Name          string
	VPCName       string
	SecurityRules *[]SpiderSecurityRuleInfo
	//Direction     string // @todo used??
}
*/`

**Comment by FionaFR** [comment]
Can you label this as hacktoberfest?
