### ISSUE TITLE
Suggestion: `mcism` -> `cb-tumblebug`

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug#88]
https://github.com/cloud-barista/cb-tumblebug/blob/master/README.md
여기에 `mcism` 이라고 기술되어 있는데,
처음 보는 사람은 이것이 무엇을 가리키는 것인지 알기 어려울 수 있고, 직관성이 떨어집니다.

Related:
https://github.com/cloud-barista/cb-tumblebug/blob/master/src/Makefile
여기에도, build 결과물로 생성되는 바이너리의 파일명이 `mcism` 으로 되어 있습니다.

FYI:
https://github.com/cloud-barista/cb-tumblebug/blob/master/Dockerfile
여기에서는,

- 임시로 생성되는 컨테이너 안의, 바이너리의 파일명
- `docker build` 의 결과물인 컨테이너 이미지 안의, 바이너리의 파일명

을 `cb-tumblebug` 이라고 하였습니다.

**Comment by seokho-son** [comment]
동의합니다. 네이밍 변경해야겠네요.
