### ISSUE TITLE
Update Swagger doc workflow is not working appropriately

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#908]
**What happened**
`Update Swagger doc` workflow is not working appropriately

**Anything else we need to know?**

https://github.com/cloud-barista/cb-tumblebug/runs/4064628789?check_suite_focus=true

```
Run stefanzweifel/git-auto-commit-action@v4
Started: bash /home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/entrypoint.sh
INPUT_REPOSITORY value: .
INPUT_STATUS_OPTIONS: 
INPUT_BRANCH value: 
From https://github.com/cloud-barista/cb-tumblebug
 * [new branch]      release-0.3.0 -> origin/release-0.3.0
 * [new branch]      release-0.4.0 -> origin/release-0.4.0
 * [new tag]         v0.4.0        -> v0.4.0
M	src/api/rest/docs/docs.go
Your branch is up to date with 'origin/main'.
INPUT_ADD_OPTIONS: 
INPUT_FILE_PATTERN: src/api/rest/docs/**
INPUT_COMMIT_OPTIONS: 
INPUT_COMMIT_USER_NAME: GitHub Actions
INPUT_COMMIT_USER_EMAIL: actions@github.com
INPUT_COMMIT_MESSAGE: Update Swagger docs
INPUT_COMMIT_AUTHOR: seokho-son <seokho-son@users.noreply.github.com>
[main ea709ea] Update Swagger docs
 Author: seokho-son <seokho-son@users.noreply.github.com>
 1 file changed, 11 insertions(+), 5 deletions(-)
INPUT_TAGGING_MESSAGE: 
No tagging message supplied. No tag will be added.
INPUT_PUSH_OPTIONS: 
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: At least 1 approving review is required by reviewers with write access.        
To https://github.com/cloud-barista/cb-tumblebug
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/cloud-barista/cb-tumblebug'
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

It seems the workflow cannot push commit since `remote: error: At least 1 approving review is required by reviewers with write access.`

**Comment by seokho-son** [comment]
Ref the initial contribution : PR #804

**Comment by jihoon-seo** [comment]
[안]
1. approve 액션을 현재 workflow YAML 에 추가하거나
2. `main` 브랜치가 현재 Protected branch 인데, 이를 해제하거나 (조건 완화)
3. workflow가 현재 'push a commit' 하도록 되어 있는데, 이를 'open a PR' 하도록 변경 (🤔)
   - 'push a commit' vs. 'open a PR' 에 대한 논의: 
   - https://github.com/cloud-barista/cb-tumblebug/issues/804#issuecomment-946788217
   - https://github.com/cloud-barista/cb-tumblebug/issues/804#issuecomment-950314211

**Comment by seokho-son** [comment]
@jihoon-seo 
1번이 일단 가장 쉬운 수정 형태일까요? 

저는.. ㅎㅎ 3번이 좋긴 하네요.. 조금 더 안심할 수 있어요.. ㅎㅎ

**Comment by hermitkim1** [comment]
`force-push`도 가능한것 같긴한데요. 저도 3번이 안전한것 같습니다 ^^

Ref: https://github.com/stefanzweifel/git-auto-commit-action

```diff
      - name: Commit generated Swagger docs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: src/api/rest/docs/**
          commit_message: Update Swagger docs
+         push_optinos: '--force'          
```

**Comment by seokho-son** [comment]
@hermitkim1 아마 --force 는 리뷰어 승인 없이도 강제 푸시한다는 의미는 아닐거예요. 
저건 아마도.. 음... base가 다른 형태인 경우 force push 해주는 그것..

그럼.. 3번.. 으로 수정해보시죠~!
@hermitkim1 @jihoon-seo 혹시 ~ 쉽게 수정 가능하신가요? 아님 contribution invite가 필요할까용?

**Comment by seokho-son** [comment]
일단~ 오류 방지를 위해서 workflow는 disable 해두었습니다.
그리고 forked 리포에서도 여전히 동작을 시도하는 듯 하네요?

**Comment by hermitkim1** [comment]
@seokho-son, 혹시 forked repository > Settings > Actions > General > Actions permissions 의 설정 값(`Allow local actions only`)을 알 수 있을지요? ^^

> 일단~ 오류 방지를 위해서 workflow는 disable 해두었습니다. 그리고 forked 리포에서도 여전히 동작을 시도하는 듯 하네요?

**Comment by seokho-son** [comment]
@hermitkim1 제가 Allow select actions 으로 오피셜 액션들만 사용하게 하고 있었어요 ㅎㅎ (왜그랬을까요)

**Comment by seokho-son** [comment]
stefanzweifel/git-auto-commit-action@v4 요거 추가하여 처리하였습니당.

**Comment by jihoon-seo** [comment]
/assign @jihoon-seo 

@seokho-son 
> 그럼.. 3번.. 으로 수정해보시죠~!
> @hermitkim1 @jihoon-seo 혹시 ~ 쉽게 수정 가능하신가요? 아님 contribution invite가 필요할까용?

제가 해 볼게요 😊
