### ISSUE TITLE
Improve error message for validation for naming convention

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#950]
**What would you like to be enhanced**
Improve error message for validation for naming convention

**Why is this needed**
For a better understanding for errors in validation for naming convention 

**Proposed solution**
Find `"NotObeyingNamingConvention"` from all source code files, 
and replace all to error message like `err.Error()`

For instance,
Replace `"NotObeyingNamingConvention"` to `err.Error()` which returns error message in string.

https://github.com/cloud-barista/cb-tumblebug/blob/0ed6b1d8f11c03eb891581037208377b0eebf5ad/src/core/mcis/provisioning.go#L142

**Comment by seokho-son** [comment]
Currently, there are 11 occurrences of "NotObeyingNamingConvention".

**Comment by atg0831** [comment]
@seokho-son 
제가 수정해보겠습니다~

**Comment by seokho-son** [comment]
@atg0831 감사합니다!! :)
